MOM6: isomip_initialization Module Reference
isomip_initialization Module Reference
Functions/Subroutines
subroutine, public isomip_initialize_topography (D, G, param_file, max_depth)
Initialization of topography.
subroutine, public isomip_initialize_thickness (h, G, GV, param_file, tv)
Initialization of thicknesses.
subroutine, public isomip_initialize_temperature_salinity (T, S, h, G, GV, param_file, eqn_of_state)
Initial values for temperature and salinity.
subroutine, public isomip_initialize_sponges (G, GV, tv, PF, CSp)
Sets up the the inverse restoration time (Idamp), and.
Variables
character(len=40) mod = "ISOMIP_initialization"
Function/Subroutine Documentation
subroutine, public isomip_initialization::isomip_initialize_sponges (type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, type(thermo_var_ptrs), intent(in) tv, type(param_file_type), intent(in) PF, type(ale_sponge_cs), pointer CSp)
Sets up the the inverse restoration time (Idamp), and.
Parameters
[in] g The ocean's grid structure.
[in] gv The ocean's vertical grid structure.
[in] tv A structure containing pointers to any available thermodynamic fields, potential temperature and salinity or mixed layer density. Absent fields have NULL ptrs.
[in] pf A structure indicating the open file to parse for model parameter values.
csp A pointer that is set to point to the control structure for this module.
Definition at line 330 of file ISOMIP_initialization.F90.
   type(ocean_grid_type), intent(in) :: g    !< The ocean's grid structure.
   type(verticalgrid_type), intent(in) :: gv !< The ocean's vertical grid structure.
   type(thermo_var_ptrs), intent(in) :: tv   !< A structure containing pointers
                                             !! to any available thermodynamic
                                             !! fields, potential temperature and
                                             !! salinity or mixed layer density.
                                             !! Absent fields have NULL ptrs.
   type(param_file_type), intent(in) :: pf   !< A structure indicating the
                                             !! open file to parse for model
                                             !! parameter values.
   type(ale_sponge_cs),   pointer    :: csp  !< A pointer that is set to point to
                                             !! the control structure for this module.
   ! Local variables
   real :: t(szi_(g),szj_(g),szk_(g))  ! A temporary array for temp
   real :: s(szi_(g),szj_(g),szk_(g))  ! A temporary array for salt
   real :: rho(szi_(g),szj_(g),szk_(g))  ! A temporary array for RHO
   real :: h(szi_(g),szj_(g),szk_(g))  ! A temporary array for thickness
   real :: idamp(szi_(g),szj_(g))    ! The inverse damping rate, in s-1.
   real :: tnudg                     ! Nudging time scale, days
   real      :: s_sur, t_sur;        ! Surface salinity and temerature in sponge
   real      :: s_bot, t_bot;        ! Bottom salinity and temerature in sponge
   real      :: t_ref, s_ref         ! reference T and S
   real      :: rho_sur, rho_bot, rho_range, t_range, s_range
   real :: e0(szk_(g))               ! The resting interface heights, in m, usually !
                                     ! negative because it is positive upward.      !
   real :: eta1d(szk_(g)+1)          ! Interface height relative to the sea surface !
                                     ! positive upward, in m.
   real :: min_depth, dummy1, z, delta_h
   real :: damp, rho_dummy, min_thickness, rho_tmp, xi0
   character(len=40) :: verticalcoordinate
   character(len=40)  :: mod = "ISOMIP_initialize_sponges" ! This subroutine's name.
   integer :: i, j, k, is, ie, js, je, isd, ied, jsd, jed, nz
   is = g%isc ; ie = g%iec ; js = g%jsc ; je = g%jec ; nz = g%ke
   isd = g%isd ; ied = g%ied ; jsd = g%jsd ; jed = g%jed
   call get_param(pf,mod,"MIN_THICKNESS",min_thickness,'Minimum layer thickness',units='m',default=1.e-3)
   call get_param(pf,mod,"REGRIDDING_COORDINATE_MODE", verticalcoordinate, &
             default=default_coordinate_mode)
   call get_param(pf, mod, "ISOMIP_TNUDG", tnudg, 'Nudging time scale for sponge layers (days)',  default=0.0)
   call get_param(pf, mod, "T_REF", t_ref, 'Reference temperature',  default=10.0,&
                  do_not_log=.true.)
   call get_param(pf, mod, "S_REF", s_ref, 'Reference salinity',  default=35.0,&
                  do_not_log=.true.)
   call get_param(pf, mod, "ISOMIP_S_SUR_SPONGE", s_sur, 'Surface salinity in sponge layer.',  default=s_ref)
   call get_param(pf, mod, "ISOMIP_S_BOT_SPONGE", s_bot, 'Bottom salinity in sponge layer.',  default=s_ref)
   call get_param(pf, mod, "ISOMIP_T_SUR_SPONGE", t_sur, 'Surface temperature in sponge layer.',  default=t_ref)
   call get_param(pf, mod, "ISOMIP_T_BOT_SPONGE", t_bot, 'Bottom temperature in sponge layer.',  default=t_ref)
   t(:,:,:) = 0.0 ; s(:,:,:) = 0.0 ; idamp(:,:) = 0.0; rho(:,:,:) = 0.0
   s_range = s_sur - s_bot
   t_range = t_sur - t_bot
 !   Set up sponges for ISOMIP configuration
   call get_param(pf, mod, "MINIMUM_DEPTH", min_depth, &
                  "The minimum depth of the ocean.", units="m", default=0.0)
   select case ( coordinatemode(verticalcoordinate) )
   case ( regridding_layer, regridding_rho )
     ! Compute min/max density using T_SUR/S_SUR and T_BOT/S_BOT
     call calculate_density(t_sur,s_sur,0.0,rho_sur,tv%eqn_of_state)
     !write (*,*)'Surface density in sponge:', rho_sur
     call calculate_density(t_bot,s_bot,0.0,rho_bot,tv%eqn_of_state)
     !write (*,*)'Bottom density in sponge:', rho_bot
     rho_range = rho_bot - rho_sur
     !write (*,*)'Density range in sponge:', rho_range
     ! Construct notional interface positions
     e0(1) = 0.
     do k=2,nz
       e0(k) = -g%max_depth * ( 0.5 * ( gv%Rlay(k-1) + gv%Rlay(k) ) - rho_sur ) / rho_range
       e0(k) = min( 0., e0(k) ) ! Bound by surface
       e0(k) = max( -g%max_depth, e0(k) ) ! Bound by possible deepest point in model
       !write(*,*)'G%max_depth,GV%Rlay(k-1),GV%Rlay(k),e0(k)',G%max_depth,GV%Rlay(k-1),GV%Rlay(k),e0(k)
     enddo
     e0(nz+1) = -g%max_depth
     ! Calculate thicknesses
     do j=js,je ; do i=is,ie
       eta1d(nz+1) = -1.0*g%bathyT(i,j)
       do k=nz,1,-1
         eta1d(k) = e0(k)
         if (eta1d(k) < (eta1d(k+1) + gv%Angstrom_z)) then
           eta1d(k) = eta1d(k+1) + gv%Angstrom_z
           h(i,j,k) = gv%Angstrom_z
         else
           h(i,j,k) = eta1d(k) - eta1d(k+1)
         endif
       enddo
     enddo ; enddo
   case ( regridding_zstar )                       ! Initial thicknesses for z coordinates
     do j=js,je ; do i=is,ie
       eta1d(nz+1) = -1.0*g%bathyT(i,j)
       do k=nz,1,-1
         eta1d(k) =  -g%max_depth * real(k-1) / real(nz)
         if (eta1d(k) < (eta1d(k+1) + min_thickness)) then
           eta1d(k) = eta1d(k+1) + min_thickness
           h(i,j,k) = min_thickness
         else
           h(i,j,k) = eta1d(k) - eta1d(k+1)
         endif
       enddo
    enddo ; enddo
    case ( regridding_sigma )             ! Initial thicknesses for sigma coordinates
     do j=js,je ; do i=is,ie
       delta_h = g%bathyT(i,j) / dfloat(nz)
       h(i,j,:) = delta_h
     end do ; end do
   case default
       call mom_error(fatal,"ISOMIP_initialize_sponges: "// &
       "Unrecognized i.c. setup - set REGRIDDING_COORDINATE_MODE")
   end select
 !  Here the inverse damping time, in s-1, is set. Set Idamp to 0     !
 !  wherever there is no sponge, and the subroutines that are called  !
 !  will automatically set up the sponges only where Idamp is positive!
 !  and mask2dT is 1.
    do i=is,ie; do j=js,je
       if (g%geoLonT(i,j) >= 790.0 .AND. g%geoLonT(i,j) <= 800.0) then
 ! 1 / day
         dummy1=(g%geoLonT(i,j)-790.0)/(800.0-790.0)
         damp = 1.0/tnudg * max(0.0,dummy1)
       else ; damp=0.0
       endif
 ! convert to 1 / seconds
       if (g%bathyT(i,j) > min_depth) then
           idamp(i,j) = damp/86400.0
       else ; idamp(i,j) = 0.0 ; endif
    enddo ; enddo
    if (associated(csp)) then
     call mom_error(warning, "ISOMIP_initialize_sponges called with an associated "// &
                             "control structure.")
     return
   endif
 !  This call sets up the damping rates and interface heights.
 !  This sets the inverse damping timescale fields in the sponges.    !
   call initialize_ale_sponge(idamp,h, nz, g, pf, csp)
 ! setup temp and salt at the sponge zone
   select case ( coordinatemode(verticalcoordinate) )
     case (  regridding_sigma, regridding_zstar, regridding_rho )
       s_range = s_range / g%max_depth ! Convert S_range into dS/dz
       t_range = t_range / g%max_depth ! Convert T_range into dT/dz
       do j=js,je ; do i=is,ie
         xi0 = -g%bathyT(i,j);
         do k = nz,1,-1
           xi0 = xi0 + 0.5 * h(i,j,k) ! Depth in middle of layer
           s(i,j,k) = s_sur + s_range * xi0
           t(i,j,k) = t_sur + t_range * xi0
           xi0 = xi0 + 0.5 * h(i,j,k) ! Depth at top of layer
         enddo
       enddo ; enddo
   i=g%iec; j=g%jec
   do k = 1,nz
     call calculate_density(t(i,j,k),s(i,j,k),0.0,rho_tmp,tv%eqn_of_state)
     !write(*,*) 'Sponge - k,h,T,S,rho,Rlay',k,h(i,j,k),T(i,j,k),S(i,j,k),rho_tmp,GV%Rlay(k)
   enddo
    case default
       call mom_error(fatal,"isomip_initialize_sponge: "// &
       "Unrecognized i.c. setup - set REGRIDDING_COORDINATE_MODE")
   end select
 !   Now register all of the fields which are damped in the sponge.   !
 ! By default, momentum is advected vertically within the sponge, but !
 ! momentum is typically not damped within the sponge.                !
 !  The remaining calls to set_up_sponge_field can be in any order. !
   if ( associated(tv%T) ) then
       call set_up_ale_sponge_field(t,g,tv%T,csp)
   endif
   if ( associated(tv%S) ) then
     call set_up_ale_sponge_field(s,g,tv%S,csp)
   endif
subroutine, public isomip_initialization::isomip_initialize_temperature_salinity (real, dimension(szi_(g),szj_(g), szk_(g)), intent(out) T, real, dimension(szi_(g),szj_(g), szk_(g)), intent(out) S, real, dimension(szi_(g),szj_(g), szk_(g)), intent(in) h, type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, type(param_file_type), intent(in) param_file, type(eos_type), pointer eqn_of_state)
Initial values for temperature and salinity.
Parameters
[in] g Ocean grid structure
[in] gv Vertical grid structure
[out] t Potential temperature (degC)
[out] s Salinity (ppt)
[in] h Layer thickness (m or Pa)
[in] param_file Parameter file structure
eqn_of_state Equation of state structure
Definition at line 248 of file ISOMIP_initialization.F90.
References mod, mom_error_handler::mom_error(), regrid_consts::regridding_rho, and regrid_consts::regridding_sigma.
Referenced by mom_state_initialization::mom_initialize_state().
   type(ocean_grid_type),                     intent(in)  :: g !< Ocean grid structure
   type(verticalgrid_type),                   intent(in)  :: gv !< Vertical grid structure
   real, dimension(SZI_(G),SZJ_(G), SZK_(G)), intent(out) :: t !< Potential temperature (degC)
   real, dimension(SZI_(G),SZJ_(G), SZK_(G)), intent(out) :: s !< Salinity (ppt)
   real, dimension(SZI_(G),SZJ_(G), SZK_(G)), intent(in)  :: h !< Layer thickness (m or Pa)
   type(param_file_type),                     intent(in)  :: param_file !< Parameter file structure
   type(eos_type),                            pointer     :: eqn_of_state !< Equation of state structure
   ! Local variables
   integer   :: i, j, k, is, ie, js, je, nz
   real      :: x, ds, dt, rho_sur, rho_bot
   real      :: xi0, xi1, dxi, r, s_sur, t_sur, s_bot, t_bot, s_range, t_range
   real      :: z          ! vertical position in z space
   character(len=40) :: verticalcoordinate, density_profile
   real :: rho_tmp
   is = g%isc ; ie = g%iec ; js = g%jsc ; je = g%jec ; nz = g%ke
   call get_param(param_file,mod,"REGRIDDING_COORDINATE_MODE", verticalcoordinate, &
             default=default_coordinate_mode)
   call get_param(param_file, mod, "ISOMIP_T_SUR",t_sur,'Temperature at the surface (interface)', default=-1.9,&
                  do_not_log=.true.)
   call get_param(param_file, mod, "ISOMIP_S_SUR", s_sur, 'Salinity at the surface (interface)',  default=33.8,&
                  do_not_log=.true.)
   call get_param(param_file, mod, "ISOMIP_T_BOT", t_bot, 'Temperature at the bottom (interface)', default=-1.9,&
                  do_not_log=.true.)
   call get_param(param_file, mod, "ISOMIP_S_BOT", s_bot,'Salinity at the bottom (interface)', default=34.55,&
                  do_not_log=.true.)
   call calculate_density(t_sur,s_sur,0.0,rho_sur,eqn_of_state)
   !write (*,*)'Density in the surface layer:', rho_sur
   call calculate_density(t_bot,s_bot,0.0,rho_bot,eqn_of_state)
   !write (*,*)'Density in the bottom layer::', rho_bot
   s_range = s_sur - s_bot
   t_range = t_sur - t_bot
   select case ( coordinatemode(verticalcoordinate) )
     case (  regridding_rho, regridding_zstar, regridding_sigma )
       s_range = s_range / g%max_depth ! Convert S_range into dS/dz
       t_range = t_range / g%max_depth ! Convert T_range into dT/dz
       do j=js,je ; do i=is,ie
         xi0 = -g%bathyT(i,j);
         do k = nz,1,-1
           xi0 = xi0 + 0.5 * h(i,j,k) ! Depth in middle of layer
           s(i,j,k) = s_sur + s_range * xi0
           t(i,j,k) = t_sur + t_range * xi0
           xi0 = xi0 + 0.5 * h(i,j,k) ! Depth at top of layer
         enddo
       enddo ; enddo
 !i=G%iec; j=G%jec
 !do k = 1,nz
 !  call calculate_density(T(i,j,k),S(i,j,k),0.0,rho_tmp,eqn_of_state)
 !  !write(*,*) 'k,h,T,S,rho,Rlay',k,h(i,j,k),T(i,j,k),S(i,j,k),rho_tmp,GV%Rlay(k)
 !enddo
 !   case ( REGRIDDING_ZSTAR, REGRIDDING_SIGMA )
 !
 !      do j=js,je ; do i=is,ie
 !        xi0 = 0.0;
 !        do k = 1,nz
 !          xi1 = xi0 + h(i,j,k) / G%max_depth;
 !          S(i,j,k) = S_sur + 0.5 * S_range * (xi0 + xi1);
 !          T(i,j,k) = T_sur + 0.5 * T_range * (xi0 + xi1);
 !          xi0 = xi1;
 !        enddo
 !      enddo ; enddo
    case default
       call mom_error(fatal,"isomip_initialize: "// &
       "Unrecognized i.c. setup - set REGRIDDING_COORDINATE_MODE")
   end select
subroutine, public isomip_initialization::isomip_initialize_thickness (real, dimension(szi_(g),szj_(g), szk_(g)), intent(out) h, type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, type(param_file_type), intent(in) param_file, type(thermo_var_ptrs), intent(in) tv)
Initialization of thicknesses.
Parameters
[in] g The ocean's grid structure.
[in] gv The ocean's vertical grid structure.
[out] h The thickness that is being initialized.
[in] param_file A structure indicating the open file to parse for model parameter values.
[in] tv A structure containing pointers to any available thermodynamic fields, including eq. of state.
Definition at line 147 of file ISOMIP_initialization.F90.
References mod, mom_error_handler::mom_error(), mom_error_handler::mom_mesg(), regrid_consts::regridding_rho, and regrid_consts::regridding_sigma.
   type(ocean_grid_type), intent(in) :: g                !< The ocean's grid structure.
   type(verticalgrid_type), intent(in) :: gv             !< The ocean's vertical grid structure.
   real, intent(out), dimension(SZI_(G),SZJ_(G), SZK_(G)) :: h !< The thickness that is being
                                                         !! initialized.
   type(param_file_type), intent(in) :: param_file       !< A structure indicating the
                                                         !! open file to parse for model
                                                         !! parameter values.
   type(thermo_var_ptrs), intent(in) :: tv               !< A structure containing pointers
                                                         !! to any available thermodynamic
                                                         !! fields, including eq. of state.
   ! Local variables
   real :: e0(szk_(g)+1)     ! The resting interface heights, in m, usually !
                           ! negative because it is positive upward.      !
   real :: eta1d(szk_(g)+1)! Interface height relative to the sea surface !
                           ! positive upward, in m.                       !
   integer :: i, j, k, is, ie, js, je, nz, tmp1
   real    :: x
   real    :: delta_h, rho_range
   real    :: min_thickness, s_sur, s_bot, t_sur, t_bot, rho_sur, rho_bot
   character(len=40) :: verticalcoordinate
   is = g%isc ; ie = g%iec ; js = g%jsc ; je = g%jec ; nz = g%ke
   call mom_mesg("MOM_initialization.F90, initialize_thickness_uniform: setting thickness")
   call get_param(param_file,mod,"MIN_THICKNESS",min_thickness,'Minimum layer thickness',units='m',default=1.e-3)
   call get_param(param_file,mod,"REGRIDDING_COORDINATE_MODE", verticalcoordinate, &
             default=default_coordinate_mode)
   select case ( coordinatemode(verticalcoordinate) )
   case ( regridding_layer, regridding_rho ) ! Initial thicknesses for isopycnal coordinates
     call get_param(param_file, mod, "ISOMIP_T_SUR",t_sur,'Temperature at the surface (interface)', default=-1.9)
     call get_param(param_file, mod, "ISOMIP_S_SUR", s_sur, 'Salinity at the surface (interface)',  default=33.8)
     call get_param(param_file, mod, "ISOMIP_T_BOT", t_bot, 'Temperature at the bottom (interface)', default=-1.9)
     call get_param(param_file, mod, "ISOMIP_S_BOT", s_bot,'Salinity at the bottom (interface)', default=34.55)
     ! Compute min/max density using T_SUR/S_SUR and T_BOT/S_BOT
     call calculate_density(t_sur,s_sur,0.0,rho_sur,tv%eqn_of_state)
     !write (*,*)'Surface density is:', rho_sur
     call calculate_density(t_bot,s_bot,0.0,rho_bot,tv%eqn_of_state)
     !write (*,*)'Bottom density is:', rho_bot
     rho_range = rho_bot - rho_sur
     !write (*,*)'Density range is:', rho_range
     ! Construct notional interface positions
     e0(1) = 0.
     do k=2,nz
       e0(k) = -g%max_depth * ( 0.5 * ( gv%Rlay(k-1) + gv%Rlay(k) ) - rho_sur ) / rho_range
       e0(k) = min( 0., e0(k) ) ! Bound by surface
       e0(k) = max( -g%max_depth, e0(k) ) ! Bound by possible deepest point in model
       !write(*,*)'G%max_depth,GV%Rlay(k-1),GV%Rlay(k),e0(k)',G%max_depth,GV%Rlay(k-1),GV%Rlay(k),e0(k)
     enddo
     e0(nz+1) = -g%max_depth
     ! Calculate thicknesses
     do j=js,je ; do i=is,ie
       eta1d(nz+1) = -1.0*g%bathyT(i,j)
       do k=nz,1,-1
         eta1d(k) = e0(k)
         if (eta1d(k) < (eta1d(k+1) + gv%Angstrom_z)) then
           eta1d(k) = eta1d(k+1) + gv%Angstrom_z
           h(i,j,k) = gv%Angstrom_z
         else
           h(i,j,k) = eta1d(k) - eta1d(k+1)
         endif
       enddo
     enddo ; enddo
   case ( regridding_zstar )                       ! Initial thicknesses for z coordinates
     do j=js,je ; do i=is,ie
       eta1d(nz+1) = -1.0*g%bathyT(i,j)
       do k=nz,1,-1
         eta1d(k) =  -g%max_depth * real(k-1) / real(nz)
         if (eta1d(k) < (eta1d(k+1) + min_thickness)) then
           eta1d(k) = eta1d(k+1) + min_thickness
           h(i,j,k) = min_thickness
         else
           h(i,j,k) = eta1d(k) - eta1d(k+1)
         endif
       enddo
    enddo ; enddo
   case ( regridding_sigma )             ! Initial thicknesses for sigma coordinates
     do j=js,je ; do i=is,ie
       delta_h = g%bathyT(i,j) / dfloat(nz)
       h(i,j,:) = delta_h
     end do ; end do
   case default
       call mom_error(fatal,"isomip_initialize: "// &
       "Unrecognized i.c. setup - set REGRIDDING_COORDINATE_MODE")
   end select
subroutine, public isomip_initialization::isomip_initialize_topography (real, dimension(szi_(g),szj_(g)), intent(out) D, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, real, intent(in) max_depth)
Initialization of topography.
Parameters
[in] g The ocean's grid structure.
[out] d The bottom depth in m.
[in] param_file A structure indicating the open file to parse for model parameter values.
[in] max_depth Maximum depth.
Definition at line 61 of file ISOMIP_initialization.F90.
References mom_file_parser::log_version(), and mom_error_handler::mom_mesg().
Referenced by mom_fixed_initialization::mom_initialize_topography().
   type(ocean_grid_type), intent(in)           :: g          !< The ocean's grid structure.
   real, intent(out), dimension(SZI_(G),SZJ_(G)) :: d        !< The bottom depth in m.
   type(param_file_type), intent(in)           :: param_file !< A structure indicating the
                                                             !! open file to parse for model
                                                             !! parameter values.
   real,                  intent(in)           :: max_depth  !< Maximum depth.
 ! This subroutine sets up the ISOMIP topography
   real :: min_depth ! The minimum and maximum depths in m.
 ! The following variables are used to set up the bathymetry in the ISOMIP example.
 ! check this paper: http://www.geosci-model-dev-discuss.net/8/9859/2015/gmdd-8-9859-2015.pdf
   real :: bmax            ! max depth of bedrock topography
   real :: b0,b2,b4,b6     ! first, second, third and fourth bedrock topography coeff
   real :: xbar           ! characteristic along-flow lenght scale of the bedrock
   real :: dc              ! depth of the trough compared with side walls
   real :: fc              ! characteristic width of the side walls of the channel
   real :: wc              ! half-width of the trough
   real :: ly              ! domain width (across ice flow)
   real :: bx, by, xtil    ! dummy vatiables
   logical :: is_2d         ! If true, use 2D setup
 ! G%ieg and G%jeg are the last indices in the global domain
 !  real, dimension (G%ieg) :: xtil    ! eq. 3
 !  real, dimension (G%ieg) :: bx            ! eq. 2
 !  real, dimension (G%ieg,G%jeg) :: dummy1            ! dummy array
 !  real, dimension (G%jeg) :: by            ! eq. 4
 ! This include declares and sets the variable "version".
 #include "version_variable.h"
   character(len=40)  :: mod = "ISOMIP_initialize_topography" ! This subroutine's name.
   integer :: i, j, is, ie, js, je, isd, ied, jsd, jed
   is = g%isc ; ie = g%iec ; js = g%jsc ; je = g%jec
   isd = g%isd ; ied = g%ied ; jsd = g%jsd ; jed = g%jed
   call mom_mesg("  ISOMIP_initialization.F90, ISOMIP_initialize_topography: setting topography", 5)
   call log_version(param_file, mod, version, "")
   call get_param(param_file, mod, "MINIMUM_DEPTH", min_depth, &
                  "The minimum depth of the ocean.", units="m", default=0.0)
   call get_param(param_file, mod, "ISOMIP_2D",is_2d,'If true, use a 2D setup.', default=.false.)
 ! The following variables should be transformed into runtime parameters?
   bmax=720.0; b0=-150.0; b2=-728.8; b4=343.91; b6=-50.57
   xbar=300.0e3; dc=500.0; fc=4.0e3; wc=24.0e3; ly=80.0e3
   bx = 0.0; by = 0.0; xtil = 0.0
   if (is_2d) then
     do j=js,je ; do i=is,ie
       ! 2D setup
       xtil = g%geoLonT(i,j)*1.0e3/xbar
       !xtil = 450*1.0e3/xbar
       bx = b0+b2*xtil**2 + b4*xtil**4 + b6*xtil**6
       !by = (dc/(1.+exp(-2.*(G%geoLatT(i,j)*1.0e3- ly/2. - wc)/fc))) + &
       !        (dc/(1.+exp(2.*(G%geoLatT(i,j)*1.0e3- ly/2. + wc)/fc)))
       by = (dc/(1.+exp(-2.*(20.*1.0e3- ly/2. - wc)/fc))) + &
            (dc/(1.+exp(2.*(20.*1.0e3- ly/2. + wc)/fc)))
       d(i,j) = -max(bx+by,-bmax)
       if (d(i,j) > max_depth) d(i,j) = max_depth
       if (d(i,j) < min_depth) d(i,j) = 0.5*min_depth
     enddo ; enddo
   else
     do j=js,je ; do i=is,ie
       ! 3D
       xtil = g%geoLonT(i,j)*1.0e3/xbar
       bx = b0+b2*xtil**2 + b4*xtil**4 + b6*xtil**6
       by = (dc/(1.+exp(-2.*(g%geoLatT(i,j)*1.0e3- ly/2. - wc)/fc))) + &
               (dc/(1.+exp(2.*(g%geoLatT(i,j)*1.0e3- ly/2. + wc)/fc)))
       d(i,j) = -max(bx+by,-bmax)
       if (d(i,j) > max_depth) d(i,j) = max_depth
       if (d(i,j) < min_depth) d(i,j) = 0.5*min_depth
     enddo ; enddo
   endif
Variable Documentation
character(len=40) isomip_initialization::mod = "ISOMIP_initialization" private
Definition at line 44 of file ISOMIP_initialization.F90.
Referenced by isomip_initialize_temperature_salinity(), and isomip_initialize_thickness().
 character(len=40) :: mod = "ISOMIP_initialization" ! This module's name.