MOM6: cvmix_kinds_and_types Module Reference
cvmix_kinds_and_types Module Reference
Data Types
type cvmix_data_type
type cvmix_global_params_type
Variables
integer, parameter, public cvmix_r8 = selected_real_kind(15, 307)
integer, parameter, public cvmix_strlen = 256
integer, parameter, public cvmix_overwrite_old_val = 1
integer, parameter, public cvmix_sum_old_and_new_vals = 2
integer, parameter, public cvmix_max_old_and_new_vals = 3
real(cvmix_r8), parameter, public cvmix_zero = real(0, cvmix_r8)
real(cvmix_r8), parameter, public cvmix_one = real(1, cvmix_r8)
real(cvmix_r8), parameter, public cvmix_pi = 3.14159265358979323846_cvmix_r8
Variable Documentation
integer, parameter, public cvmix_kinds_and_types::cvmix_max_old_and_new_vals = 3
Definition at line 45 of file cvmix_kinds_and_types.F90.
Referenced by cvmix_background::cvmix_init_bkgnd_1d(), cvmix_background::cvmix_init_bkgnd_2d(), cvmix_background::cvmix_init_bkgnd_bryanlewis(), cvmix_background::cvmix_init_bkgnd_scalar(), cvmix_convection::cvmix_init_conv(), cvmix_ddiff::cvmix_init_ddiff(), cvmix_kpp::cvmix_init_kpp(), cvmix_shear::cvmix_init_shear(), cvmix_tidal::cvmix_init_tidal(), and cvmix_utils::cvmix_update_wrap().
   integer, parameter, public :: cvmix_max_old_and_new_vals = 3
real(cvmix_r8), parameter, public cvmix_kinds_and_types::cvmix_one = real(1, cvmix_r8)
Definition at line 50 of file cvmix_kinds_and_types.F90.
Referenced by cvmix_kpp::compute_phi_inv(), cvmix_convection::cvmix_coeffs_conv_low(), cvmix_ddiff::cvmix_coeffs_ddiff_low(), cvmix_kpp::cvmix_coeffs_kpp_low(), cvmix_shear::cvmix_coeffs_shear_low(), cvmix_ddiff::cvmix_init_ddiff(), cvmix_kpp::cvmix_init_kpp(), cvmix_kpp::cvmix_kpp_compute_bulk_richardson(), cvmix_kpp::cvmix_kpp_compute_enhanced_diff(), cvmix_kpp::cvmix_kpp_compute_nu_at_obl_depth_lmd94(), cvmix_kpp::cvmix_kpp_compute_shape_function_coeffs(), cvmix_kpp::cvmix_kpp_compute_turbulent_scales_1d_obl(), cvmix_kpp::cvmix_kpp_compute_turbulent_scales_1d_sigma(), and cvmix_math::cvmix_math_poly_interp().
integer, parameter, public cvmix_kinds_and_types::cvmix_overwrite_old_val = 1
Definition at line 43 of file cvmix_kinds_and_types.F90.
Referenced by cvmix_background::cvmix_init_bkgnd_1d(), cvmix_background::cvmix_init_bkgnd_2d(), cvmix_background::cvmix_init_bkgnd_bryanlewis(), cvmix_background::cvmix_init_bkgnd_scalar(), cvmix_convection::cvmix_init_conv(), cvmix_ddiff::cvmix_init_ddiff(), cvmix_kpp::cvmix_init_kpp(), cvmix_shear::cvmix_init_shear(), cvmix_tidal::cvmix_init_tidal(), and cvmix_utils::cvmix_update_wrap().
   integer, parameter, public :: cvmix_overwrite_old_val    = 1
real(cvmix_r8), parameter, public cvmix_kinds_and_types::cvmix_pi = 3.14159265358979323846_cvmix_r8
Definition at line 52 of file cvmix_kinds_and_types.F90.
Referenced by cvmix_background::cvmix_init_bkgnd_bryanlewis().
   real(cvmix_r8), parameter, public :: cvmix_pi   = &
                                        3.14159265358979323846_cvmix_r8
integer, parameter, public cvmix_kinds_and_types::cvmix_r8 = selected_real_kind(15, 307)
Definition at line 39 of file cvmix_kinds_and_types.F90.
   integer, parameter, public :: cvmix_r8     = selected_real_kind(15, 307),   &
                                 cvmix_strlen = 256
integer, parameter, public cvmix_kinds_and_types::cvmix_strlen = 256
Definition at line 39 of file cvmix_kinds_and_types.F90.
integer, parameter, public cvmix_kinds_and_types::cvmix_sum_old_and_new_vals = 2
Definition at line 44 of file cvmix_kinds_and_types.F90.
Referenced by cvmix_background::cvmix_init_bkgnd_1d(), cvmix_background::cvmix_init_bkgnd_2d(), cvmix_background::cvmix_init_bkgnd_bryanlewis(), cvmix_background::cvmix_init_bkgnd_scalar(), cvmix_convection::cvmix_init_conv(), cvmix_ddiff::cvmix_init_ddiff(), cvmix_kpp::cvmix_init_kpp(), cvmix_shear::cvmix_init_shear(), cvmix_tidal::cvmix_init_tidal(), and cvmix_utils::cvmix_update_wrap().
   integer, parameter, public :: cvmix_sum_old_and_new_vals = 2
real(cvmix_r8), parameter, public cvmix_kinds_and_types::cvmix_zero = real(0, cvmix_r8)
Definition at line 50 of file cvmix_kinds_and_types.F90.
Referenced by cvmix_kpp::compute_phi_inv(), cvmix_background::cvmix_coeffs_bkgnd_wrap(), cvmix_convection::cvmix_coeffs_conv_low(), cvmix_convection::cvmix_coeffs_conv_wrap(), cvmix_ddiff::cvmix_coeffs_ddiff_low(), cvmix_ddiff::cvmix_coeffs_ddiff_wrap(), cvmix_kpp::cvmix_coeffs_kpp_low(), cvmix_kpp::cvmix_coeffs_kpp_wrap(), cvmix_shear::cvmix_coeffs_shear_low(), cvmix_shear::cvmix_coeffs_shear_wrap(), cvmix_tidal::cvmix_coeffs_tidal_low(), cvmix_tidal::cvmix_compute_vert_dep(), cvmix_convection::cvmix_get_conv_real(), cvmix_ddiff::cvmix_get_ddiff_real(), cvmix_kpp::cvmix_get_kpp_real(), cvmix_shear::cvmix_get_shear_real(), cvmix_tidal::cvmix_get_tidal_real(), cvmix_convection::cvmix_init_conv(), cvmix_kpp::cvmix_init_kpp(), cvmix_shear::cvmix_init_shear(), cvmix_kpp::cvmix_kpp_compute_bulk_richardson(), cvmix_kpp::cvmix_kpp_compute_enhanced_diff(), cvmix_kpp::cvmix_kpp_compute_nu_at_obl_depth_lmd94(), cvmix_kpp::cvmix_kpp_compute_obl_depth_low(), cvmix_kpp::cvmix_kpp_compute_shape_function_coeffs(), cvmix_kpp::cvmix_kpp_compute_turbulent_scales_1d_obl(), cvmix_kpp::cvmix_kpp_compute_turbulent_scales_1d_sigma(), cvmix_kpp::cvmix_kpp_compute_unresolved_shear(), cvmix_background::cvmix_put_bkgnd_real_1d(), and cvmix_background::cvmix_put_bkgnd_real_2d().
   real(cvmix_r8), parameter, public :: cvmix_zero = real(0,cvmix_r8),         &
                                        cvmix_one  = real(1,cvmix_r8)