MOM6: cvmix_tidal Module Reference
cvmix_tidal Module Reference
Data Types
interface cvmix_coeffs_tidal
interface cvmix_put_tidal
type cvmix_tidal_params_type
Functions/Subroutines
subroutine, public cvmix_init_tidal (CVmix_tidal_params_user, mix_scheme, efficiency, vertical_decay_scale, max_coefficient, local_mixing_frac, depth_cutoff, old_vals)
subroutine cvmix_coeffs_tidal_wrap (CVmix_vars, CVmix_params, energy_flux, CVmix_tidal_params_user)
subroutine cvmix_coeffs_tidal_low (Tdiff_out, Nsqr, zw, zt, OceanDepth, CVmix_params, energy_flux, nlev, max_nlev, CVmix_tidal_params_user)
real(cvmix_r8) function, dimension(nlev+1), public cvmix_compute_vert_dep (zw, zt, nlev, CVmix_tidal_params)
subroutine cvmix_put_tidal_int (varname, val, CVmix_tidal_params_user)
subroutine cvmix_put_tidal_real (varname, val, CVmix_tidal_params_user)
subroutine cvmix_put_tidal_str (varname, val, CVmix_tidal_params_user)
real(cvmix_r8) function, public cvmix_get_tidal_real (varname, CVmix_tidal_params_user)
character(len=cvmix_strlen) function, public cvmix_get_tidal_str (varname, CVmix_tidal_params_user)
Variables
type(cvmix_tidal_params_type), target cvmix_tidal_params_saved
Function/Subroutine Documentation
subroutine cvmix_tidal::cvmix_coeffs_tidal_low (real(cvmix_r8), dimension(max_nlev+1), intent(inout) Tdiff_out, real(cvmix_r8), dimension(max_nlev+1), intent(in) Nsqr, real(cvmix_r8), dimension(max_nlev+1), intent(in) zw, real(cvmix_r8), dimension(max_nlev), intent(in) zt, real(cvmix_r8), intent(in) OceanDepth, type(cvmix_global_params_type), intent(in) CVmix_params, real(cvmix_r8), intent(in) energy_flux, integer, intent(in) nlev, integer, intent(in) max_nlev, type(cvmix_tidal_params_type), intent(in), optional, target CVmix_tidal_params_user) private
Definition at line 282 of file cvmix_tidal.F90.
References cvmix_compute_vert_dep(), cvmix_tidal_params_saved, and cvmix_kinds_and_types::cvmix_zero.
 ! !DESCRIPTION:
 !  Computes vertical diffusion coefficients for tidal mixing
 !  parameterizations.
 !\\
 !\\
 !
 ! !USES:
 !  only those used by entire module.
 ! !INPUT PARAMETERS:
     type(cvmix_tidal_params_type),  target, optional, intent(in) ::           &
                                             cvmix_tidal_params_user
     integer,                               intent(in) :: nlev, max_nlev
     type(cvmix_global_params_type),        intent(in) :: cvmix_params
     real(cvmix_r8),                        intent(in) :: oceandepth,          &
                                                          energy_flux
     real(cvmix_r8), dimension(max_nlev+1), intent(in) :: nsqr, zw
     real(cvmix_r8), dimension(max_nlev),   intent(in) :: zt
 ! !INPUT/OUTPUT PARAMETERS:
     real(cvmix_r8), dimension(max_nlev+1), intent(inout) :: tdiff_out
 !EOP
 !BOC
     ! Local variables
     integer        :: k
     real(cvmix_r8) :: coef, rho
     real(cvmix_r8), dimension(nlev+1) :: vert_dep
     type(cvmix_tidal_params_type), pointer :: cvmix_tidal_params
     if (present(cvmix_tidal_params_user)) then
       cvmix_tidal_params => cvmix_tidal_params_user
     else
       cvmix_tidal_params => cvmix_tidal_params_saved
     end if
     rho  = cvmix_params%FreshWaterDensity
     select case (trim(cvmix_tidal_params%mix_scheme))
       case ('simmons','Simmons')
         vert_dep = cvmix_compute_vert_dep(zw(1:nlev+1), zt(1:nlev), nlev,     &
                                           cvmix_tidal_params)
         coef = cvmix_tidal_params%local_mixing_frac * &
                cvmix_tidal_params%efficiency *        &
                energy_flux
         tdiff_out = cvmix_zero
         if (oceandepth.ge.cvmix_tidal_params%depth_cutoff) then
           do k=1, nlev+1
             if (nsqr(k).gt.cvmix_zero) &
               tdiff_out(k) = coef*vert_dep(k)/(rho*nsqr(k))
             if (tdiff_out(k).gt.cvmix_tidal_params%max_coefficient) &
               tdiff_out(k) = cvmix_tidal_params%max_coefficient
           end do
         end if
       case DEFAULT
         ! Note: this error should be caught in cvmix_init_tidal
         print*, "ERROR: invalid choice for type of tidal mixing."
         stop 1
     end select
 !EOC
subroutine cvmix_tidal::cvmix_coeffs_tidal_wrap (type(cvmix_data_type), intent(inout) CVmix_vars, type(cvmix_global_params_type), intent(in) CVmix_params, real(cvmix_r8), intent(in) energy_flux, type(cvmix_tidal_params_type), intent(in), optional, target CVmix_tidal_params_user) private
Definition at line 229 of file cvmix_tidal.F90.
References cvmix_tidal_params_saved, and cvmix_utils::cvmix_update_wrap().
 ! !DESCRIPTION:
 !  Computes vertical diffusion coefficients for tidal mixing
 !  parameterizations.
 !\\
 !\\
 !
 ! !USES:
 !  only those used by entire module.
 ! !INPUT PARAMETERS:
     type(cvmix_tidal_params_type),  target, optional, intent(in) ::           &
                                             cvmix_tidal_params_user
     type(cvmix_global_params_type), intent(in) :: cvmix_params
     real(cvmix_r8),                 intent(in) :: energy_flux
 ! !INPUT/OUTPUT PARAMETERS:
     type(cvmix_data_type), intent(inout) :: cvmix_vars
 !EOP
 !BOC
     ! Local variables
     real(cvmix_r8), dimension(CVmix_vars%max_nlev+1) :: new_tdiff
     type(cvmix_tidal_params_type),  pointer :: cvmix_tidal_params_in
     integer :: nlev, max_nlev
     cvmix_tidal_params_in => cvmix_tidal_params_saved
     if (present(cvmix_tidal_params_user)) then
       cvmix_tidal_params_in => cvmix_tidal_params_user
     end if
     nlev = cvmix_vars%nlev
     max_nlev = cvmix_vars%max_nlev
     call cvmix_coeffs_tidal(new_tdiff, cvmix_vars%SqrBuoyancyFreq_iface,      &
                             cvmix_vars%zw_iface, cvmix_vars%zt_cntr,          &
                             cvmix_vars%OceanDepth, cvmix_params, energy_flux, &
                             nlev, max_nlev, cvmix_tidal_params_user)
     call cvmix_update_wrap(cvmix_tidal_params_in%handle_old_vals, max_nlev,   &
                            tdiff_out = cvmix_vars%Tdiff_iface,                &
                            new_tdiff = new_tdiff)
 !EOC
real(cvmix_r8) function, dimension(nlev+1), public cvmix_tidal::cvmix_compute_vert_dep (real(cvmix_r8), dimension(nlev+1), intent(in) zw, real(cvmix_r8), dimension(nlev), intent(in) zt, integer, intent(in) nlev, type(cvmix_tidal_params_type), intent(in) CVmix_tidal_params)
Definition at line 357 of file cvmix_tidal.F90.
References cvmix_kinds_and_types::cvmix_zero.
Referenced by cvmix_coeffs_tidal_low().
 ! !DESCRIPTION:
 !  Computes the vertical deposition function needed for Simmons et al tidal
 !  mixing.
 !\\
 !\\
 !
 ! !USES:
 !  only those used by entire module.
 ! !INPUT PARAMETERS:
     type(cvmix_tidal_params_type),     intent(in) :: cvmix_tidal_params
     integer,                           intent(in) :: nlev
     real(cvmix_r8), dimension(nlev+1), intent(in) :: zw
     real(cvmix_r8), dimension(nlev),   intent(in) :: zt
 ! !OUTPUT PARAMETERS:
     real(cvmix_r8), dimension(nlev+1) :: cvmix_compute_vert_dep
 !EOP
 !BOC
     ! Local variables
     real(cvmix_r8) :: tot_area, num, thick
     integer        :: k
     ! Compute vertical deposition
     tot_area = cvmix_zero
     cvmix_compute_vert_dep(1) = cvmix_zero
     cvmix_compute_vert_dep(nlev+1) = cvmix_zero
     do k=2,nlev
       num = -zw(k)/cvmix_tidal_params%vertical_decay_scale
       ! Simmons vertical deposition
       ! Note that it is getting normalized (divide through by tot_area)
       ! So multiplicative constants that are independent of z are omitted
       cvmix_compute_vert_dep(k) = exp(num)
       ! Compute integral of vert_dep via trapezoid rule
       ! (looks like midpoint rule, but vert_dep = 0 at z=0 and z=-ocn_depth)
       thick = zt(k-1) - zt(k)
       tot_area = tot_area + cvmix_compute_vert_dep(k)*thick
     end do
     ! Normalize vert_dep (need integral = 1.0D0)
     cvmix_compute_vert_dep = cvmix_compute_vert_dep/tot_area
 !EOC
real(cvmix_r8) function, public cvmix_tidal::cvmix_get_tidal_real (character(len=*), intent(in) varname, type(cvmix_tidal_params_type), intent(in), optional, target CVmix_tidal_params_user)
Definition at line 559 of file cvmix_tidal.F90.
References cvmix_tidal_params_saved, and cvmix_kinds_and_types::cvmix_zero.
 ! !DESCRIPTION:
 !  Returns the real value of a cvmix\_tidal\_params\_type variable.
 !\\
 !\\
 ! !USES:
 !  Only those used by entire module.
 ! !INPUT PARAMETERS:
     character(len=*),                                intent(in) :: varname
     type(cvmix_tidal_params_type), optional, target, intent(in) ::            &
                                            cvmix_tidal_params_user
 ! !OUTPUT PARAMETERS:
     real(cvmix_r8) :: cvmix_get_tidal_real
 !EOP
 !BOC
     type(cvmix_tidal_params_type), pointer :: cvmix_tidal_params_in
     if (present(cvmix_tidal_params_user)) then
       cvmix_tidal_params_in => cvmix_tidal_params_user
     else
       cvmix_tidal_params_in => cvmix_tidal_params_saved
     end if
     cvmix_get_tidal_real = cvmix_zero
     select case (trim(varname))
       case ('efficiency')
         cvmix_get_tidal_real = cvmix_tidal_params_in%efficiency
       case ('vertical_decay_scale')
         cvmix_get_tidal_real = cvmix_tidal_params_in%vertical_decay_scale
       case ('max_coefficient')
         cvmix_get_tidal_real = cvmix_tidal_params_in%max_coefficient
       case ('local_mixing_frac')
         cvmix_get_tidal_real = cvmix_tidal_params_in%local_mixing_frac
       case ('depth_cutoff')
         cvmix_get_tidal_real = cvmix_tidal_params_in%depth_cutoff
       case DEFAULT
         print*, "ERROR: ", trim(varname), " not a valid choice!"
         stop 1
     end select
 !EOC
character(len=cvmix_strlen) function, public cvmix_tidal::cvmix_get_tidal_str (character(len=*), intent(in) varname, type(cvmix_tidal_params_type), intent(in), optional, target CVmix_tidal_params_user)
Definition at line 614 of file cvmix_tidal.F90.
References cvmix_tidal_params_saved.
 ! !DESCRIPTION:
 !  Returns the string value of a cvmix\_tidal\_params\_type variable.
 !\\
 !\\
 ! !USES:
 !  Only those used by entire module.
 ! !INPUT PARAMETERS:
     character(len=*),                                intent(in) :: varname
     type(cvmix_tidal_params_type), optional, target, intent(in) ::            &
                                            cvmix_tidal_params_user
 ! !OUTPUT PARAMETERS:
     character(len=cvmix_strlen) :: cvmix_get_tidal_str
 !EOP
 !BOC
     type(cvmix_tidal_params_type), pointer :: cvmix_tidal_params_in
     if (present(cvmix_tidal_params_user)) then
       cvmix_tidal_params_in => cvmix_tidal_params_user
     else
       cvmix_tidal_params_in => cvmix_tidal_params_saved
     end if
     select case (trim(varname))
       case ('mix_scheme')
         cvmix_get_tidal_str = trim(cvmix_tidal_params_in%mix_scheme)
       case DEFAULT
         print*, "ERROR: ", trim(varname), " not a valid choice!"
         stop 1
     end select
 !EOC
subroutine, public cvmix_tidal::cvmix_init_tidal (type(cvmix_tidal_params_type), intent(inout), optional, target CVmix_tidal_params_user, character(len=*), intent(in), optional mix_scheme, real(cvmix_r8), intent(in), optional efficiency, real(cvmix_r8), intent(in), optional vertical_decay_scale, real(cvmix_r8), intent(in), optional max_coefficient, real(cvmix_r8), intent(in), optional local_mixing_frac, real(cvmix_r8), intent(in), optional depth_cutoff, character(len=*), intent(in), optional old_vals)
Definition at line 108 of file cvmix_tidal.F90.
References cvmix_kinds_and_types::cvmix_max_old_and_new_vals, cvmix_kinds_and_types::cvmix_overwrite_old_val, cvmix_kinds_and_types::cvmix_sum_old_and_new_vals, and cvmix_tidal_params_saved.
 ! !DESCRIPTION:
 !  Initialization routine for tidal mixing. There is currently just one
 !  supported schemes - set \verb|mix_scheme = 'simmons'| to use the Simmons
 !  mixing scheme.
 !
 ! !USES:
 !  Only those used by entire module.
 ! !INPUT PARAMETERS:
     character(len=*), optional, intent(in) :: mix_scheme, old_vals
     real(cvmix_r8),   optional, intent(in) :: efficiency
     real(cvmix_r8),   optional, intent(in) :: vertical_decay_scale
     real(cvmix_r8),   optional, intent(in) :: max_coefficient
     real(cvmix_r8),   optional, intent(in) :: local_mixing_frac
     real(cvmix_r8),   optional, intent(in) :: depth_cutoff
 ! !OUTPUT PARAMETERS:
     type(cvmix_tidal_params_type), optional, target, intent(inout) ::         &
                                               cvmix_tidal_params_user
 !EOP
 !BOC
     type(cvmix_tidal_params_type), pointer :: cvmix_tidal_params_out
     if (present(cvmix_tidal_params_user)) then
       cvmix_tidal_params_out => cvmix_tidal_params_user
     else
       cvmix_tidal_params_out => cvmix_tidal_params_saved
     end if
     if (present(mix_scheme)) then
       call cvmix_put_tidal("mix_scheme", trim(mix_scheme),                    &
                            cvmix_tidal_params_user)
     else
       call cvmix_put_tidal("mix_scheme", "Simmons", cvmix_tidal_params_user)
     end if
     select case (trim(cvmix_tidal_params_out%mix_scheme))
       case ('simmons','Simmons')
         ! Unitless parameters
         if (present(efficiency)) then
           call cvmix_put_tidal("efficiency", efficiency,                      &
                                cvmix_tidal_params_user)
         else
           call cvmix_put_tidal("efficiency", 0.2_cvmix_r8,                    &
                                cvmix_tidal_params_user)
         end if
         if (present(local_mixing_frac)) then
           call cvmix_put_tidal("local_mixing_frac", local_mixing_frac,        &
                                cvmix_tidal_params_user)
         else
           call cvmix_put_tidal("local_mixing_frac", 3, cvmix_tidal_params_user)
         end if
         ! Parameters with units
         if (present(vertical_decay_scale)) then
           call cvmix_put_tidal("vertical_decay_scale", vertical_decay_scale,  &
                                cvmix_tidal_params_user)
         else
           call cvmix_put_tidal("vertical_decay_scale", 500,                   &
                                cvmix_tidal_params_user)
         end if
         if (present(depth_cutoff)) then
           call cvmix_put_tidal("depth_cutoff", depth_cutoff,                  &
                                cvmix_tidal_params_user)
         else
           ! Default: no cutoff depth => 0 m
           call cvmix_put_tidal("depth_cutoff", 0, cvmix_tidal_params_user)
         end if
         if (present(max_coefficient)) then
           call cvmix_put_tidal("max_coefficient", max_coefficient,            &
                                cvmix_tidal_params_user)
         else
           call cvmix_put_tidal("max_coefficient", 50e-4_cvmix_r8,             &
                                cvmix_tidal_params_user)
         end if
       case DEFAULT
         print*, "ERROR: ", trim(mix_scheme), " is not a valid choice for ", &
                 "tidal mixing."
         stop 1
     end select
     if (present(old_vals)) then
       select case (trim(old_vals))
         case ("overwrite")
           call cvmix_put_tidal('handle_old_vals', cvmix_overwrite_old_val,    &
                                cvmix_tidal_params_user)
         case ("sum")
           call cvmix_put_tidal('handle_old_vals', cvmix_sum_old_and_new_vals, &
                                cvmix_tidal_params_user)
         case ("max")
           call cvmix_put_tidal('handle_old_vals', cvmix_max_old_and_new_vals, &
                                cvmix_tidal_params_user)
         case DEFAULT
           print*, "ERROR: ", trim(old_vals), " is not a valid option for ",   &
                   "handling old values of diff and visc."
           stop 1
       end select
     else
       call cvmix_put_tidal('handle_old_vals', cvmix_overwrite_old_val,        &
                                cvmix_tidal_params_user)
     end if
 !EOC
subroutine cvmix_tidal::cvmix_put_tidal_int (character(len=*), intent(in) varname, integer, intent(in) val, type(cvmix_tidal_params_type), intent(inout), optional, target CVmix_tidal_params_user) private
Definition at line 412 of file cvmix_tidal.F90.
References cvmix_tidal_params_saved.
 ! !DESCRIPTION:
 !  Write an integer value into a cvmix\_tidal\_params\_type variable.
 !\\
 !\\
 ! !USES:
 !  Only those used by entire module.
 ! !INPUT PARAMETERS:
     character(len=*), intent(in) :: varname
     integer,          intent(in) :: val
 ! !OUTPUT PARAMETERS:
     type(cvmix_tidal_params_type), optional, target, intent(inout) ::         &
                                               cvmix_tidal_params_user
 !EOP
 !BOC
     type(cvmix_tidal_params_type), pointer :: cvmix_tidal_params_out
     cvmix_tidal_params_out => cvmix_tidal_params_saved
     if (present(cvmix_tidal_params_user)) then
       cvmix_tidal_params_out => cvmix_tidal_params_user
     end if
     select case (trim(varname))
       case ('old_vals', 'handle_old_vals')
         cvmix_tidal_params_out%handle_old_vals = val
       case DEFAULT
         call cvmix_put_tidal(varname, real(val,cvmix_r8),                     &
                              cvmix_tidal_params_user)
     end select
 !EOC
subroutine cvmix_tidal::cvmix_put_tidal_real (character(len=*), intent(in) varname, real(cvmix_r8), intent(in) val, type(cvmix_tidal_params_type), intent(inout), optional, target CVmix_tidal_params_user) private
Definition at line 457 of file cvmix_tidal.F90.
References cvmix_tidal_params_saved.
 ! !DESCRIPTION:
 !  Write a real value into a cvmix\_tidal\_params\_type variable.
 !\\
 !\\
 ! !USES:
 !  Only those used by entire module.
 ! !INPUT PARAMETERS:
     character(len=*), intent(in) :: varname
     real(cvmix_r8),   intent(in) :: val
 ! !OUTPUT PARAMETERS:
     type(cvmix_tidal_params_type), optional, target, intent(inout) ::         &
                                               cvmix_tidal_params_user
 !EOP
 !BOC
     type(cvmix_tidal_params_type), pointer :: cvmix_tidal_params_out
     if (present(cvmix_tidal_params_user)) then
       cvmix_tidal_params_out => cvmix_tidal_params_user
     else
       cvmix_tidal_params_out => cvmix_tidal_params_saved
     end if
     select case (trim(varname))
       case ('efficiency')
         cvmix_tidal_params_out%efficiency = val
       case ('vertical_decay_scale')
         cvmix_tidal_params_out%vertical_decay_scale = val
       case ('max_coefficient')
         cvmix_tidal_params_out%max_coefficient = val
       case ('local_mixing_frac')
         cvmix_tidal_params_out%local_mixing_frac = val
       case ('depth_cutoff')
         cvmix_tidal_params_out%depth_cutoff = val
       case DEFAULT
         print*, "ERROR: ", trim(varname), " not a valid choice!"
         stop 1
     end select
 !EOC
subroutine cvmix_tidal::cvmix_put_tidal_str (character(len=*), intent(in) varname, character(len=*), intent(in) val, type(cvmix_tidal_params_type), intent(inout), optional, target CVmix_tidal_params_user) private
Definition at line 512 of file cvmix_tidal.F90.
References cvmix_tidal_params_saved.
 ! !DESCRIPTION:
 !  Write a string into a cvmix\_tidal\_params\_type variable.
 !\\
 !\\
 ! !USES:
 !  Only those used by entire module.
 ! !INPUT PARAMETERS:
     character(len=*), intent(in) :: varname
     character(len=*), intent(in) :: val
 ! !OUTPUT PARAMETERS:
     type(cvmix_tidal_params_type), optional, target, intent(inout) ::         &
                                               cvmix_tidal_params_user
 !EOP
 !BOC
     type(cvmix_tidal_params_type), pointer :: cvmix_tidal_params_out
     if (present(cvmix_tidal_params_user)) then
       cvmix_tidal_params_out => cvmix_tidal_params_user
     else
       cvmix_tidal_params_out => cvmix_tidal_params_saved
     end if
     select case (trim(varname))
       case ('mix_scheme')
         cvmix_tidal_params_out%mix_scheme = val
       case DEFAULT
         print*, "ERROR: ", trim(varname), " not a valid choice!"
         stop 1
     end select
 !EOC
Variable Documentation
type(cvmix_tidal_params_type), target cvmix_tidal::cvmix_tidal_params_saved
Definition at line 96 of file cvmix_tidal.F90.
Referenced by cvmix_coeffs_tidal_low(), cvmix_coeffs_tidal_wrap(), cvmix_get_tidal_real(), cvmix_get_tidal_str(), cvmix_init_tidal(), cvmix_put_tidal_int(), cvmix_put_tidal_real(), and cvmix_put_tidal_str().
   type(cvmix_tidal_params_type), target :: cvmix_tidal_params_saved