MOM6: cvmix_shear Module Reference
cvmix_shear Module Reference
Data Types
interface cvmix_coeffs_shear
interface cvmix_put_shear
type cvmix_shear_params_type
Functions/Subroutines
subroutine, public cvmix_init_shear (CVmix_shear_params_user, mix_scheme, PP_nu_zero, PP_alpha, PP_exp, PP_nu_b, PP_kappa_b, KPP_nu_zero, KPP_Ri_zero, KPP_exp, old_vals)
subroutine cvmix_coeffs_shear_wrap (CVmix_vars, CVmix_shear_params_user)
subroutine cvmix_coeffs_shear_low (Mdiff_out, Tdiff_out, RICH, nlev, max_nlev, CVmix_shear_params_user)
subroutine cvmix_put_shear_int (varname, val, CVmix_shear_params_user)
subroutine cvmix_put_shear_real (varname, val, CVmix_shear_params_user)
subroutine cvmix_put_shear_str (varname, val, CVmix_shear_params_user)
real(cvmix_r8) function, public cvmix_get_shear_real (varname, CVmix_shear_params_user)
character(len=cvmix_strlen) function, public cvmix_get_shear_str (varname, CVmix_shear_params_user)
Variables
type(cvmix_shear_params_type), target cvmix_shear_params_saved
Function/Subroutine Documentation
subroutine cvmix_shear::cvmix_coeffs_shear_low (real(cvmix_r8), dimension(max_nlev+1), intent(inout) Mdiff_out, real(cvmix_r8), dimension(max_nlev+1), intent(inout) Tdiff_out, real(cvmix_r8), dimension(max_nlev+1), intent(in) RICH, integer, intent(in) nlev, integer, intent(in) max_nlev, type(cvmix_shear_params_type), intent(in), optional, target CVmix_shear_params_user) private
Definition at line 341 of file cvmix_shear.F90.
References cvmix_kinds_and_types::cvmix_one, cvmix_shear_params_saved, and cvmix_kinds_and_types::cvmix_zero.
 ! !DESCRIPTION:
 !  Computes vertical tracer and velocity mixing coefficients for
 !  shear-type mixing parameterizations. Note that Richardson number
 !  is needed at both T-points and U-points.
 !\\
 !\\
 !
 ! !USES:
 !  only those used by entire module.
 ! !INPUT PARAMETERS:
     type(cvmix_shear_params_type), target, optional, intent(in) ::            &
                                            cvmix_shear_params_user
     integer, intent(in) :: nlev, max_nlev
     real(cvmix_r8), dimension(max_nlev+1), intent(in) :: rich
 ! !INPUT/OUTPUT PARAMETERS:
     real(cvmix_r8), dimension(max_nlev+1), intent(inout) :: mdiff_out,        &
                                                             tdiff_out
 !EOP
 !BOC
     integer                   :: kw ! vertical cell index
     ! Parameters used in both PP81 and LMD94
     real(cvmix_r8)            :: nu_zero, loc_exp
     ! Parameters only used in PP81
     real(cvmix_r8)            :: pp_alpha, pp_nu_b, pp_kappa_b, denom
     ! Parameters only used in LMD94
     real(cvmix_r8)            :: kpp_ri_zero
     type(cvmix_shear_params_type), pointer :: cvmix_shear_params
     if (present(cvmix_shear_params_user)) then
       cvmix_shear_params => cvmix_shear_params_user
     else
       cvmix_shear_params => cvmix_shear_params_saved
     end if
     select case (trim(cvmix_shear_params%mix_scheme))
       case ('PP')
         ! Copy parameters to make the code more legible
         nu_zero    = cvmix_shear_params%PP_nu_zero
         pp_alpha   = cvmix_shear_params%PP_alpha
         loc_exp    = cvmix_shear_params%PP_exp
         pp_nu_b    = cvmix_shear_params%PP_nu_b
         pp_kappa_b = cvmix_shear_params%PP_nu_b
         ! Pacanowski-Philander
         do kw=1,nlev+1
           if (rich(kw).gt.cvmix_zero) then
             denom = cvmix_one + pp_alpha * rich(kw)
           else
             ! Treat non-negative Richardson number as Ri = 0
             denom = cvmix_one
           end if
           mdiff_out(kw) = nu_zero / (denom**loc_exp) + pp_nu_b
           tdiff_out(kw) = mdiff_out(kw) / denom + pp_kappa_b
         end do
       case ('KPP')
         ! Copy parameters to make the code more legible
         nu_zero     = cvmix_shear_params%KPP_nu_zero
         kpp_ri_zero = cvmix_shear_params%KPP_Ri_zero
         loc_exp     = cvmix_shear_params%KPP_exp
         ! Large, et al
         do kw=1,nlev+1
             if (rich(kw).lt.cvmix_zero) then
               tdiff_out(kw) = nu_zero
             else if (rich(kw).lt.kpp_ri_zero) then
               tdiff_out(kw) = nu_zero * (cvmix_one - (rich(kw)/kpp_ri_zero)   &
                                                      **2)**loc_exp
             else ! Ri_g >= Ri_zero
               tdiff_out(kw) = cvmix_zero
             end if
         end do
         ! to do: include global params for prandtl number!
         mdiff_out = tdiff_out
       case DEFAULT
         ! Note: this error should be caught in cvmix_init_shear
         print*, "ERROR: invalid choice for type of shear mixing."
         stop 1
     end select
 !EOC
subroutine cvmix_shear::cvmix_coeffs_shear_wrap (type(cvmix_data_type), intent(inout) CVmix_vars, type(cvmix_shear_params_type), intent(in), optional, target CVmix_shear_params_user) private
Definition at line 285 of file cvmix_shear.F90.
References cvmix_shear_params_saved, cvmix_utils::cvmix_update_wrap(), and cvmix_kinds_and_types::cvmix_zero.
 ! !DESCRIPTION:
 !  Computes vertical tracer and velocity mixing coefficients for
 !  shear-type mixing parameterizations. Note that Richardson number
 !  is needed at both T-points and U-points.
 !\\
 !\\
 !
 ! !USES:
 !  only those used by entire module.
 ! !INPUT PARAMETERS:
     type(cvmix_shear_params_type), target, optional, intent(in) ::            &
                                            cvmix_shear_params_user
 ! !INPUT/OUTPUT PARAMETERS:
     type(cvmix_data_type), intent(inout) :: cvmix_vars
 !EOP
 !BOC
     real(cvmix_r8), dimension(CVmix_vars%max_nlev+1) :: new_mdiff, new_tdiff
     integer :: nlev, max_nlev
     type(cvmix_shear_params_type), pointer :: cvmix_shear_params_in
     if (present(cvmix_shear_params_user)) then
       cvmix_shear_params_in => cvmix_shear_params_user
     else
       cvmix_shear_params_in => cvmix_shear_params_saved
     end if
     nlev = cvmix_vars%nlev
     max_nlev = cvmix_vars%max_nlev
     if (.not.associated(cvmix_vars%Mdiff_iface)) &
       call cvmix_put(cvmix_vars, "Mdiff", cvmix_zero, max_nlev)
     if (.not.associated(cvmix_vars%Tdiff_iface)) &
       call cvmix_put(cvmix_vars, "Tdiff", cvmix_zero, max_nlev)
     call cvmix_coeffs_shear(new_mdiff, new_tdiff,                             &
                             cvmix_vars%ShearRichardson_iface, nlev, max_nlev, &
                             cvmix_shear_params_user)
     call cvmix_update_wrap(cvmix_shear_params_in%handle_old_vals, max_nlev,   &
                            mdiff_out = cvmix_vars%Mdiff_iface,                &
                            new_mdiff = new_mdiff,                             &
                            tdiff_out = cvmix_vars%Tdiff_iface,                &
                            new_tdiff = new_tdiff)
 !EOC
real(cvmix_r8) function, public cvmix_shear::cvmix_get_shear_real (character(len=*), intent(in) varname, type(cvmix_shear_params_type), intent(in), optional, target CVmix_shear_params_user)
Definition at line 592 of file cvmix_shear.F90.
References cvmix_shear_params_saved, and cvmix_kinds_and_types::cvmix_zero.
 ! !DESCRIPTION:
 !  Read the real value of a cvmix\_shear\_params\_type variable.
 !\\
 !\\
 ! !USES:
 !  Only those used by entire module.
 ! !INPUT PARAMETERS:
     character(len=*),                                intent(in) :: varname
     type(cvmix_shear_params_type), optional, target, intent(in) ::            &
                                            cvmix_shear_params_user
 ! !OUTPUT PARAMETERS:
     real(cvmix_r8) :: cvmix_get_shear_real
 !EOP
 !BOC
     type(cvmix_shear_params_type), pointer :: cvmix_shear_params_in
     if (present(cvmix_shear_params_user)) then
       cvmix_shear_params_in => cvmix_shear_params_user
     else
       cvmix_shear_params_in => cvmix_shear_params_saved
     end if
     cvmix_get_shear_real = cvmix_zero
     select case (trim(varname))
       case ('PP_nu_zero')
         cvmix_get_shear_real =cvmix_shear_params_in%PP_nu_zero
       case ('PP_alpha')
         cvmix_get_shear_real =cvmix_shear_params_in%PP_alpha
       case ('PP_exp')
         cvmix_get_shear_real =cvmix_shear_params_in%PP_exp
       case ('KPP_nu_zero')
         cvmix_get_shear_real =cvmix_shear_params_in%KPP_nu_zero
       case ('KPP_Ri_zero')
         cvmix_get_shear_real =cvmix_shear_params_in%KPP_Ri_zero
       case ('KPP_exp')
         cvmix_get_shear_real =cvmix_shear_params_in%KPP_exp
       case DEFAULT
         print*, "ERROR: ", trim(varname), " not a valid choice!"
         stop 1
     end select
 !EOC
character(len=cvmix_strlen) function, public cvmix_shear::cvmix_get_shear_str (character(len=*), intent(in) varname, type(cvmix_shear_params_type), intent(in), optional, target CVmix_shear_params_user)
Definition at line 650 of file cvmix_shear.F90.
References cvmix_shear_params_saved.
 ! !DESCRIPTION:
 !  Read the string contents of a cvmix\_shear\_params\_type variable.
 !\\
 !\\
 ! !USES:
 !  Only those used by entire module.
 ! !INPUT PARAMETERS:
     character(len=*),                                intent(in) :: varname
     type(cvmix_shear_params_type), optional, target, intent(in) ::            &
                                            cvmix_shear_params_user
 ! !OUTPUT PARAMETERS:
     character(len=cvmix_strlen) :: cvmix_get_shear_str
 !EOP
 !BOC
     type(cvmix_shear_params_type), pointer :: cvmix_shear_params_in
     if (present(cvmix_shear_params_user)) then
       cvmix_shear_params_in => cvmix_shear_params_user
     else
       cvmix_shear_params_in => cvmix_shear_params_saved
     end if
     select case (trim(varname))
       case ('mix_scheme')
         cvmix_get_shear_str = trim(cvmix_shear_params_in%mix_scheme)
       case DEFAULT
         print*, "ERROR: ", trim(varname), " not a valid choice!"
         stop 1
     end select
 !EOC
subroutine, public cvmix_shear::cvmix_init_shear (type(cvmix_shear_params_type), intent(inout), optional, target CVmix_shear_params_user, character(len=*), intent(in), optional mix_scheme, real(cvmix_r8), intent(in), optional PP_nu_zero, real(cvmix_r8), intent(in), optional PP_alpha, real(cvmix_r8), intent(in), optional PP_exp, real(cvmix_r8), intent(in), optional PP_nu_b, real(cvmix_r8), intent(in), optional PP_kappa_b, real(cvmix_r8), intent(in), optional KPP_nu_zero, real(cvmix_r8), intent(in), optional KPP_Ri_zero, real(cvmix_r8), intent(in), optional KPP_exp, character(len=*), intent(in), optional old_vals)
Definition at line 122 of file cvmix_shear.F90.
References cvmix_kinds_and_types::cvmix_max_old_and_new_vals, cvmix_kinds_and_types::cvmix_overwrite_old_val, cvmix_shear_params_saved, cvmix_kinds_and_types::cvmix_sum_old_and_new_vals, and cvmix_kinds_and_types::cvmix_zero.
 ! !DESCRIPTION:
 !  Initialization routine for shear (Richardson number-based) mixing. There are
 !  currently two supported schemes - set \verb|mix_scheme = 'PP'| to use the
 !  Pacanowski-Philander mixing scheme or set \verb|mix_scheme = 'KPP'| to use
 !  the interior mixing scheme laid out in Large et al.
 !\\
 !\\
 !  PP requires setting $\nu_0$ (\verb|PP_nu_zero| in this routine), $alpha$
 !  (\verb|PP_alpha|), and $n$ (\verb|PP_exp|), and returns
 !  \begin{eqnarray*}
 !  \nu_{PP} & = & \frac{\nu_0}{(1+\alpha \textrm{Ri})^n} + \nu_b \\
 !  \kappa_{PP} & = & \frac{\nu}{1+\alpha \textrm{Ri}} + \kappa_b
 !  \end{eqnarray*}
 !  Note that $\nu_b$ and $\kappa_b$ are 0 by default, with the assumption that
 !  background diffusivities are computed in the \verb|cvmix_background| module
 ! \\
 ! \\
 ! KPP requires setting $\nu^0$ (\verb|KPP_nu_zero|, $\textrm{Ri}_0
 ! ($\verb|KPP_Ri_zero|), and $p_1$ (\verb|KPP_exp|),  and returns
 ! $$
 ! \nu_{KPP} = \left\{
 ! \begin{array}{r l}
 ! \nu^0 & \textrm{Ri} < 0\\
 ! \nu^0 \left[1 - \frac{\textrm{Ri}}{\textrm{Ri}_0}^2\right]^{p_1}
 !       & 0 < \textrm{Ri}
 !           < \textrm{Ri}_0 \\
 ! 0     & \textrm{Ri}_0 < \textrm{Ri}
 ! \end{array} \right.
 ! $$
 !
 ! !USES:
 !  Only those used by entire module.
 ! !INPUT PARAMETERS:
     character(len=*), optional, intent(in) :: mix_scheme,                     &
                                               old_vals
     real(cvmix_r8),   optional, intent(in) :: pp_nu_zero,                     &
                                               pp_alpha,                       &
                                               pp_exp,                         &
                                               pp_nu_b,                        &
                                               pp_kappa_b,                     &
                                               kpp_nu_zero,                    &
                                               kpp_ri_zero,                    &
                                               kpp_exp
 ! !OUTPUT PARAMETERS:
     type(cvmix_shear_params_type), optional, target, intent(inout) ::         &
                                               cvmix_shear_params_user
 !EOP
 !BOC
     type(cvmix_shear_params_type), pointer :: cvmix_shear_params_out
     if (present(cvmix_shear_params_user)) then
       cvmix_shear_params_out => cvmix_shear_params_user
     else
       cvmix_shear_params_out => cvmix_shear_params_saved
     end if
     if (present(mix_scheme)) then
       call cvmix_put_shear("mix_scheme", trim(mix_scheme),                    &
                            cvmix_shear_params_user)
     else
       call cvmix_put_shear("mix_scheme", "KPP", cvmix_shear_params_user)
     end if
     select case (trim(cvmix_shear_params_out%mix_scheme))
       case ('PP')
         if (present(pp_nu_zero)) then
           call cvmix_put_shear("PP_nu_zero", pp_nu_zero,                      &
                                cvmix_shear_params_user)
         else
           call cvmix_put_shear("PP_nu_zero", 0.01_cvmix_r8,                   &
                                cvmix_shear_params_user)
         end if
         if (present(pp_alpha)) then
           call cvmix_put_shear("PP_alpha", pp_alpha, cvmix_shear_params_user)
         else
           call cvmix_put_shear("PP_alpha", 5, cvmix_shear_params_user)
         end if
         if (present(pp_exp)) then
           call cvmix_put_shear("PP_exp", pp_exp, cvmix_shear_params_user)
         else
           call cvmix_put_shear("PP_exp", 2, cvmix_shear_params_user)
         end if
         if (present(pp_nu_b)) then
           call cvmix_put_shear("PP_nu_b", pp_nu_b, cvmix_shear_params_user)
         else
           call cvmix_put_shear("PP_nu_b", cvmix_zero, cvmix_shear_params_user)
         end if
         if (present(pp_kappa_b)) then
           call cvmix_put_shear("PP_kappa_b", pp_kappa_b, cvmix_shear_params_user)
         else
           call cvmix_put_shear("PP_kappa_b", cvmix_zero, cvmix_shear_params_user)
         end if
       case ('KPP')
         if (present(kpp_nu_zero)) then
           call cvmix_put_shear("KPP_nu_zero", kpp_nu_zero,                    &
                                cvmix_shear_params_user)
         else
           call cvmix_put_shear("KPP_nu_zero", 50e-4_cvmix_r8,                 &
                                cvmix_shear_params_user)
         end if
         if (present(kpp_ri_zero)) then
           call cvmix_put_shear("KPP_Ri_zero", kpp_ri_zero,                    &
                                cvmix_shear_params_user)
         else
           call cvmix_put_shear("KPP_Ri_zero", 0.7_cvmix_r8,                   &
                                cvmix_shear_params_user)
         end if
         if (present(kpp_exp)) then
           call cvmix_put_shear("KPP_exp", kpp_exp, cvmix_shear_params_user)
         else
           call cvmix_put_shear("KPP_exp", 3, cvmix_shear_params_user)
         end if
       case DEFAULT
         print*, "ERROR: ", trim(cvmix_shear_params_out%mix_scheme),           &
                 " is not a valid choice for shear mixing."
         stop 1
     end select
     if (present(old_vals)) then
       select case (trim(old_vals))
         case ("overwrite")
           call cvmix_put_shear('handle_old_vals', cvmix_overwrite_old_val,    &
                                cvmix_shear_params_user)
         case ("sum")
           call cvmix_put_shear('handle_old_vals', cvmix_sum_old_and_new_vals, &
                                cvmix_shear_params_user)
         case ("max")
           call cvmix_put_shear('handle_old_vals', cvmix_max_old_and_new_vals, &
                                cvmix_shear_params_user)
         case DEFAULT
           print*, "ERROR: ", trim(old_vals), " is not a valid option for ",   &
                   "handling old values of diff and visc."
           stop 1
       end select
     else
       call cvmix_put_shear('handle_old_vals', cvmix_overwrite_old_val,        &
                                cvmix_shear_params_user)
     end if
 !EOC
subroutine cvmix_shear::cvmix_put_shear_int (character(len=*), intent(in) varname, integer, intent(in) val, type(cvmix_shear_params_type), intent(inout), optional, target CVmix_shear_params_user) private
Definition at line 438 of file cvmix_shear.F90.
References cvmix_shear_params_saved.
 ! !DESCRIPTION:
 !  Write an integer value into a cvmix\_shear\_params\_type variable.
 !\\
 !\\
 ! !USES:
 !  Only those used by entire module.
 ! !INPUT PARAMETERS:
     character(len=*), intent(in) :: varname
     integer,          intent(in) :: val
 ! !OUTPUT PARAMETERS:
     type(cvmix_shear_params_type), optional, target, intent(inout) ::         &
                                               cvmix_shear_params_user
 !EOP
 !BOC
     type(cvmix_shear_params_type), pointer :: cvmix_shear_params_out
     if (present(cvmix_shear_params_user)) then
       cvmix_shear_params_out => cvmix_shear_params_user
     else
       cvmix_shear_params_out => cvmix_shear_params_saved
     end if
     select case(trim(varname))
       case ('old_vals', 'handle_old_vals')
         cvmix_shear_params_out%handle_old_vals = val
       case DEFAULT
       call cvmix_put_shear(varname, real(val,cvmix_r8),                       &
                            cvmix_shear_params_user)
     end select
 !EOC
subroutine cvmix_shear::cvmix_put_shear_real (character(len=*), intent(in) varname, real(cvmix_r8), intent(in) val, type(cvmix_shear_params_type), intent(inout), optional, target CVmix_shear_params_user) private
Definition at line 484 of file cvmix_shear.F90.
References cvmix_shear_params_saved.
 ! !DESCRIPTION:
 !  Write a real value into a cvmix\_shear\_params\_type variable.
 !\\
 !\\
 ! !USES:
 !  Only those used by entire module.
 ! !INPUT PARAMETERS:
     character(len=*), intent(in) :: varname
     real(cvmix_r8),   intent(in) :: val
 ! !OUTPUT PARAMETERS:
     type(cvmix_shear_params_type), optional, target, intent(inout) ::         &
                                               cvmix_shear_params_user
 !EOP
 !BOC
     type(cvmix_shear_params_type), pointer :: cvmix_shear_params_out
     if (present(cvmix_shear_params_user)) then
       cvmix_shear_params_out => cvmix_shear_params_user
     else
       cvmix_shear_params_out => cvmix_shear_params_saved
     end if
     select case (trim(varname))
       case ('PP_nu_zero')
         cvmix_shear_params_out%PP_nu_zero = val
       case ('PP_alpha')
         cvmix_shear_params_out%PP_alpha = val
       case ('PP_exp')
         cvmix_shear_params_out%PP_exp = val
       case ('PP_nu_b')
         cvmix_shear_params_out%PP_nu_b = val
       case ('PP_kappa_b')
         cvmix_shear_params_out%PP_kappa_b = val
       case ('KPP_nu_zero')
         cvmix_shear_params_out%KPP_nu_zero = val
       case ('KPP_Ri_zero')
         cvmix_shear_params_out%KPP_Ri_zero = val
       case ('KPP_exp')
         cvmix_shear_params_out%KPP_exp = val
       case DEFAULT
         print*, "ERROR: ", trim(varname), " not a valid choice!"
         stop 1
     end select
 !EOC
subroutine cvmix_shear::cvmix_put_shear_str (character(len=*), intent(in) varname, character(len=*), intent(in) val, type(cvmix_shear_params_type), intent(inout), optional, target CVmix_shear_params_user) private
Definition at line 545 of file cvmix_shear.F90.
References cvmix_shear_params_saved.
 ! !DESCRIPTION:
 !  Write a string into a cvmix\_shear\_params\_type variable.
 !\\
 !\\
 ! !USES:
 !  Only those used by entire module.
 ! !INPUT PARAMETERS:
     character(len=*), intent(in) :: varname
     character(len=*), intent(in) :: val
 ! !OUTPUT PARAMETERS:
     type(cvmix_shear_params_type), optional, target, intent(inout) ::         &
                                               cvmix_shear_params_user
 !EOP
 !BOC
     type(cvmix_shear_params_type), pointer :: cvmix_shear_params_out
     if (present(cvmix_shear_params_user)) then
       cvmix_shear_params_out => cvmix_shear_params_user
     else
       cvmix_shear_params_out => cvmix_shear_params_saved
     end if
     select case (trim(varname))
       case ('mix_scheme')
         cvmix_shear_params_out%mix_scheme = val
       case DEFAULT
         print*, "ERROR: ", trim(varname), " not a valid choice!"
         stop 1
     end select
 !EOC
Variable Documentation
type(cvmix_shear_params_type), target cvmix_shear::cvmix_shear_params_saved
Definition at line 109 of file cvmix_shear.F90.
Referenced by cvmix_coeffs_shear_low(), cvmix_coeffs_shear_wrap(), cvmix_get_shear_real(), cvmix_get_shear_str(), cvmix_init_shear(), cvmix_put_shear_int(), cvmix_put_shear_real(), and cvmix_put_shear_str().
   type(cvmix_shear_params_type), target :: cvmix_shear_params_saved