MOM6: mom_open_boundary Module Reference
mom_open_boundary Module Reference
Data Types
type open_boundary_cs
Functions/Subroutines
subroutine, public radiation_open_bdry_conds (OBC, u_new, u_old, v_new, v_old, h_new, h_old, G, CS)
subroutine, public open_boundary_init (Time, G, param_file, diag, CS)
subroutine, public open_boundary_end (CS)
Variables
integer id_clock_pass
Function/Subroutine Documentation
subroutine, public mom_open_boundary::open_boundary_end (type(open_boundary_cs), pointer CS)
Definition at line 261 of file MOM_open_boundary.F90.
   type(open_boundary_cs), pointer :: cs
   deallocate(cs)
subroutine, public mom_open_boundary::open_boundary_init (type(time_type), intent(in), target Time, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diag_ctrl), intent(inout), target diag, type(open_boundary_cs), pointer CS)
Definition at line 193 of file MOM_open_boundary.F90.
References id_clock_pass, mom_file_parser::log_version(), and mom_error_handler::mom_error().
   type(time_type), target, intent(in)    :: time
   type(ocean_grid_type),   intent(in)    :: g
   type(param_file_type),   intent(in)    :: param_file
   type(diag_ctrl), target, intent(inout) :: diag
   type(open_boundary_cs),  pointer       :: cs
 ! Arguments: Time - The current model time.
 !  (in)      G - The ocean's grid structure.
 !  (in)      param_file - A structure indicating the open file to parse for
 !                         model parameter values.
 !  (in)      diag - A structure that is used to regulate diagnostic output.
 !  (in/out)  CS - A pointer that is set to point to the control structure
 !                 for this module
 ! This include declares and sets the variable "version".
 #include "version_variable.h"
   character(len=40)  :: mod = "MOM_open_boundary" ! This module's name.
   logical :: flather_east, flather_west, flather_north, flather_south
   if (associated(cs)) then
     call mom_error(warning, "continuity_init called with associated control structure.")
     return
   endif
   call log_version(param_file, mod, version)
   call get_param(param_file, mod, "APPLY_OBC_U_FLATHER_EAST", flather_east, &
                  "If true, some zonal velocity points use Flather open \n"//&
                  "boundary conditions on the east side of the ocean.", &
                  default=.false.)
   call get_param(param_file, mod, "APPLY_OBC_U_FLATHER_WEST", flather_west, &
                  "If true, some zonal velocity points use Flather open \n"//&
                  "boundary conditions on the west side of the ocean.", &
                  default=.false.)
   call get_param(param_file, mod, "APPLY_OBC_V_FLATHER_NORTH", flather_north, &
                  "If true, some meridional velocity points use Flather \n"//&
                  "open boundary conditions on the north side of the ocean.", &
                  default=.false.)
   call get_param(param_file, mod, "APPLY_OBC_V_FLATHER_SOUTH", flather_south, &
                  "If true, some meridional velocity points use Flather \n"//&
                  "open boundary conditions on the north side of the ocean.", &
                  default=.false.)
   if (.not.(flather_east .or. flather_west .or. flather_north .or. &
             flather_south)) return
   allocate(cs)
   call get_param(param_file, mod, "OBC_RADIATION_MAX", cs%rx_max, &
                  "The maximum magnitude of the baroclinic radiation \n"//&
                  "velocity (or speed of characteristics).  This is only \n"//&
                  "used if one of the APPLY_OBC_[UV]_FLATHER_... is true.", &
                  units="m s-1", default=10.0)
   call get_param(param_file, mod, "OBC_RAD_VEL_WT", cs%gamma_uv, &
                  "The relative weighting for the baroclinic radiation \n"//&
                  "velocities (or speed of characteristics) at the new \n"//&
                  "time level (1) or the running mean (0) for velocities. \n"//&
                  "Valid values range from 0 to 1. This is only used if \n"//&
                  "one of the APPLY_OBC_[UV]_FLATHER_...  is true.", &
                  units="nondim",  default=0.3)
   call get_param(param_file, mod, "OBC_RAD_THICK_WT", cs%gamma_h, &
                  "The relative weighting for the baroclinic radiation \n"//&
                  "velocities (or speed of characteristics) at the new \n"//&
                  "time level (1) or the running mean (0) for thicknesses. \n"//&
                  "Valid values range from 0 to 1. This is only used if \n"//&
                  "one of the APPLY_OBC_[UV]_FLATHER_...  is true.", &
                  units="nondim",  default=0.2)
   id_clock_pass = cpu_clock_id('(Ocean OBC halo updates)', grain=clock_routine)
subroutine, public mom_open_boundary::radiation_open_bdry_conds (type(ocean_obc_type), pointer OBC, real, dimension(szib_(g),szj_(g),szk_(g)), intent(inout) u_new, real, dimension(szib_(g),szj_(g),szk_(g)), intent(in) u_old, real, dimension(szi_(g),szjb_(g),szk_(g)), intent(inout) v_new, real, dimension(szi_(g),szjb_(g),szk_(g)), intent(in) v_old, real, dimension(szi_(g),szj_(g),szk_(g)), intent(inout) h_new, real, dimension(szi_(g),szj_(g),szk_(g)), intent(in) h_old, type(ocean_grid_type), intent(inout) G, type(open_boundary_cs), pointer CS)
Definition at line 78 of file MOM_open_boundary.F90.
References id_clock_pass, mom_error_handler::mom_error(), mom_variables::obc_flather_e, mom_variables::obc_flather_n, mom_variables::obc_flather_s, and mom_variables::obc_flather_w.
   type(ocean_grid_type),                     intent(inout) :: g
   type(ocean_obc_type),                      pointer       :: obc
   real, dimension(SZIB_(G),SZJ_(G),SZK_(G)), intent(inout) :: u_new
   real, dimension(SZIB_(G),SZJ_(G),SZK_(G)), intent(in)    :: u_old
   real, dimension(SZI_(G),SZJB_(G),SZK_(G)), intent(inout) :: v_new
   real, dimension(SZI_(G),SZJB_(G),SZK_(G)), intent(in)    :: v_old
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)),  intent(inout) :: h_new
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)),  intent(in)    :: h_old
   type(open_boundary_cs),                    pointer       :: cs
   real :: dhdt, dhdx, gamma_u, gamma_h, gamma_v
   real :: rx_max, ry_max ! coefficients for radiation
   real :: rx_new, rx_avg ! coefficients for radiation
   integer :: i, j, k, is, ie, js, je, nz
   is = g%isc ; ie = g%iec ; js = g%jsc ; je = g%jec ; nz = g%ke
   if (.not.associated(obc)) return
   if (.not.(obc%apply_OBC_u_flather_east .or. obc%apply_OBC_u_flather_west .or. &
             obc%apply_OBC_v_flather_north .or. obc%apply_OBC_v_flather_south)) &
     return
   if (.not.associated(cs)) call mom_error(fatal, &
          "MOM_open_boundary: Module must be initialized before it is used.")
   gamma_u = cs%gamma_uv ; gamma_v = cs%gamma_uv ; gamma_h = cs%gamma_h
   rx_max = cs%rx_max ; ry_max = cs%rx_max
   if (obc%apply_OBC_u_flather_east .or. obc%apply_OBC_u_flather_west) then
     do k=1,nz ; do j=js,je ; do i=is-1,ie ; if (obc%OBC_mask_u(i,j)) then
       if (obc%OBC_kind_u(i,j) == obc_flather_e) then
         dhdt = u_old(i-1,j,k)-u_new(i-1,j,k) !old-new
         dhdx = u_new(i-1,j,k)-u_new(i-2,j,k) !in new time backward sasha for I-1
         rx_new = 0.0
         if (dhdt*dhdx > 0.0) rx_new = min( (dhdt/dhdx), rx_max)
         rx_avg = (1.0-gamma_u)*obc%rx_old_u(i,j,k) + gamma_u*rx_new
         obc%rx_old_u(i,j,k) = rx_avg
         u_new(i,j,k) = (u_old(i,j,k) + rx_avg*u_new(i-1,j,k)) / (1.0+rx_avg)
     !   dhdt = h_old(I,j,k)-h_new(I,j,k) !old-new
     !   dhdx = h_new(I,j,k)-h_new(I-1,j,k) !in new time
     !   rx_new = 0.0
     !   if (dhdt*dhdx > 0.0) rx_new = min( (dhdt/dhdx), rx_max)
     !   rx_avg = (1.0-gamma_h)*OBC%rx_old_h(I,j,k) + gamma_h*rx_new
     !   OBC%rx_old_h(I,j,k) = rx_avg
     !    h_new(I+1,j,k) = (h_old(I+1,j,k) + rx_avg*h_new(I,j,k)) / (1.0+rx_avg) !original
       endif
       if (obc%OBC_kind_u(i,j) == obc_flather_w) then
         dhdt = u_old(i+1,j,k)-u_new(i+1,j,k) !old-new
         dhdx = u_new(i+1,j,k)-u_new(i+2,j,k) !in new time backward sasha for I+1
         rx_new = 0.0
         if (dhdt*dhdx > 0.0) rx_new = min( (dhdt/dhdx), rx_max)
         rx_avg = (1.0-gamma_u)*obc%rx_old_u(i,j,k) + gamma_u*rx_new
         obc%rx_old_u(i,j,k) = rx_avg
         u_new(i,j,k) = (u_old(i,j,k) + rx_avg*u_new(i+1,j,k)) / (1.0+rx_avg)
     !   dhdt = h_old(I+1,j,k)-h_new(I+1,j,k) !old-new
     !   dhdx = h_new(I+1,j,k)-h_new(I+2,j,k) !in new time
     !   rx_new = 0.0
     !   if (dhdt*dhdx > 0.0) rx_new = min( (dhdt/dhdx), rx_max)
     !   rx_avg = (1.0-gamma_h)*OBC%rx_old_h(I,j,k) + gamma_h*rx_new
     !   OBC%rx_old_h(I,j,k) = rx_avg
     !   h_new(I,j,k) = (h_old(I,j,k) + rx_avg*h_new(I+1,j,k)) / (1.0+rx_avg) !original
       endif
     endif ; enddo ; enddo ; enddo
   endif
   if (obc%apply_OBC_v_flather_north .or. obc%apply_OBC_v_flather_south) then
     do k=1,nz ; do j=js-1,je ; do i=is,ie ; if (obc%OBC_mask_v(i,j)) then
       if (obc%OBC_kind_v(i,j) == obc_flather_n) then
         dhdt = v_old(i,j-1,k)-v_new(i,j-1,k) !old-new
         dhdx = v_new(i,j-1,k)-v_new(i,j-2,k) !in new time backward sasha for J-1
         rx_new = 0.0
         if (dhdt*dhdx > 0.0) rx_new = min( (dhdt/dhdx), rx_max)
         rx_avg = (1.0-gamma_v)*obc%ry_old_v(i,j,k) + gamma_v*rx_new
         obc%ry_old_v(i,j,k) = rx_avg
         v_new(i,j,k) = (v_old(i,j,k) + rx_avg*v_new(i,j-1,k)) / (1.0+rx_avg)
     !   dhdt = h_old(i,J,k)-h_new(i,J,k) !old-new
     !   dhdx = h_new(i,J,k)-h_new(i,J-1,k) !in new time
     !   rx_new = 0.0
     !   if (dhdt*dhdx > 0.0) rx_new = min( (dhdt/dhdx), rx_max)
     !   rx_avg = (1.0-gamma_h)*OBC%ry_old_h(i,J,k) + gamma_h*rx_new
     !   OBC%ry_old_h(i,J,k) = rx_avg
     !   h_new(i,J+1,k) = (h_old(i,J+1,k) + rx_avg*h_new(i,J,k)) / (1.0+rx_avg) !original
       endif
       if (obc%OBC_kind_v(i,j) == obc_flather_s) then
         dhdt = v_old(i,j+1,k)-v_new(i,j+1,k) !old-new
         dhdx = v_new(i,j+1,k)-v_new(i,j+2,k) !in new time backward sasha for J+1
         rx_new = 0.0
         if (dhdt*dhdx > 0.0) rx_new = min( (dhdt/dhdx), rx_max)
         rx_avg = (1.0-gamma_v)*obc%ry_old_v(i,j,k) + gamma_v*rx_new
         obc%ry_old_v(i,j,k) = rx_avg
         v_new(i,j,k) = (v_old(i,j,k) + rx_avg*v_new(i,j+1,k)) / (1.0+rx_avg)
     !   dhdt = h_old(i,J+1,k)-h_new(i,J+1,k) !old-new
     !   dhdx = h_new(i,J+1,k)-h_new(i,J+2,k) !in new time
     !   rx_new = 0.0
     !   if (dhdt*dhdx > 0.0) rx_new = min( (dhdt/dhdx), rx_max)
     !   rx_avg = (1.0-gamma_h)*OBC%ry_old_h(i,J,k) + gamma_h*rx_new
     !   OBC%ry_old_h(i,J,k) = rx_avg
     !   h_new(i,J,k) = (h_old(i,J,k) + rx_avg*h_new(i,J+1,k)) / (1.0+rx_avg) !original
       endif
     endif ; enddo ; enddo ; enddo
   endif
   call cpu_clock_begin(id_clock_pass)
   call pass_vector(u_new, v_new, g%Domain)
   call pass_var(h_new, g%Domain)
   call cpu_clock_end(id_clock_pass)
Variable Documentation
integer mom_open_boundary::id_clock_pass
Definition at line 72 of file MOM_open_boundary.F90.
Referenced by open_boundary_init(), and radiation_open_bdry_conds().
 integer :: id_clock_pass