MOM6: src/framework/MOM_checksums.F90 File Reference
MOM_checksums.F90 File Reference
#include "version_variable.h"
Data Types
interface mom_checksums::hchksum
interface mom_checksums::qchksum
interface mom_checksums::uchksum
interface mom_checksums::vchksum
interface mom_checksums::chksum
interface mom_checksums::chk_sum_msg
interface mom_checksums::is_nan
Modules
module mom_checksums
Functions/Subroutines
subroutine mom_checksums::chksum_h_2d_g (array, mesg, G, haloshift)
chksum_h_2d_G performs checksums on a 2d array staggered at tracer points.
subroutine mom_checksums::chksum_q_2d_g (array, mesg, G, haloshift)
chksum_q_2d_G performs checksums on a 2d array staggered at corner points.
subroutine mom_checksums::chksum_u_2d_g (array, mesg, G, haloshift)
chksum_u_2d_G performs checksums on a 2d array staggered at C-grid u points.
subroutine mom_checksums::chksum_v_2d_g (array, mesg, G, haloshift)
chksum_v_2d_G performs checksums on a 2d array staggered at C-grid v points.
subroutine mom_checksums::chksum_h_3d_g (array, mesg, G, haloshift)
chksum_h_3d performs checksums on a 3d array staggered at tracer points.
subroutine mom_checksums::chksum_q_3d_g (array, mesg, G, haloshift)
chksum_q_3d_G performs checksums on a 3d array staggered at corner points.
subroutine mom_checksums::chksum_u_3d_g (array, mesg, G, haloshift)
chksum_u_3d_G performs checksums on a 3d array staggered at C-grid u points.
subroutine mom_checksums::chksum_v_3d_g (array, mesg, G, haloshift)
chksum_v_3d_G performs checksums on a 3d array staggered at C-grid v points.
subroutine mom_checksums::chksum_h_2d (array, mesg, HI, haloshift)
chksum_h_2d performs checksums on a 2d array staggered at tracer points.
integer function subchk (array, HI, di, dj)
subroutine substats (HI, array, mesg)
subroutine mom_checksums::chksum_q_2d (array, mesg, HI, haloshift)
chksum_q_2d performs checksums on a 2d array staggered at corner points.
integer function subchk (array, HI, di, dj)
subroutine substats (HI, array, mesg)
subroutine mom_checksums::chksum_u_2d (array, mesg, HI, haloshift)
chksum_u_2d performs checksums on a 2d array staggered at C-grid u points.
integer function subchk (array, HI, di, dj)
subroutine substats (HI, array, mesg)
subroutine mom_checksums::chksum_v_2d (array, mesg, HI, haloshift)
chksum_v_2d performs checksums on a 2d array staggered at C-grid v points.
integer function subchk (array, HI, di, dj)
subroutine substats (HI, array, mesg)
subroutine mom_checksums::chksum_h_3d (array, mesg, HI, haloshift)
chksum_h_3d performs checksums on a 3d array staggered at tracer points.
integer function subchk (array, HI, di, dj)
subroutine substats (HI, array, mesg)
subroutine mom_checksums::chksum_q_3d (array, mesg, HI, haloshift)
chksum_q_3d performs checksums on a 3d array staggered at corner points.
integer function subchk (array, HI, di, dj)
subroutine substats (HI, array, mesg)
subroutine mom_checksums::chksum_u_3d (array, mesg, HI, haloshift)
chksum_u_3d performs checksums on a 3d array staggered at C-grid u points.
integer function subchk (array, HI, di, dj)
subroutine substats (HI, array, mesg)
subroutine mom_checksums::chksum_v_3d (array, mesg, HI, haloshift)
chksum_v_3d performs checksums on a 3d array staggered at C-grid v points.
integer function subchk (array, HI, di, dj)
subroutine substats (HI, array, mesg)
subroutine mom_checksums::chksum1d (array, mesg, start_i, end_i, compare_PEs)
chksum1d does a checksum of a 1-dimensional array.
subroutine mom_checksums::chksum2d (array, mesg, start_x, end_x, start_y, end_y)
subroutine mom_checksums::chksum3d (array, mesg, start_x, end_x, start_y, end_y, start_z, end_z)
logical function mom_checksums::is_nan_0d (x)
This function returns .true. if x is a NaN, and .false. otherwise.
logical function mom_checksums::is_nan_1d (x, skip_mpp)
This function returns .true. if any element of x is a NaN, and .false. otherwise.
logical function mom_checksums::is_nan_2d (x)
This function returns .true. if any element of x is a NaN, and .false. otherwise.
logical function mom_checksums::is_nan_3d (x)
This function returns .true. if any element of x is a NaN, and .false. otherwise.
real function, public mom_checksums::totalstuff (G, hThick, stuff)
This function returns the sum over computational domain of all processors of hThick*stuff, where stuff is a 3-d array at tracer points.
subroutine, public mom_checksums::totaltands (G, hThick, temperature, salinity, mesg)
This subroutine display the total thickness, temperature and salinity as well as the change since the last call. NOTE: This subroutine uses "save" data which is not thread safe and is purely for extreme debugging without a proper debugger.
subroutine mom_checksums::chk_sum_msg1 (fmsg, bc0, mesg)
subroutine mom_checksums::chk_sum_msg5 (fmsg, bc0, bcSW, bcSE, bcNW, bcNE, mesg)
subroutine mom_checksums::chk_sum_msg3 (fmsg, aMean, aMin, aMax, mesg)
subroutine, public mom_checksums::mom_checksums_init (param_file)
MOM_checksums_init initializes the MOM_checksums module. As it happens, the only thing that it does is to log the version of this module.
subroutine mom_checksums::chksum_error (signal, message)
Variables
integer, parameter mom_checksums::default_shift =0
logical mom_checksums::calculatestatistics =.false.
logical mom_checksums::checkfornans =.true.
Function/Subroutine Documentation
integer function chksum_h_2d::subchk (real, dimension(hi%isd:,hi%jsd:), intent(in) array, type(hor_index_type), intent(in) HI, integer, intent(in) di, integer, intent(in) dj) private
Definition at line 228 of file MOM_checksums.F90.
Referenced by mom_checksums::chksum_h_2d(), mom_checksums::chksum_h_3d(), mom_checksums::chksum_q_2d(), mom_checksums::chksum_q_3d(), mom_checksums::chksum_u_2d(), mom_checksums::chksum_u_3d(), mom_checksums::chksum_v_2d(), mom_checksums::chksum_v_3d(), and subchk().
     type(hor_index_type), intent(in) :: hi
     real, dimension(HI%isd:,HI%jsd:), intent(in) :: array
     integer, intent(in) :: di, dj
     integer :: bitcount, i, j, bc
     subchk = 0
     do j=hi%jsc+dj,hi%jec+dj; do i=hi%isc+di,hi%iec+di
         bc = bitcount(abs(array(i,j)))
         subchk = subchk + bc
     enddo; enddo
     call sum_across_pes(subchk)
     subchk=mod(subchk,1000000000)
integer function chksum_q_2d::subchk (real, dimension(hi%isdb:,hi%jsdb:), intent(in) array, type(hor_index_type), intent(in) HI, integer, intent(in) di, integer, intent(in) dj) private
Definition at line 320 of file MOM_checksums.F90.
References subchk().
     type(hor_index_type), intent(in) :: hi
     real, dimension(HI%IsdB:,HI%JsdB:), intent(in) :: array
     integer, intent(in) :: di, dj
     integer :: bitcount, i, j, bc
     subchk = 0
     do j=hi%jsc+dj,hi%jec+dj; do i=hi%isc+di,hi%iec+di
         bc = bitcount(abs(array(i,j)))
         subchk = subchk + bc
     enddo; enddo
     call sum_across_pes(subchk)
     subchk=mod(subchk,1000000000)
integer function chksum_u_2d::subchk (real, dimension(hi%isdb:,hi%jsd:), intent(in) array, type(hor_index_type), intent(in) HI, integer, intent(in) di, integer, intent(in) dj) private
Definition at line 412 of file MOM_checksums.F90.
References subchk().
     type(hor_index_type), intent(in) :: hi
     real, dimension(HI%IsdB:,HI%jsd:), intent(in) :: array
     integer, intent(in) :: di, dj
     integer :: bitcount, i, j, bc
     subchk = 0
     do j=hi%jsc+dj,hi%jec+dj; do i=hi%isc+di,hi%iec+di
         bc = bitcount(abs(array(i,j)))
         subchk = subchk + bc
     enddo; enddo
     call sum_across_pes(subchk)
     subchk=mod(subchk,1000000000)
integer function chksum_v_2d::subchk (real, dimension(hi%isd:,hi%jsdb:), intent(in) array, type(hor_index_type), intent(in) HI, integer, intent(in) di, integer, intent(in) dj) private
Definition at line 504 of file MOM_checksums.F90.
References subchk().
     type(hor_index_type), intent(in) :: hi
     real, dimension(HI%isd:,HI%JsdB:), intent(in) :: array
     integer, intent(in) :: di, dj
     integer :: bitcount, i, j, bc
     subchk = 0
     do j=hi%jsc+dj,hi%jec+dj; do i=hi%isc+di,hi%iec+di
         bc = bitcount(abs(array(i,j)))
         subchk = subchk + bc
     enddo; enddo
     call sum_across_pes(subchk)
     subchk=mod(subchk,1000000000)
integer function chksum_h_3d::subchk (real, dimension(hi%isd:,hi%jsd:,:), intent(in) array, type(hor_index_type), intent(in) HI, integer, intent(in) di, integer, intent(in) dj) private
Definition at line 596 of file MOM_checksums.F90.
References subchk().
     type(hor_index_type), intent(in) :: hi
     real, dimension(HI%isd:,HI%jsd:,:), intent(in) :: array
     integer, intent(in) :: di, dj
     integer :: bitcount, i, j, k, bc
     subchk = 0
     do k=lbound(array,3),ubound(array,3) ; do j=hi%jsc+dj,hi%jec+dj ; do i=hi%isc+di,hi%iec+di
       bc = bitcount(abs(array(i,j,k)))
       subchk = subchk + bc
     enddo ; enddo ; enddo
     call sum_across_pes(subchk)
     subchk=mod(subchk,1000000000)
integer function chksum_q_3d::subchk (real, dimension(hi%isdb:,hi%jsdb:,:), intent(in) array, type(hor_index_type), intent(in) HI, integer, intent(in) di, integer, intent(in) dj) private
Definition at line 688 of file MOM_checksums.F90.
References subchk().
     type(hor_index_type), intent(in) :: hi
     real, dimension(HI%IsdB:,HI%JsdB:,:), intent(in) :: array
     integer, intent(in) :: di, dj
     integer :: bitcount, i, j, k, bc
     subchk = 0
     do k=lbound(array,3),ubound(array,3) ; do j=hi%jsc+dj,hi%jec+dj ; do i=hi%isc+di,hi%iec+di
       bc = bitcount(abs(array(i,j,k)))
       subchk = subchk + bc
     enddo ; enddo ; enddo
     call sum_across_pes(subchk)
     subchk=mod(subchk,1000000000)
integer function chksum_u_3d::subchk (real, dimension(hi%isdb:,hi%jsd:,:), intent(in) array, type(hor_index_type), intent(in) HI, integer, intent(in) di, integer, intent(in) dj) private
Definition at line 780 of file MOM_checksums.F90.
References subchk().
     type(hor_index_type), intent(in) :: hi
     real, dimension(HI%IsdB:,HI%jsd:,:), intent(in) :: array
     integer, intent(in) :: di, dj
     integer :: bitcount, i, j, k, bc
     subchk = 0
     do k=lbound(array,3),ubound(array,3) ; do j=hi%jsc+dj,hi%jec+dj ; do i=hi%isc+di,hi%iec+di
       bc = bitcount(abs(array(i,j,k)))
       subchk = subchk + bc
     enddo ; enddo ; enddo
     call sum_across_pes(subchk)
     subchk=mod(subchk,1000000000)
integer function chksum_v_3d::subchk (real, dimension(hi%isd:,hi%jsdb:,:), intent(in) array, type(hor_index_type), intent(in) HI, integer, intent(in) di, integer, intent(in) dj) private
Definition at line 872 of file MOM_checksums.F90.
References subchk().
     type(hor_index_type), intent(in) :: hi
     real, dimension(HI%isd:,HI%JsdB:,:), intent(in) :: array
     integer, intent(in) :: di, dj
     integer :: bitcount, i, j, k, bc
     subchk = 0
     do k=lbound(array,3),ubound(array,3) ; do j=hi%jsc+dj,hi%jec+dj ; do i=hi%isc+di,hi%iec+di
       bc = bitcount(abs(array(i,j,k)))
       subchk = subchk + bc
     enddo ; enddo ; enddo
     call sum_across_pes(subchk)
     subchk=mod(subchk,1000000000)
subroutine chksum_h_2d::substats (type(hor_index_type), intent(in) HI, real, dimension(hi%isd:,hi%jsd:), intent(in) array, character(len=*), intent(in) mesg) private
Definition at line 242 of file MOM_checksums.F90.
References mom_error_handler::is_root_pe().
Referenced by mom_checksums::chksum_h_2d(), mom_checksums::chksum_h_3d(), mom_checksums::chksum_q_2d(), mom_checksums::chksum_q_3d(), mom_checksums::chksum_u_2d(), mom_checksums::chksum_u_3d(), mom_checksums::chksum_v_2d(), and mom_checksums::chksum_v_3d().
     type(hor_index_type), intent(in) :: hi
     real, dimension(HI%isd:,HI%jsd:), intent(in) :: array
     character(len=*), intent(in) :: mesg
     integer :: i, j, n
     real :: amean, amin, amax
     amean = 0.
     amin = array(hi%isc,hi%jsc)
     amax = array(hi%isc,hi%jsc)
     n = 0
     do j=hi%jsc,hi%jec; do i=hi%isc,hi%iec
         amean = amean + array(i,j)
         amin = min(amin, array(i,j))
         amax = max(amax, array(i,j))
         n = n + 1
     enddo; enddo
     call sum_across_pes(amean)
     call sum_across_pes(n)
     call min_across_pes(amin)
     call max_across_pes(amax)
     amean = amean / real(n)
     if (is_root_pe()) call chk_sum_msg("h-point:",amean,amin,amax,mesg)
subroutine chksum_q_2d::substats (type(hor_index_type), intent(in) HI, real, dimension(hi%isdb:,hi%jsdb:), intent(in) array, character(len=*), intent(in) mesg) private
Definition at line 334 of file MOM_checksums.F90.
     type(hor_index_type), intent(in) :: hi
     real, dimension(HI%IsdB:,HI%JsdB:), intent(in) :: array
     character(len=*), intent(in) :: mesg
     integer :: i, j, n
     real :: amean, amin, amax
     amean = 0.
     amin = array(hi%isc,hi%jsc)
     amax = array(hi%isc,hi%jsc)
     n = 0
     do j=hi%jsc,hi%jec; do i=hi%isc,hi%iec
         amean = amean + array(i,j)
         amin = min(amin, array(i,j))
         amax = max(amax, array(i,j))
         n = n + 1
     enddo; enddo
     call sum_across_pes(amean)
     call sum_across_pes(n)
     call min_across_pes(amin)
     call max_across_pes(amax)
     amean = amean / real(n)
     if (is_root_pe()) call chk_sum_msg("q-point:",amean,amin,amax,mesg)
subroutine chksum_u_2d::substats (type(hor_index_type), intent(in) HI, real, dimension(hi%isdb:,hi%jsd:), intent(in) array, character(len=*), intent(in) mesg) private
Definition at line 426 of file MOM_checksums.F90.
     type(hor_index_type), intent(in) :: hi
     real, dimension(HI%IsdB:,HI%jsd:), intent(in) :: array
     character(len=*), intent(in) :: mesg
     integer :: i, j, n
     real :: amean, amin, amax
     amean = 0.
     amin = array(hi%isc,hi%jsc)
     amax = array(hi%isc,hi%jsc)
     n = 0
     do j=hi%jsc,hi%jec; do i=hi%isc,hi%iec
         amean = amean + array(i,j)
         amin = min(amin, array(i,j))
         amax = max(amax, array(i,j))
         n = n + 1
     enddo; enddo
     call sum_across_pes(amean)
     call sum_across_pes(n)
     call min_across_pes(amin)
     call max_across_pes(amax)
     amean = amean / real(n)
     if (is_root_pe()) call chk_sum_msg("u-point:",amean,amin,amax,mesg)
subroutine chksum_v_2d::substats (type(hor_index_type), intent(in) HI, real, dimension(hi%isd:,hi%jsdb:), intent(in) array, character(len=*), intent(in) mesg) private
Definition at line 518 of file MOM_checksums.F90.
     type(hor_index_type), intent(in) :: hi
     real, dimension(HI%isd:,HI%JsdB:), intent(in) :: array
     character(len=*), intent(in) :: mesg
     integer :: i, j, n
     real :: amean, amin, amax
     amean = 0.
     amin = array(hi%isc,hi%jsc)
     amax = array(hi%isc,hi%jsc)
     n = 0
     do j=hi%jsc,hi%jec; do i=hi%isc,hi%iec
         amean = amean + array(i,j)
         amin = min(amin, array(i,j))
         amax = max(amax, array(i,j))
         n = n + 1
     enddo; enddo
     call sum_across_pes(amean)
     call sum_across_pes(n)
     call min_across_pes(amin)
     call max_across_pes(amax)
     amean = amean / real(n)
     if (is_root_pe()) call chk_sum_msg("v-point:",amean,amin,amax,mesg)
subroutine chksum_h_3d::substats (type(hor_index_type), intent(in) HI, real, dimension(hi%isd:,hi%jsd:,:), intent(in) array, character(len=*), intent(in) mesg) private
Definition at line 610 of file MOM_checksums.F90.
     type(hor_index_type), intent(in) :: hi
     real, dimension(HI%isd:,HI%jsd:,:), intent(in) :: array
     character(len=*), intent(in) :: mesg
     integer :: i, j, k, n
     real :: amean, amin, amax
     amean = 0.
     amin = array(hi%isc,hi%jsc,1)
     amax = array(hi%isc,hi%jsc,1)
     n = 0
     do k=lbound(array,3),ubound(array,3) ; do j=hi%jsc,hi%jec ; do i=hi%isc,hi%iec
       amean = amean + array(i,j,k)
       amin = min(amin, array(i,j,k))
       amax = max(amax, array(i,j,k))
       n = n + 1
     enddo ; enddo ; enddo
     call sum_across_pes(amean)
     call sum_across_pes(n)
     call min_across_pes(amin)
     call max_across_pes(amax)
     amean = amean / real(n)
     if (is_root_pe()) call chk_sum_msg("h-point:",amean,amin,amax,mesg)
subroutine chksum_q_3d::substats (type(hor_index_type), intent(in) HI, real, dimension(hi%isdb:,hi%jsdb:,:), intent(in) array, character(len=*), intent(in) mesg) private
Definition at line 702 of file MOM_checksums.F90.
     type(hor_index_type), intent(in) :: hi
     real, dimension(HI%IsdB:,HI%JsdB:,:), intent(in) :: array
     character(len=*), intent(in) :: mesg
     integer :: i, j, k, n
     real :: amean, amin, amax
     amean = 0.
     amin = array(hi%isc,hi%jsc,1)
     amax = array(hi%isc,hi%jsc,1)
     n = 0
     do k=lbound(array,3),ubound(array,3) ; do j=hi%jsc,hi%jec ; do i=hi%isc,hi%iec
       amean = amean + array(i,j,k)
       amin = min(amin, array(i,j,k))
       amax = max(amax, array(i,j,k))
       n = n + 1
     enddo ; enddo ; enddo
     call sum_across_pes(amean)
     call sum_across_pes(n)
     call min_across_pes(amin)
     call max_across_pes(amax)
     amean = amean / real(n)
     if (is_root_pe()) call chk_sum_msg("q-point:",amean,amin,amax,mesg)
subroutine chksum_u_3d::substats (type(hor_index_type), intent(in) HI, real, dimension(hi%isdb:,hi%jsd:,:), intent(in) array, character(len=*), intent(in) mesg) private
Definition at line 794 of file MOM_checksums.F90.
     type(hor_index_type), intent(in) :: hi
     real, dimension(HI%IsdB:,HI%jsd:,:), intent(in) :: array
     character(len=*), intent(in) :: mesg
     integer :: i, j, k, n
     real :: amean, amin, amax
     amean = 0.
     amin = array(hi%isc,hi%jsc,1)
     amax = array(hi%isc,hi%jsc,1)
     n = 0
     do k=lbound(array,3),ubound(array,3) ; do j=hi%jsc,hi%jec ; do i=hi%isc,hi%iec
       amean = amean + array(i,j,k)
       amin = min(amin, array(i,j,k))
       amax = max(amax, array(i,j,k))
       n = n + 1
     enddo ; enddo ; enddo
     call sum_across_pes(amean)
     call sum_across_pes(n)
     call min_across_pes(amin)
     call max_across_pes(amax)
     amean = amean / real(n)
     if (is_root_pe()) call chk_sum_msg("u-point:",amean,amin,amax,mesg)
subroutine chksum_v_3d::substats (type(hor_index_type), intent(in) HI, real, dimension(hi%isd:,hi%jsdb:,:), intent(in) array, character(len=*), intent(in) mesg) private
Definition at line 886 of file MOM_checksums.F90.
     type(hor_index_type), intent(in) :: hi
     real, dimension(HI%isd:,HI%JsdB:,:), intent(in) :: array
     character(len=*), intent(in) :: mesg
     integer :: i, j, k, n
     real :: amean, amin, amax
     amean = 0.
     amin = array(hi%isc,hi%jsc,1)
     amax = array(hi%isc,hi%jsc,1)
     n = 0
     do k=lbound(array,3),ubound(array,3) ; do j=hi%jsc,hi%jec ; do i=hi%isc,hi%iec
       amean = amean + array(i,j,k)
       amin = min(amin, array(i,j,k))
       amax = max(amax, array(i,j,k))
       n = n + 1
     enddo ; enddo ; enddo
     call sum_across_pes(amean)
     call sum_across_pes(n)
     call min_across_pes(amin)
     call max_across_pes(amax)
     amean = amean / real(n)
     if (is_root_pe()) call chk_sum_msg("v-point:",amean,amin,amax,mesg)