MOM6: mom_error_checking Module Reference
mom_error_checking Module Reference
Data Types
interface check_redundant
Functions/Subroutines
subroutine check_redundant_v3d (mesg, u_comp, v_comp, G, is, ie, js, je, direction, stagger)
subroutine check_redundant_v2d (mesg, u_comp, v_comp, G, is, ie, js, je, direction, stagger)
subroutine check_redundant_s3d (mesg, array, G, is, ie, js, je, stagger)
subroutine check_redundant_s2d (mesg, array, G, is, ie, js, je, stagger)
Function/Subroutine Documentation
subroutine mom_error_checking::check_redundant_s2d (character(len=*), intent(in) mesg, real, dimension(szib_(g),szjb_(g)), intent(in) array, type(ocean_grid_type), intent(inout) G, integer, intent(in), optional is, integer, intent(in), optional ie, integer, intent(in), optional js, integer, intent(in), optional je, integer, intent(in), optional stagger) private
Definition at line 186 of file MOM_error_checking.F90.
References mom_domains::do_group_pass(), and mom_error_handler::mom_error().
Referenced by check_redundant_s3d().
   character(len=*),                intent(in)    :: mesg
   type(ocean_grid_type),           intent(inout) :: g
   real, dimension(SZIB_(G),SZJB_(G)), intent(in) :: array
   integer,               optional, intent(in)    :: is, ie, js, je
   integer,               optional, intent(in)    :: stagger
 ! Arguments: u_comp - The u-component of the vector being checked.
 !  (in)      v_comp - The v-component of the vector being checked.
 !  (in)      mesg - A message indicating what is being checked.
 !  (in)      G - The ocean's grid structure.
 !  (in/opt)  is, ie, js, je - the i- and j- range of indices to check.
 !  (in/opt)  stagger - the stagger flag to be passed to pass_vector.
   real :: a_nonsym(szi_(g),szj_(g))
   real :: a_resym(szib_(g),szjb_(g))
   character(len=128) :: mesg2
   type(group_pass_type), save :: pass_a_nonsym, pass_a_resym !For group halo pass
   integer :: i, j, is_ch, ie_ch, js_ch, je_ch
   integer :: isq, ieq, jsq, jeq, isd, ied, jsd, jed, isdb, iedb, jsdb, jedb
   isq = g%IscB ; ieq = g%IecB ; jsq = g%JscB ; jeq = g%JecB
   isd = g%isd ; ied = g%ied ; jsd = g%jsd ; jed = g%jed
   isdb = g%IsdB ; iedb = g%IedB ; jsdb = g%JsdB ; jedb = g%JedB
   if ((isd == isdb) .and. (jsd == jsdb)) return
   do i=isd,ied ; do j=jsd,jed
     a_nonsym(i,j) = array(i,j)
   enddo ; enddo
   if (.not.associated(g%Domain_aux)) call mom_error(fatal," check_redundant"//&
     " called with a non-associated auxiliary domain the grid type.")
   call create_group_pass(pass_a_nonsym, a_nonsym, a_nonsym, g%Domain_aux, &
                          direction=to_all+scalar_pair, stagger=bgrid_ne)
   call create_group_pass(pass_a_resym, a_resym, a_resym, g%Domain,     &
                          direction=to_all+scalar_pair, stagger=bgrid_ne)
   call do_group_pass(pass_a_nonsym, g%Domain_aux)
   do i=isdb,iedb ; do j=jsdb,jedb ; a_resym(i,j) = array(i,j) ; enddo ; enddo
   do i=isd,ied ; do j=jsd,jed
     a_resym(i,j) = a_nonsym(i,j)
   enddo ; enddo
   call do_group_pass(pass_a_resym, g%Domain)
   is_ch = isq ; ie_ch = ieq ; js_ch = jsq ; je_ch = jeq
   if (present(is)) is_ch = is ; if (present(ie)) ie_ch = ie
   if (present(js)) js_ch = js ; if (present(js)) je_ch = je
   do i=is_ch,ie_ch ; do j=js_ch,je_ch
     if (a_resym(i,j) /= array(i,j)) then
       write(mesg2,'(" Redundant points",2(1pe12.4)," differ by ", &
                     & 1pe12.4," at i,j = ",2i4," on pe ",i4)') &
            array(i,j), a_resym(i,j),array(i,j)-a_resym(i,j),i,j,pe_here()
       write(*,'(A130)') trim(mesg)//trim(mesg2)
     endif
   enddo ; enddo
subroutine mom_error_checking::check_redundant_s3d (character(len=*), intent(in) mesg, real, dimension(szib_(g),szjb_(g),szk_(g)), intent(in) array, type(ocean_grid_type), intent(inout) G, integer, intent(in), optional is, integer, intent(in), optional ie, integer, intent(in), optional js, integer, intent(in), optional je, integer, intent(in), optional stagger) private
Definition at line 158 of file MOM_error_checking.F90.
References check_redundant_s2d().
   character(len=*),                     intent(in)    :: mesg
   type(ocean_grid_type),                intent(inout) :: g
   real, dimension(SZIB_(G),SZJB_(G),SZK_(G)), intent(in) :: array
   integer,                    optional, intent(in)    :: is, ie, js, je
   integer,                    optional, intent(in)    :: stagger
 ! Arguments: u_comp - The u-component of the vector being checked.
 !  (in)      v_comp - The v-component of the vector being checked.
 !  (in)      mesg - A message indicating what is being checked.
 !  (in)      G - The ocean's grid structure.
 !  (in/opt)  is, ie, js, je - the i- and j- range of indices to check.
 !  (in/opt)  stagger - the stagger flag to be passed to pass_vector.
   character(len=24) :: mesg_k
   integer :: k
   do k=1,g%ke
     if (k < 10) then ; write(mesg_k,'(" Layer",i2," ")') k
     elseif (k < 100) then ; write(mesg_k,'(" Layer",i3," ")') k
     elseif (k < 1000) then ; write(mesg_k,'(" Layer",i4," ")') k
     else ; write(mesg_k,'(" Layer",i9," ")') k ; endif
     call check_redundant_s2d(trim(mesg)//trim(mesg_k), array(:,:,k), &
                              g, is, ie, js, je, stagger)
   enddo
subroutine mom_error_checking::check_redundant_v2d (character(len=*), intent(in) mesg, real, dimension(szib_(g),szj_(g)), intent(in) u_comp, real, dimension(szi_(g),szjb_(g)), intent(in) v_comp, type(ocean_grid_type), intent(inout) G, integer, intent(in), optional is, integer, intent(in), optional ie, integer, intent(in), optional js, integer, intent(in), optional je, integer, intent(in), optional direction, integer, intent(in), optional stagger) private
Definition at line 83 of file MOM_error_checking.F90.
References mom_domains::do_group_pass(), and mom_error_handler::mom_error().
Referenced by check_redundant_v3d().
   type(ocean_grid_type),           intent(inout) :: g
   character(len=*),                intent(in)    :: mesg
   real, dimension(SZIB_(G),SZJ_(G)), intent(in)  :: u_comp
   real, dimension(SZI_(G),SZJB_(G)), intent(in)  :: v_comp
   integer,               optional, intent(in)    :: is, ie, js, je
   integer,               optional, intent(in)    :: direction
   integer,               optional, intent(in)    :: stagger
 ! Arguments: u_comp - The u-component of the vector being checked.
 !  (in)      v_comp - The v-component of the vector being checked.
 !  (in)      mesg - A message indicating what is being checked.
 !  (in)      G - The ocean's grid structure.
 !  (in/opt)  is, ie, js, je - the i- and j- range of indices to check.
 !  (in/opt)  direction - the direction flag to be passed to pass_vector.
 !  (in/opt)  stagger - the stagger flag to be passed to pass_vector.
   real :: u_nonsym(szi_(g),szj_(g))
   real :: v_nonsym(szi_(g),szj_(g))
   real :: u_resym(szib_(g),szj_(g))
   real :: v_resym(szi_(g),szjb_(g))
   character(len=128) :: mesg2
   type(group_pass_type), save :: pass_nonsym_uv, pass_resym_uv !For group halo pass
   integer :: i, j, is_ch, ie_ch, js_ch, je_ch
   integer :: isq, ieq, jsq, jeq, isd, ied, jsd, jed, isdb, iedb, jsdb, jedb
   isq = g%IscB ; ieq = g%IecB ; jsq = g%JscB ; jeq = g%JecB
   isd = g%isd ; ied = g%ied ; jsd = g%jsd ; jed = g%jed
   isdb = g%IsdB ; iedb = g%IedB ; jsdb = g%JsdB ; jedb = g%JedB
   if ((isd == isdb) .and. (jsd == jsdb)) return
   do i=isd,ied ; do j=jsd,jed
     u_nonsym(i,j) = u_comp(i,j) ; v_nonsym(i,j) = v_comp(i,j)
   enddo ; enddo
   if (.not.associated(g%Domain_aux)) call mom_error(fatal," check_redundant"//&
     " called with a non-associated auxiliary domain the grid type.")
   call create_group_pass(pass_nonsym_uv, u_nonsym, v_nonsym, g%Domain_aux, &
                          direction, stagger)
   call create_group_pass(pass_resym_uv, u_resym, v_resym, g%Domain,  &
                          direction, stagger)
   call do_group_pass(pass_nonsym_uv, g%Domain_aux)
   do i=isdb,iedb ; do j=jsd,jed ; u_resym(i,j) = u_comp(i,j) ; enddo ; enddo
   do i=isd,ied ; do j=jsdb,jedb ; v_resym(i,j) = v_comp(i,j) ; enddo ; enddo
   do i=isd,ied ; do j=jsd,jed
     u_resym(i,j) = u_nonsym(i,j) ; v_resym(i,j) = v_nonsym(i,j)
   enddo ; enddo
   call do_group_pass(pass_resym_uv, g%Domain)
   is_ch = isq ; ie_ch = ieq ; js_ch = jsq ; je_ch = jeq
   if (present(is)) is_ch = is ; if (present(ie)) ie_ch = ie
   if (present(js)) js_ch = js ; if (present(js)) je_ch = je
   do i=is_ch,ie_ch ; do j=js_ch+1,je_ch
     if (u_resym(i,j) /= u_comp(i,j)) then
       write(mesg2,'(" redundant u-components",2(1pe12.4)," differ by ", &
                     & 1pe12.4," at i,j = ",2i4," on pe ",i4)') &
            u_comp(i,j), u_resym(i,j),u_comp(i,j)-u_resym(i,j),i,j,pe_here()
       write(*,'(A130)') trim(mesg)//trim(mesg2)
     endif
   enddo ; enddo
   do i=is_ch+1,ie_ch ; do j=js_ch,je_ch
     if (v_resym(i,j) /= v_comp(i,j)) then
       write(mesg2,'(" redundant v-comps",2(1pe12.4)," differ by ", &
                     & 1pe12.4," at i,j = ",2i4," x,y = ",2(1pe12.4)" on pe ",i4)') &
            v_comp(i,j), v_resym(i,j),v_comp(i,j)-v_resym(i,j),i,j, &
            g%geoLonBu(i,j), g%geoLatBu(i,j), pe_here()
       write(*,'(A155)') trim(mesg)//trim(mesg2)
     endif
   enddo ; enddo
subroutine mom_error_checking::check_redundant_v3d (character(len=*), intent(in) mesg, real, dimension(szib_(g),szj_(g),szk_(g)), intent(in) u_comp, real, dimension(szi_(g),szjb_(g),szk_(g)), intent(in) v_comp, type(ocean_grid_type), intent(inout) G, integer, intent(in), optional is, integer, intent(in), optional ie, integer, intent(in), optional js, integer, intent(in), optional je, integer, intent(in), optional direction, integer, intent(in), optional stagger) private
Definition at line 52 of file MOM_error_checking.F90.
References check_redundant_v2d().
   type(ocean_grid_type),               intent(inout) :: g
   character(len=*),                    intent(in)    :: mesg
   real, dimension(SZIB_(G),SZJ_(G),SZK_(G)), intent(in) :: u_comp
   real, dimension(SZI_(G),SZJB_(G),SZK_(G)), intent(in) :: v_comp
   integer,                   optional, intent(in)    :: is, ie, js, je
   integer,                   optional, intent(in)    :: direction
   integer,                   optional, intent(in)    :: stagger
 ! Arguments: u_comp - The u-component of the vector being checked.
 !  (in)      v_comp - The v-component of the vector being checked.
 !  (in)      mesg - A message indicating what is being checked.
 !  (in)      G - The ocean's grid structure.
 !  (in/opt)  is, ie, js, je - the i- and j- range of indices to check.
 !  (in/opt)  direction - the direction flag to be passed to pass_vector.
 !  (in/opt)  stagger - the stagger flag to be passed to pass_vector.
   character(len=24) :: mesg_k
   integer :: k
   do k=1,g%ke
     if (k < 10) then ; write(mesg_k,'(" Layer",i2," ")') k
     elseif (k < 100) then ; write(mesg_k,'(" Layer",i3," ")') k
     elseif (k < 1000) then ; write(mesg_k,'(" Layer",i4," ")') k
     else ; write(mesg_k,'(" Layer",i9," ")') k ; endif
     call check_redundant_v2d(trim(mesg)//trim(mesg_k), u_comp(:,:,k), &
              v_comp(:,:,k), g, is, ie, js, je, direction, stagger)
   enddo