MOM6: cvmix_convection Module Reference
cvmix_convection Module Reference
Data Types
interface cvmix_coeffs_conv
type cvmix_conv_params_type
interface cvmix_put_conv
Functions/Subroutines
subroutine, public cvmix_init_conv (convect_diff, convect_visc, lBruntVaisala, BVsqr_convect, old_vals, CVmix_conv_params_user)
subroutine cvmix_coeffs_conv_wrap (CVmix_vars, CVmix_conv_params_user)
subroutine cvmix_coeffs_conv_low (Mdiff_out, Tdiff_out, Nsqr, dens, dens_lwr, nlev, max_nlev, CVmix_conv_params_user)
subroutine cvmix_put_conv_int (varname, val, CVmix_conv_params_user)
subroutine cvmix_put_conv_real (varname, val, CVmix_conv_params_user)
subroutine cvmix_put_conv_logical (varname, val, CVmix_conv_params_user)
real(cvmix_r8) function, public cvmix_get_conv_real (varname, CVmix_conv_params_user)
Variables
type(cvmix_conv_params_type), target cvmix_conv_params_saved
Function/Subroutine Documentation
subroutine cvmix_convection::cvmix_coeffs_conv_low (real(cvmix_r8), dimension(max_nlev+1), intent(inout) Mdiff_out, real(cvmix_r8), dimension(max_nlev+1), intent(inout) Tdiff_out, real(cvmix_r8), dimension(max_nlev+1), intent(in) Nsqr, real(cvmix_r8), dimension(max_nlev), intent(in) dens, real(cvmix_r8), dimension(max_nlev), intent(in) dens_lwr, integer, intent(in) nlev, integer, intent(in) max_nlev, type (cvmix_conv_params_type), intent(in), optional, target CVmix_conv_params_user) private
Definition at line 233 of file cvmix_convection.F90.
References cvmix_conv_params_saved, cvmix_get_conv_real(), cvmix_kinds_and_types::cvmix_one, and cvmix_kinds_and_types::cvmix_zero.
 ! !DESCRIPTION:
 !  Computes vertical diffusion coefficients for convective mixing.
 !\\
 !\\
 ! !USES:
 !  Only those used by entire module.
 ! !INPUT PARAMETERS:
     integer,                               intent(in) :: nlev, max_nlev
     ! max_nlev+1
     real(cvmix_r8), dimension(max_nlev+1), intent(in) :: nsqr
     ! max_nlev
     real(cvmix_r8), dimension(max_nlev),   intent(in) :: dens, dens_lwr
     type(cvmix_conv_params_type), optional, target, intent(in)  ::           &
                                              cvmix_conv_params_user
 ! !INPUT/OUTPUT PARAMETERS:
     ! nlev+1
     real(cvmix_r8), dimension(max_nlev+1), intent(inout) :: mdiff_out,        &
                                                             tdiff_out
 !EOP
 !BOC
 !-----------------------------------------------------------------------
 !
 !  local variables
 !
 !-----------------------------------------------------------------------
     real(cvmix_r8) :: vvconv, wgt
     integer        :: kw
     type(cvmix_conv_params_type), pointer :: cvmix_conv_params_in
     if (present(cvmix_conv_params_user)) then
       cvmix_conv_params_in => cvmix_conv_params_user
     else
       cvmix_conv_params_in => cvmix_conv_params_saved
     end if
 !-----------------------------------------------------------------------
 !
 !  enhance the vertical mixing coefficients if gravitationally unstable
 !
 !-----------------------------------------------------------------------
     if (cvmix_conv_params_in%lBruntVaisala) then
       ! Brunt-Vaisala mixing based on buoyancy
       ! Based on parameter BVsqr_convect
       ! diffusivity = convect_diff * wgt
       ! viscosity   = convect_visc * wgt
       ! For BVsqr_convect < 0:
       ! wgt = 0 for N^2 > 0
       ! wgt = 1 for N^2 < BVsqr_convect
       ! wgt = [1 - (1-N^2/BVsqr_convect)^2]^3 otherwise
       ! If BVsqr_convect >= 0:
       ! wgt = 0 for N^2 > 0
       ! wgt = 1 for N^2 <= 0
       ! Compute wgt
       if (cvmix_conv_params_in%BVsqr_convect.lt.0) then
         do kw=1, nlev
           wgt = cvmix_zero
           if (nsqr(kw).le.0) then
             if (nsqr(kw).gt.cvmix_conv_params_in%BVsqr_convect) then
               wgt = cvmix_one - nsqr(kw) / cvmix_conv_params_in%BVsqr_convect
               wgt = (cvmix_one - wgt**2)**3
             else
               wgt = cvmix_one
             end if
           end if
           mdiff_out(kw) = wgt*cvmix_get_conv_real('convect_visc',             &
                                                   cvmix_conv_params_in)
           tdiff_out(kw) = wgt*cvmix_get_conv_real('convect_diff',             &
                                                   cvmix_conv_params_in)
         end do
       else ! BVsqr_convect >= 0 => step function
         do kw=1,nlev-1
           if (nsqr(kw).le.0) then
             mdiff_out(kw) = cvmix_get_conv_real('convect_visc',               &
                                                 cvmix_conv_params_in)
             tdiff_out(kw) = cvmix_get_conv_real('convect_diff',               &
                                                 cvmix_conv_params_in)
           else
             mdiff_out(kw) = cvmix_zero
             tdiff_out(kw) = cvmix_zero
           end if
         end do
         mdiff_out(nlev) = cvmix_zero
         tdiff_out(nlev) = cvmix_zero
       end if
       mdiff_out(nlev+1) = cvmix_zero
       tdiff_out(nlev+1) = cvmix_zero
     else
       ! Default convection mixing based on density
       do kw=1,nlev-1
         if (cvmix_conv_params_in%convect_visc.ne.cvmix_zero) then
            vvconv = cvmix_get_conv_real('convect_visc', cvmix_conv_params_in)
         else
           ! convection only affects tracers
           vvconv = mdiff_out(kw)
         end if
 !        if (CVmix_vars%WaterDensity_cntr(kw).gt.                              &
 !            CVmix_vars%AdiabWaterDensity_cntr(kw)) then
         if (dens(kw).gt.dens_lwr(kw)) then
           mdiff_out(kw+1) = vvconv
           tdiff_out(kw+1) = cvmix_get_conv_real('convect_diff',               &
                                                 cvmix_conv_params_in)
         end if
       end do
     end if
 !EOC
subroutine cvmix_convection::cvmix_coeffs_conv_wrap (type (cvmix_data_type), intent(inout) CVmix_vars, type (cvmix_conv_params_type), intent(in), optional, target CVmix_conv_params_user) private
Definition at line 167 of file cvmix_convection.F90.
References cvmix_conv_params_saved, cvmix_utils::cvmix_update_wrap(), and cvmix_kinds_and_types::cvmix_zero.
 ! !DESCRIPTION:
 !  Computes vertical diffusion coefficients for convective mixing.
 !\\
 !\\
 ! !USES:
 !  Only those used by entire module.
 ! !INPUT PARAMETERS:
     type(cvmix_conv_params_type), optional, target, intent(in)  ::           &
                                              cvmix_conv_params_user
 ! !INPUT/OUTPUT PARAMETERS:
     type(cvmix_data_type), intent(inout) :: cvmix_vars
 !EOP
 !BOC
 !-----------------------------------------------------------------------
 !
 !  local variables
 !
 !-----------------------------------------------------------------------
     real(cvmix_r8), dimension(CVmix_vars%max_nlev+1) :: new_mdiff, new_tdiff
     type(cvmix_conv_params_type), pointer :: cvmix_conv_params_in
     integer :: nlev, max_nlev
     if (present(cvmix_conv_params_user)) then
       cvmix_conv_params_in => cvmix_conv_params_user
     else
       cvmix_conv_params_in => cvmix_conv_params_saved
     end if
     nlev = cvmix_vars%nlev
     max_nlev = cvmix_vars%max_nlev
     if (.not.associated(cvmix_vars%Mdiff_iface)) &
       call cvmix_put(cvmix_vars, "Mdiff", cvmix_zero, max_nlev)
     if (.not.associated(cvmix_vars%Tdiff_iface)) &
       call cvmix_put(cvmix_vars, "Tdiff", cvmix_zero, max_nlev)
     call cvmix_coeffs_conv(new_mdiff, new_tdiff,                              &
                            cvmix_vars%SqrBuoyancyFreq_iface,                  &
                            cvmix_vars%WaterDensity_cntr,                      &
                            cvmix_vars%AdiabWaterDensity_cntr,                 &
                            nlev, max_nlev, cvmix_conv_params_user)
     call cvmix_update_wrap(cvmix_conv_params_in%handle_old_vals, max_nlev,    &
                            mdiff_out = cvmix_vars%Mdiff_iface,                &
                            new_mdiff = new_mdiff,                             &
                            tdiff_out = cvmix_vars%Tdiff_iface,                &
                            new_tdiff = new_tdiff)
 !EOC
real(cvmix_r8) function, public cvmix_convection::cvmix_get_conv_real (character(len=*), intent(in) varname, type(cvmix_conv_params_type), intent(in), optional, target CVmix_conv_params_user)
Definition at line 503 of file cvmix_convection.F90.
References cvmix_conv_params_saved, and cvmix_kinds_and_types::cvmix_zero.
Referenced by cvmix_coeffs_conv_low().
 ! !DESCRIPTION:
 !  Read the real value of a cvmix\_conv\_params\_type variable.
 !\\
 !\\
 ! !USES:
 !  Only those used by entire module.
 ! !INPUT PARAMETERS:
     character(len=*),             intent(in) :: varname
     type(cvmix_conv_params_type), optional, target, intent(in) ::             &
                                            cvmix_conv_params_user
 ! !OUTPUT PARAMETERS:
     real(cvmix_r8) :: cvmix_get_conv_real
 !EOP
 !BOC
     type(cvmix_conv_params_type), pointer :: cvmix_conv_params_get
     if (present(cvmix_conv_params_user)) then
       cvmix_conv_params_get => cvmix_conv_params_user
     else
       cvmix_conv_params_get => cvmix_conv_params_saved
     end if
     cvmix_get_conv_real = cvmix_zero
     select case (trim(varname))
       case ('convect_diff')
         cvmix_get_conv_real = cvmix_conv_params_get%convect_diff
       case ('convect_visc')
         cvmix_get_conv_real = cvmix_conv_params_get%convect_visc
       case DEFAULT
         print*, "ERROR: ", trim(varname), " not a valid choice!"
         stop 1
     end select
 !EOC
subroutine, public cvmix_convection::cvmix_init_conv (real(cvmix_r8), intent(in) convect_diff, real(cvmix_r8), intent(in) convect_visc, logical, intent(in), optional lBruntVaisala, real(cvmix_r8), intent(in), optional BVsqr_convect, character(len=cvmix_strlen), intent(in), optional old_vals, type (cvmix_conv_params_type), intent(inout), optional CVmix_conv_params_user)
Definition at line 95 of file cvmix_convection.F90.
References cvmix_kinds_and_types::cvmix_max_old_and_new_vals, cvmix_kinds_and_types::cvmix_overwrite_old_val, cvmix_kinds_and_types::cvmix_sum_old_and_new_vals, and cvmix_kinds_and_types::cvmix_zero.
 ! !DESCRIPTION:
 !  Initialization routine for specifying convective mixing coefficients.
 !\\
 !\\
 ! !USES:
 !  Only those used by entire module.
 ! !OUTPUT PARAMETERS:
     type(cvmix_conv_params_type), optional, intent(inout) ::                 &
                                        cvmix_conv_params_user
 ! !INPUT PARAMETERS:
     real(cvmix_r8), intent(in) :: &
       convect_diff,      &! diffusivity to parameterize convection
       convect_visc        ! viscosity to parameterize convection
     logical,        intent(in), optional :: lbruntvaisala ! True => B-V mixing
     real(cvmix_r8), intent(in), optional :: bvsqr_convect ! B-V parameter
     character(len=cvmix_strlen), optional, intent(in) :: old_vals
 !EOP
 !BOC
     ! Set convect_diff and convect_visc in conv_params_type
     call cvmix_put_conv("convect_diff", convect_diff, cvmix_conv_params_user)
     call cvmix_put_conv("convect_visc", convect_visc, cvmix_conv_params_user)
     if (present(lbruntvaisala)) then
       call cvmix_put_conv("lBruntVaisala", lbruntvaisala,                     &
                           cvmix_conv_params_user)
     else
       call cvmix_put_conv("lBruntVaisala", .false., cvmix_conv_params_user)
     end if
     if (present(bvsqr_convect)) then
       call cvmix_put_conv("BVsqr_convect", bvsqr_convect,                     &
                           cvmix_conv_params_user)
     else
       call cvmix_put_conv("BVsqr_convect", cvmix_zero, cvmix_conv_params_user)
     end if
     if (present(old_vals)) then
       select case (trim(old_vals))
         case ("overwrite")
           call cvmix_put_conv('handle_old_vals', cvmix_overwrite_old_val,     &
                                cvmix_conv_params_user)
         case ("sum")
           call cvmix_put_conv('handle_old_vals', cvmix_sum_old_and_new_vals,  &
                                cvmix_conv_params_user)
         case ("max")
           call cvmix_put_conv('handle_old_vals', cvmix_max_old_and_new_vals,  &
                                cvmix_conv_params_user)
         case DEFAULT
           print*, "ERROR: ", trim(old_vals), " is not a valid option for ",   &
                   "handling old values of diff and visc."
           stop 1
       end select
     else
       call cvmix_put_conv('handle_old_vals', cvmix_overwrite_old_val,         &
                                cvmix_conv_params_user)
     end if
 !EOC
subroutine cvmix_convection::cvmix_put_conv_int (character(len=*), intent(in) varname, integer, intent(in) val, type (cvmix_conv_params_type), intent(inout), optional, target CVmix_conv_params_user) private
Definition at line 360 of file cvmix_convection.F90.
References cvmix_conv_params_saved.
 ! !DESCRIPTION:
 !  Write a real value into a cvmix\_conv\_params\_type variable.
 !\\
 !\\
 ! !USES:
 !  Only those used by entire module.
 ! !INPUT PARAMETERS:
     character(len=*), intent(in) :: varname
     integer,          intent(in) :: val
 ! !OUTPUT PARAMETERS:
     type(cvmix_conv_params_type), optional, target, intent(inout) ::         &
                                                cvmix_conv_params_user
 !EOP
 !BOC
     type(cvmix_conv_params_type), pointer :: cvmix_conv_params_out
     if (present(cvmix_conv_params_user)) then
       cvmix_conv_params_out => cvmix_conv_params_user
     else
       cvmix_conv_params_out => cvmix_conv_params_saved
     end if
     select case (trim(varname))
       case ("old_vals", "handle_old_vals")
         cvmix_conv_params_out%handle_old_vals = val
       case DEFAULT
         call cvmix_put_conv(varname, real(val, cvmix_r8),                     &
                             cvmix_conv_params_user)
     end select
 !EOC
subroutine cvmix_convection::cvmix_put_conv_logical (character(len=*), intent(in) varname, logical, intent(in) val, type (cvmix_conv_params_type), intent(inout), optional, target CVmix_conv_params_user) private
Definition at line 457 of file cvmix_convection.F90.
References cvmix_conv_params_saved.
 ! !DESCRIPTION:
 !  Write a Boolean value into a cvmix\_conv\_params\_type variable.
 !\\
 !\\
 ! !USES:
 !  Only those used by entire module.
 ! !INPUT PARAMETERS:
     character(len=*), intent(in) :: varname
     logical,          intent(in) :: val
 ! !OUTPUT PARAMETERS:
     type(cvmix_conv_params_type), optional, target, intent(inout) ::         &
                                                cvmix_conv_params_user
 !EOP
 !BOC
     type(cvmix_conv_params_type), pointer :: cvmix_conv_params_out
     if (present(cvmix_conv_params_user)) then
       cvmix_conv_params_out => cvmix_conv_params_user
     else
       cvmix_conv_params_out => cvmix_conv_params_saved
     end if
     select case (trim(varname))
       case ('lBruntVaisala')
         cvmix_conv_params_out%lBruntVaisala = val
       case DEFAULT
         print*, "ERROR: ", trim(varname), " not a valid choice!"
         stop 1
     end select
 !EOC
subroutine cvmix_convection::cvmix_put_conv_real (character(len=*), intent(in) varname, real(cvmix_r8), intent(in) val, type (cvmix_conv_params_type), intent(inout), optional, target CVmix_conv_params_user) private
Definition at line 406 of file cvmix_convection.F90.
References cvmix_conv_params_saved.
 ! !DESCRIPTION:
 !  Write a real value into a cvmix\_conv\_params\_type variable.
 !\\
 !\\
 ! !USES:
 !  Only those used by entire module.
 ! !INPUT PARAMETERS:
     character(len=*), intent(in) :: varname
     real(cvmix_r8),   intent(in) :: val
 ! !OUTPUT PARAMETERS:
     type(cvmix_conv_params_type), optional, target, intent(inout) ::         &
                                                cvmix_conv_params_user
 !EOP
 !BOC
     type(cvmix_conv_params_type), pointer :: cvmix_conv_params_out
     if (present(cvmix_conv_params_user)) then
       cvmix_conv_params_out => cvmix_conv_params_user
     else
       cvmix_conv_params_out => cvmix_conv_params_saved
     end if
     select case (trim(varname))
       case ('convect_diff')
         cvmix_conv_params_out%convect_diff = val
       case ('convect_visc')
         cvmix_conv_params_out%convect_visc = val
       case ('BVsqr_convect')
         cvmix_conv_params_out%BVsqr_convect = val
       case DEFAULT
         print*, "ERROR: ", trim(varname), " not a valid choice!"
         stop 1
     end select
 !EOC
Variable Documentation
type(cvmix_conv_params_type), target cvmix_convection::cvmix_conv_params_saved
Definition at line 84 of file cvmix_convection.F90.
Referenced by cvmix_coeffs_conv_low(), cvmix_coeffs_conv_wrap(), cvmix_get_conv_real(), cvmix_put_conv_int(), cvmix_put_conv_logical(), and cvmix_put_conv_real().
   type(cvmix_conv_params_type), target :: cvmix_conv_params_saved