MOM6: mom_tracer_registry Module Reference
mom_tracer_registry Module Reference
This module contains the tracer_registry_type and the subroutines that handle registration of tracers and related subroutines. The primary subroutine, register_tracer, is called to indicate the tracers advected and diffused.
Data Types
type tracer_registry_type
Type to carry basic tracer information.
type tracer_type
The tracer type.
Functions/Subroutines
subroutine, public register_tracer (tr1, tr_desc, param_file, HI, GV, Reg, tr_desc_ptr, ad_x, ad_y, df_x, df_y, OBC_inflow, OBC_in_u, OBC_in_v, ad_2d_x, ad_2d_y, df_2d_x, df_2d_y, advection_xy)
This subroutine registers a tracer to be advected and laterally diffused.
subroutine, public lock_tracer_registry (Reg)
This subroutine locks the tracer registry to prevent the addition of more tracers. After locked=.true., can then register common diagnostics.
subroutine, public add_tracer_obc_values (name, Reg, OBC_inflow, OBC_in_u, OBC_in_v)
This subroutine adds open boundary condition concentrations for a tracer that has previously been registered by a call to register_tracer.
subroutine, public add_tracer_diagnostics (name, Reg, ad_x, ad_y, df_x, df_y, ad_2d_x, ad_2d_y, df_2d_x, df_2d_y, advection_xy)
This subroutine adds diagnostic arrays for a tracer that has previously been registered by a call to register_tracer.
subroutine, public tracer_vertdiff (h_old, ea, eb, dt, tr, G, GV, sfc_flux, btm_flux, btm_reservoir, sink_rate)
This subroutine solves a tridiagonal equation for the final tracer concentrations after the dual-entrainments, and possibly sinking or surface and bottom sources, are applied. The sinking is implemented with an fully implicit upwind advection scheme.
subroutine, public mom_tracer_chksum (mesg, Tr, ntr, G)
This subroutine writes out chksums for thermodynamic state variables.
subroutine, public tracer_registry_init (param_file, Reg)
This routine include declares and sets the variable "version".
subroutine, public tracer_registry_end (Reg)
This routine closes the tracer registry module.
Detailed Description
This module contains the tracer_registry_type and the subroutines that handle registration of tracers and related subroutines. The primary subroutine, register_tracer, is called to indicate the tracers advected and diffused.
Function/Subroutine Documentation
subroutine, public mom_tracer_registry::add_tracer_diagnostics (character(len=*), intent(in) name, type(tracer_registry_type), pointer Reg, real, dimension(:,:,:), optional, pointer ad_x, real, dimension(:,:,:), optional, pointer ad_y, real, dimension(:,:,:), optional, pointer df_x, real, dimension(:,:,:), optional, pointer df_y, real, dimension(:,:), optional, pointer ad_2d_x, real, dimension(:,:), optional, pointer ad_2d_y, real, dimension(:,:), optional, pointer df_2d_x, real, dimension(:,:), optional, pointer df_2d_y, real, dimension(:,:,:), optional, pointer advection_xy)
This subroutine adds diagnostic arrays for a tracer that has previously been registered by a call to register_tracer.
Parameters
[in] name name of the tracer for which the diagnostic points
reg pointer to the tracer registry
ad_x diagnostic x-advective flux (CONC m3/s or CONC*kg/s)
ad_y diagnostic y-advective flux (CONC m3/s or CONC*kg/s)
df_x diagnostic x-diffusive flux (CONC m3/s or CONC*kg/s)
df_y diagnostic y-diffusive flux (CONC m3/s or CONC*kg/s)
ad_2d_x vert sum of diagnostic x-advect flux (CONC m3/s or CONC*kg/s)
ad_2d_y vert sum of diagnostic y-advect flux (CONC m3/s or CONC*kg/s)
df_2d_x vert sum of diagnostic x-diffuse flux (CONC m3/s or CONC*kg/s)
df_2d_y vert sum of diagnostic y-diffuse flux (CONC m3/s or CONC*kg/s)
advection_xy convergence of lateral advective tracer fluxes
Definition at line 209 of file MOM_tracer_registry.F90.
References mom_error_handler::mom_error().
Referenced by user_tracer_example::user_initialize_tracer().
   character(len=*), intent(in)              :: name         !< name of the tracer for which the diagnostic points
   type(tracer_registry_type), pointer       :: reg          !< pointer to the tracer registry
   real, dimension(:,:,:), pointer, optional :: ad_x         !< diagnostic x-advective flux (CONC m3/s or CONC*kg/s)
   real, dimension(:,:,:), pointer, optional :: ad_y         !< diagnostic y-advective flux (CONC m3/s or CONC*kg/s)
   real, dimension(:,:,:), pointer, optional :: df_x         !< diagnostic x-diffusive flux (CONC m3/s or CONC*kg/s)
   real, dimension(:,:,:), pointer, optional :: df_y         !< diagnostic y-diffusive flux (CONC m3/s or CONC*kg/s)
   real, dimension(:,:),   pointer, optional :: ad_2d_x      !< vert sum of diagnostic x-advect flux (CONC m3/s or CONC*kg/s)
   real, dimension(:,:),   pointer, optional :: ad_2d_y      !< vert sum of diagnostic y-advect flux (CONC m3/s or CONC*kg/s)
   real, dimension(:,:),   pointer, optional :: df_2d_x      !< vert sum of diagnostic x-diffuse flux (CONC m3/s or CONC*kg/s)
   real, dimension(:,:),   pointer, optional :: df_2d_y      !< vert sum of diagnostic y-diffuse flux (CONC m3/s or CONC*kg/s)
   real, dimension(:,:,:), pointer, optional :: advection_xy !< convergence of lateral advective tracer fluxes
   integer :: m
   if (.not. associated(reg)) call mom_error(fatal, "add_tracer_diagnostics: "// &
        "register_tracer must be called before add_tracer_diagnostics")
   do m=1,reg%ntr ; if (reg%Tr(m)%name == trim(name)) exit ; enddo
   if (m <= reg%ntr) then
     if (present(ad_x)) then ; if (associated(ad_x)) reg%Tr(m)%ad_x => ad_x ; endif
     if (present(ad_y)) then ; if (associated(ad_y)) reg%Tr(m)%ad_y => ad_y ; endif
     if (present(df_x)) then ; if (associated(df_x)) reg%Tr(m)%df_x => df_x ; endif
     if (present(df_y)) then ; if (associated(df_y)) reg%Tr(m)%df_y => df_y ; endif
     if (present(ad_2d_x)) then ; if (associated(ad_2d_x)) reg%Tr(m)%ad2d_x => ad_2d_x ; endif
     if (present(ad_2d_y)) then ; if (associated(ad_2d_y)) reg%Tr(m)%ad2d_y => ad_2d_y ; endif
     if (present(df_2d_x)) then ; if (associated(df_2d_x)) reg%Tr(m)%df2d_x => df_2d_x ; endif
     if (present(df_2d_y)) then ; if (associated(df_2d_y)) reg%Tr(m)%df2d_y => df_2d_y ; endif
     if (present(advection_xy)) then ; if (associated(advection_xy)) reg%Tr(m)%advection_xy => advection_xy ; endif
   else
     call mom_error(fatal, "MOM_tracer: register_tracer must be called for "//&
              trim(name)//" before add_tracer_diagnostics is called for it.")
   endif
subroutine, public mom_tracer_registry::add_tracer_obc_values (character(len=*), intent(in) name, type(tracer_registry_type), pointer Reg, real, intent(in), optional OBC_inflow, real, dimension(:,:,:), optional, pointer OBC_in_u, real, dimension(:,:,:), optional, pointer OBC_in_v)
This subroutine adds open boundary condition concentrations for a tracer that has previously been registered by a call to register_tracer.
Parameters
[in] name tracer name for which the diagnostic points
reg pointer to the tracer registry
[in] obc_inflow tracer value for all inflows via the OBC for which OBC_in_u or OBC_in_v are not specified (same units as tracer CONC)
obc_in_u tracer at inflows through u-face of tracer cells (same units as tracer CONC)
obc_in_v tracer at inflows through v-face of tracer cells (same units as tracer CONC)
Definition at line 173 of file MOM_tracer_registry.F90.
References mom_error_handler::mom_error().
Referenced by mom_state_initialization::set_open_bdry_conds(), and user_tracer_example::user_initialize_tracer().
   character(len=*), intent(in)               :: name        !< tracer name for which the diagnostic points
   type(tracer_registry_type), pointer        :: reg         !< pointer to the tracer registry
   real, intent(in), optional                 :: obc_inflow  !< tracer value for all inflows via the OBC
                                                             !! for which OBC_in_u or OBC_in_v are
                                                             !! not specified (same units as tracer CONC)
   real, pointer, dimension(:,:,:), optional  :: obc_in_u    !< tracer at inflows through u-face of tracer cells
                                                             !! (same units as tracer CONC)
   real, pointer, dimension(:,:,:), optional  :: obc_in_v    !< tracer at inflows through v-face of tracer cells
                                                             !! (same units as tracer CONC)
   integer :: m
   if (.not. associated(reg)) call mom_error(fatal, "add_tracer_OBC_values :"// &
        "register_tracer must be called before add_tracer_OBC_values")
   do m=1,reg%ntr ; if (reg%Tr(m)%name == trim(name)) exit ; enddo
   if (m <= reg%ntr) then
     if (present(obc_inflow)) reg%Tr(m)%OBC_inflow_conc = obc_inflow
     if (present(obc_in_u)) then ; if (associated(obc_in_u)) &
                                       reg%Tr(m)%OBC_in_u => obc_in_u ; endif
     if (present(obc_in_v)) then ; if (associated(obc_in_v)) &
                                       reg%Tr(m)%OBC_in_v => obc_in_v ; endif
   else
     call mom_error(fatal, "MOM_tracer: register_tracer must be called for "//&
              trim(name)//" before add_tracer_OBC_values is called for it.")
   endif
subroutine, public mom_tracer_registry::lock_tracer_registry (type(tracer_registry_type), pointer Reg)
This subroutine locks the tracer registry to prevent the addition of more tracers. After locked=.true., can then register common diagnostics.
Parameters
reg pointer to the tracer registry
Definition at line 160 of file MOM_tracer_registry.F90.
References mom_error_handler::mom_error().
Referenced by mom::initialize_mom().
   type(tracer_registry_type), pointer    :: reg    !< pointer to the tracer registry
   if (.not. associated(reg)) call mom_error(warning, &
     "lock_tracer_registry called with an unassocaited registry.")
   reg%locked = .true.
subroutine, public mom_tracer_registry::mom_tracer_chksum (character(len=*), intent(in) mesg, type(tracer_type), dimension(:), intent(in) Tr, integer, intent(in) ntr, type(ocean_grid_type), intent(in) G)
This subroutine writes out chksums for thermodynamic state variables.
Parameters
[in] mesg message that appears on the chksum lines
[in] tr array of all of registered tracers
[in] ntr number of registered tracers
[in] g ocean grid structure
Definition at line 426 of file MOM_tracer_registry.F90.
Referenced by mom_tracer_hor_diff::tracer_hordiff().
   character(len=*),         intent(in) :: mesg   !< message that appears on the chksum lines
   type(tracer_type),        intent(in) :: tr(:)  !< array of all of registered tracers
   integer,                  intent(in) :: ntr    !< number of registered tracers
   type(ocean_grid_type),    intent(in) :: g      !< ocean grid structure
   integer :: is, ie, js, je, nz, m
   is = g%isc ; ie = g%iec ; js = g%jsc ; je = g%jec ; nz = g%ke
   do m=1,ntr
     call hchksum(tr(m)%t, mesg//trim(tr(m)%name), g)
   enddo
subroutine, public mom_tracer_registry::register_tracer (real, dimension(szi_(hi),szj_(hi),szk_(gv)), target tr1, type(vardesc), intent(in) tr_desc, type(param_file_type), intent(in) param_file, type(hor_index_type), intent(in) HI, type(verticalgrid_type), intent(in) GV, type(tracer_registry_type), pointer Reg, type(vardesc), optional, target tr_desc_ptr, real, dimension(:,:,:), optional, pointer ad_x, real, dimension(:,:,:), optional, pointer ad_y, real, dimension(:,:,:), optional, pointer df_x, real, dimension(:,:,:), optional, pointer df_y, real, intent(in), optional OBC_inflow, real, dimension(:,:,:), optional, pointer OBC_in_u, real, dimension(:,:,:), optional, pointer OBC_in_v, real, dimension(:,:), optional, pointer ad_2d_x, real, dimension(:,:), optional, pointer ad_2d_y, real, dimension(:,:), optional, pointer df_2d_x, real, dimension(:,:), optional, pointer df_2d_y, real, dimension(:,:,:), optional, pointer advection_xy)
This subroutine registers a tracer to be advected and laterally diffused.
Parameters
[in] hi horizontal index type
[in] gv ocean vertical grid structure
tr1 pointer to the tracer (concentration units)
[in] tr_desc metadata about the tracer
[in] param_file file to parse for model parameter values
reg pointer to the tracer registry
tr_desc_ptr A target that can be used to set a pointer to the stored value of trtr_desc. This target must be an enduring part of the control structure, because the tracer registry will use this memory, but it also means that any updates to this structure in the calling module will be available subsequently to the tracer registry.
ad_x diagnostic x-advective flux (CONC m3/s or CONC*kg/s)
ad_y diagnostic y-advective flux (CONC m3/s or CONC*kg/s)
df_x diagnostic x-diffusive flux (CONC m3/s or CONC*kg/s)
df_y diagnostic y-diffusive flux (CONC m3/s or CONC*kg/s)
[in] obc_inflow the tracer for all inflows via OBC for which OBC_in_u or OBC_in_v are not specified (units of tracer CONC)
obc_in_u tracer at inflows through u-faces of tracer cells (units of tracer CONC)
obc_in_v tracer at inflows through v-faces of tracer cells (units of tracer CONC)
ad_2d_x vert sum of diagnostic x-advect flux (CONC m3/s or CONC*kg/s)
ad_2d_y vert sum of diagnostic y-advect flux (CONC m3/s or CONC*kg/s)
df_2d_x vert sum of diagnostic x-diffuse flux (CONC m3/s or CONC*kg/s)
df_2d_y vert sum of diagnostic y-diffuse flux (CONC m3/s or CONC*kg/s)
advection_xy convergence of lateral advective tracer fluxes
Definition at line 80 of file MOM_tracer_registry.F90.
References mom_error_handler::mom_error(), mom_io::query_vardesc(), and tracer_registry_init().
   type(hor_index_type),           intent(in)    :: hi           !< horizontal index type
   type(verticalgrid_type),        intent(in)    :: gv           !< ocean vertical grid structure
   real, dimension(SZI_(HI),SZJ_(HI),SZK_(GV)), target :: tr1    !< pointer to the tracer (concentration units)
   type(vardesc),         intent(in)             :: tr_desc      !< metadata about the tracer
   type(param_file_type), intent(in)             :: param_file   !< file to parse for  model parameter values
   type(tracer_registry_type), pointer           :: reg          !< pointer to the tracer registry
   type(vardesc), target, optional               :: tr_desc_ptr  !< A target that can be used to set a pointer to the
                                                                 !! stored value of tr%tr_desc.  This target must be an
                                                                 !! enduring part of the control structure, because the tracer
                                                                 !! registry will use this memory, but it also means that any
                                                                 !! updates to this structure in the calling module will be
                                                                 !! available subsequently to the tracer registry.
   real, pointer, dimension(:,:,:), optional     :: ad_x         !< diagnostic x-advective flux (CONC m3/s or CONC*kg/s)
   real, pointer, dimension(:,:,:), optional     :: ad_y         !< diagnostic y-advective flux (CONC m3/s or CONC*kg/s)
   real, pointer, dimension(:,:,:), optional     :: df_x         !< diagnostic x-diffusive flux (CONC m3/s or CONC*kg/s)
   real, pointer, dimension(:,:,:), optional     :: df_y         !< diagnostic y-diffusive flux (CONC m3/s or CONC*kg/s)
   real, intent(in),                optional     :: obc_inflow   !< the tracer for all inflows via OBC for which OBC_in_u
                                                                 !! or OBC_in_v are not specified (units of tracer CONC)
   real, pointer, dimension(:,:,:), optional     :: obc_in_u     !< tracer at inflows through u-faces of
                                                                 !! tracer cells (units of tracer CONC)
   real, pointer, dimension(:,:,:), optional     :: obc_in_v     !< tracer at inflows through v-faces of
                                                                 !! tracer cells (units of tracer CONC)
   real, dimension(:,:),   pointer, optional     :: ad_2d_x      !< vert sum of diagnostic x-advect flux (CONC m3/s or CONC*kg/s)
   real, dimension(:,:),   pointer, optional     :: ad_2d_y      !< vert sum of diagnostic y-advect flux (CONC m3/s or CONC*kg/s)
   real, dimension(:,:),   pointer, optional     :: df_2d_x      !< vert sum of diagnostic x-diffuse flux (CONC m3/s or CONC*kg/s)
   real, dimension(:,:),   pointer, optional     :: df_2d_y      !< vert sum of diagnostic y-diffuse flux (CONC m3/s or CONC*kg/s)
   real, pointer, dimension(:,:,:), optional     :: advection_xy !< convergence of lateral advective tracer fluxes
   integer :: ntr
   type(tracer_type) :: temp
   character(len=256) :: mesg    ! Message for error messages.
   if (.not. associated(reg)) call tracer_registry_init(param_file, reg)
   if (reg%ntr>=max_fields_) then
     write(mesg,'("Increase MAX_FIELDS_ in MOM_memory.h to at least ",I3," to allow for &
         &all the tracers being registered via register_tracer.")') reg%ntr+1
     call mom_error(fatal,"MOM register_tracer: "//mesg)
   endif
   reg%ntr = reg%ntr + 1
   ntr     = reg%ntr
   if (present(tr_desc_ptr)) then
     reg%Tr(ntr)%vd => tr_desc_ptr
   else
     allocate(reg%Tr(ntr)%vd) ; reg%Tr(ntr)%vd = tr_desc
   endif
   call query_vardesc(reg%Tr(ntr)%vd, name=reg%Tr(ntr)%name)
   if (reg%locked) call mom_error(fatal, &
       "MOM register_tracer was called for variable "//trim(reg%Tr(ntr)%name)//&
       " with a locked tracer registry.")
   reg%Tr(ntr)%t => tr1
   if (present(ad_x)) then ; if (associated(ad_x)) reg%Tr(ntr)%ad_x => ad_x ; endif
   if (present(ad_y)) then ; if (associated(ad_y)) reg%Tr(ntr)%ad_y => ad_y ; endif
   if (present(df_x)) then ; if (associated(df_x)) reg%Tr(ntr)%df_x => df_x ; endif
   if (present(df_y)) then ; if (associated(df_y)) reg%Tr(ntr)%df_y => df_y ; endif
   if (present(obc_inflow)) reg%Tr(ntr)%OBC_inflow_conc = obc_inflow
   if (present(obc_in_u)) then ; if (associated(obc_in_u)) &
                                     reg%Tr(ntr)%OBC_in_u => obc_in_u ; endif
   if (present(obc_in_v)) then ; if (associated(obc_in_v)) &
                                     reg%Tr(ntr)%OBC_in_v => obc_in_v ; endif
   if (present(ad_2d_x)) then ; if (associated(ad_2d_x)) reg%Tr(ntr)%ad2d_x => ad_2d_x ; endif
   if (present(ad_2d_y)) then ; if (associated(ad_2d_y)) reg%Tr(ntr)%ad2d_y => ad_2d_y ; endif
   if (present(df_2d_x)) then ; if (associated(df_2d_x)) reg%Tr(ntr)%df2d_x => df_2d_x ; endif
   if (present(advection_xy)) then ; if (associated(advection_xy)) reg%Tr(ntr)%advection_xy => advection_xy ; endif
subroutine, public mom_tracer_registry::tracer_registry_end (type(tracer_registry_type), pointer Reg)
This routine closes the tracer registry module.
Definition at line 470 of file MOM_tracer_registry.F90.
   type(tracer_registry_type), pointer :: reg
   if (associated(reg)) deallocate(reg)
subroutine, public mom_tracer_registry::tracer_registry_init (type(param_file_type), intent(in) param_file, type(tracer_registry_type), pointer Reg)
This routine include declares and sets the variable "version".
Parameters
[in] param_file open file to parse for model parameters
reg pointer to tracer registry
Definition at line 443 of file MOM_tracer_registry.F90.
Referenced by register_tracer().
   type(param_file_type),      intent(in) :: param_file !< open file to parse for model parameters
   type(tracer_registry_type), pointer    :: reg        !< pointer to tracer registry
   integer, save :: init_calls = 0
 #include "version_variable.h"
   character(len=40)  :: mod = "MOM_tracer_registry" ! This module's name.
   character(len=256) :: mesg    ! Message for error messages.
   if (.not.associated(reg)) then ; allocate(reg)
   else ; return ; endif
   ! Read all relevant parameters and write them to the model log.
   call log_version(param_file, mod, version, "")
   init_calls = init_calls + 1
   if (init_calls > 1) then
     write(mesg,'("tracer_registry_init called ",I3, &
       &" times with different registry pointers.")') init_calls
     if (is_root_pe()) call mom_error(warning,"MOM_tracer"//mesg)
   endif
subroutine, public mom_tracer_registry::tracer_vertdiff (real, dimension(szi_(g),szj_(g),szk_(gv)), intent(in) h_old, real, dimension(szi_(g),szj_(g),szk_(gv)), intent(in) ea, real, dimension(szi_(g),szj_(g),szk_(gv)), intent(in) eb, real, intent(in) dt, real, dimension(szi_(g),szj_(g),szk_(gv)), intent(inout) tr, type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, real, dimension(szi_(g),szj_(g)), intent(in), optional sfc_flux, real, dimension(szi_(g),szj_(g)), intent(in), optional btm_flux, real, dimension(szi_(g),szj_(g)), intent(inout), optional btm_reservoir, real, intent(in), optional sink_rate)
This subroutine solves a tridiagonal equation for the final tracer concentrations after the dual-entrainments, and possibly sinking or surface and bottom sources, are applied. The sinking is implemented with an fully implicit upwind advection scheme.
Parameters
[in] g ocean grid structure
[in] gv ocean vertical grid structure
[in] h_old layer thickness before entrainment (m or kg m-2)
[in] ea amount of fluid entrained from the layer above (units of h_old)
[in] eb amount of fluid entrained from the layer below (units of h_old)
[in,out] tr tracer concentration (in concentration units CU)
[in] dt amount of time covered by this call (seconds)
[in] sfc_flux surface flux of the tracer (in CU * kg m-2 s-1)
[in] btm_flux The (negative upward) bottom flux of the tracer, in units of (CU * kg m-2 s-1)
[in,out] btm_reservoir amount of tracer in a bottom reservoir (units of CU kg m-2; formerly CU m)
[in] sink_rate rate at which the tracer sinks, in m s-1
Definition at line 257 of file MOM_tracer_registry.F90.
Referenced by ideal_age_example::ideal_age_tracer_column_physics(), and mom_ocmip2_cfc::ocmip2_cfc_column_physics().
   type(ocean_grid_type),                     intent(in)    :: g             !< ocean grid structure
   type(verticalgrid_type),                   intent(in)    :: gv            !< ocean vertical grid structure
   real, dimension(SZI_(G),SZJ_(G),SZK_(GV)), intent(in)    :: h_old         !< layer thickness before entrainment (m or kg m-2)
   real, dimension(SZI_(G),SZJ_(G),SZK_(GV)), intent(in)    :: ea            !< amount of fluid entrained from the layer above (units of h_old)
   real, dimension(SZI_(G),SZJ_(G),SZK_(GV)), intent(in)    :: eb            !< amount of fluid entrained from the layer below (units of h_old)
   real, dimension(SZI_(G),SZJ_(G),SZK_(GV)), intent(inout) :: tr            !< tracer concentration (in concentration units CU)
   real,                                      intent(in)    :: dt            !< amount of time covered by this call (seconds)
   real, dimension(SZI_(G),SZJ_(G)), optional,intent(in)    :: sfc_flux      !< surface flux of the tracer (in CU * kg m-2 s-1)
   real, dimension(SZI_(G),SZJ_(G)), optional,intent(in)    :: btm_flux      !< The (negative upward) bottom flux of the tracer,
                                                                             !! in units of (CU * kg m-2 s-1)
   real, dimension(SZI_(G),SZJ_(G)), optional,intent(inout) :: btm_reservoir !< amount of tracer in a bottom reservoir (units of CU kg m-2; formerly CU m)
   real,                             optional,intent(in)    :: sink_rate     !< rate at which the tracer sinks, in m s-1
   real :: sink_dist ! The distance the tracer sinks in a time step, in m or kg m-2.
   real, dimension(SZI_(G),SZJ_(G)) :: &
     sfc_src, &      ! The time-integrated surface source of the tracer, in
                     ! units of m or kg m-2 times a concentration.
     btm_src         ! The time-integrated bottom source of the tracer, in
                     ! units of m or kg m-2  times a concentration.
   real, dimension(SZI_(G)) :: &
     b1, &           ! b1 is used by the tridiagonal solver, in m-1 or m2 kg-1.
     d1              ! d1=1-c1 is used by the tridiagonal solver, nondimensional.
   real :: c1(szi_(g),szk_(gv))    ! c1 is used by the tridiagonal solver, ND.
   real :: h_minus_dsink(szi_(g),szk_(gv)) ! The layer thickness minus the
                     ! difference in sinking rates across the layer, in m or kg m-2.
                     ! By construction, 0 <= h_minus_dsink < h_old.
   real :: sink(szi_(g),szk_(gv)+1) ! The tracer's sinking distances at the
                     ! interfaces, limited to prevent characteristics from
                     ! crossing within a single timestep, in m or kg m-2.
   real :: b_denom_1 ! The first term in the denominator of b1, in m or kg m-2.
   real :: h_tr      ! h_tr is h at tracer points with a h_neglect added to
                     ! ensure positive definiteness, in m or kg m-2.
   real :: h_neglect ! A thickness that is so small it is usually lost
                     ! in roundoff and can be neglected, in m.
   integer :: i, j, k, is, ie, js, je, nz
   is = g%isc ; ie = g%iec ; js = g%jsc ; je = g%jec ; nz = gv%ke
   h_neglect = gv%H_subroundoff
   sink_dist = 0.0
   if (present(sink_rate)) sink_dist = (dt*sink_rate) * gv%m_to_H
 !$OMP parallel default(none) shared(is,ie,js,je,sfc_src,btm_src,sfc_flux,dt,G,GV,btm_flux, &
 !$OMP                               sink_rate,btm_reservoir,nz,sink_dist,h_old,ea,      &
 !$OMP                               h_neglect,eb,tr) &
 !$OMP                       private(sink,h_minus_dsink,b_denom_1,b1,d1,h_tr,c1)
 !$OMP do
   do j=js,je; do i=is,ie ; sfc_src(i,j) = 0.0 ; btm_src(i,j) = 0.0 ; enddo; enddo
   if (present(sfc_flux)) then
 !$OMP do
      do j = js, je; do i = is,ie
         sfc_src(i,j) = (sfc_flux(i,j)*dt) * gv%kg_m2_to_H
      enddo; enddo
   endif
   if (present(btm_flux)) then
 !$OMP do
      do j = js, je; do i = is,ie
         btm_src(i,j) = (btm_flux(i,j)*dt) * gv%kg_m2_to_H
      enddo; enddo
   endif
   if (present(sink_rate)) then
 !$OMP do
     do j=js,je
       ! Find the sinking rates at all interfaces, limiting them if necesary
       ! so that the characteristics do not cross within a timestep.
       !   If a non-constant sinking rate were used, that would be incorprated
       ! here.
       if (present(btm_reservoir)) then
         do i=is,ie ; sink(i,nz+1) = sink_dist ; enddo
         do k=2,nz ; do i=is,ie
           sink(i,k) = sink_dist ; h_minus_dsink(i,k) = h_old(i,j,k)
         enddo ; enddo
       else
         do i=is,ie ; sink(i,nz+1) = 0.0 ; enddo
         ! Find the limited sinking distance at the interfaces.
         do k=nz,2,-1 ; do i=is,ie
           if (sink(i,k+1) >= sink_dist) then
             sink(i,k) = sink_dist
             h_minus_dsink(i,k) = h_old(i,j,k) + (sink(i,k+1) - sink(i,k))
           elseif (sink(i,k+1) + h_old(i,j,k) < sink_dist) then
             sink(i,k) = sink(i,k+1) + h_old(i,j,k)
             h_minus_dsink(i,k) = 0.0
           else
             sink(i,k) = sink_dist
             h_minus_dsink(i,k) = (h_old(i,j,k) + sink(i,k+1)) - sink(i,k)
           endif
         enddo ; enddo
       endif
       do i=is,ie
         sink(i,1) = 0.0 ; h_minus_dsink(i,1) = (h_old(i,j,1) + sink(i,2))
       enddo
       ! Now solve the tridiagonal equation for the tracer concentrations.
       do i=is,ie ; if (g%mask2dT(i,j) > 0.5) then
         b_denom_1 = h_minus_dsink(i,1) + ea(i,j,1) + h_neglect
         b1(i) = 1.0 / (b_denom_1 + eb(i,j,1))
         d1(i) = b_denom_1 * b1(i)
         h_tr = h_old(i,j,1) + h_neglect
         tr(i,j,1) = b1(i)*(h_tr*tr(i,j,1) + sfc_src(i,j))
       endif ; enddo
       do k=2,nz-1 ; do i=is,ie ; if (g%mask2dT(i,j) > 0.5) then
         c1(i,k) = eb(i,j,k-1) * b1(i)
         b_denom_1 = h_minus_dsink(i,k) + d1(i) * (ea(i,j,k) + sink(i,k)) + &
                     h_neglect
         b1(i) = 1.0 / (b_denom_1 + eb(i,j,k))
         d1(i) = b_denom_1 * b1(i)
         h_tr = h_old(i,j,k) + h_neglect
         tr(i,j,k) = b1(i) * (h_tr * tr(i,j,k) + &
                              (ea(i,j,k) + sink(i,k)) * tr(i,j,k-1))
       endif ; enddo ; enddo
       do i=is,ie ; if (g%mask2dT(i,j) > 0.5) then
         c1(i,nz) = eb(i,j,nz-1) * b1(i)
         b_denom_1 = h_minus_dsink(i,nz) + d1(i) * (ea(i,j,nz) + sink(i,nz)) + &
                     h_neglect
         b1(i) = 1.0 / (b_denom_1 + eb(i,j,nz))
         h_tr = h_old(i,j,nz) + h_neglect
         tr(i,j,nz) = b1(i) * ((h_tr * tr(i,j,nz) + btm_src(i,j)) + &
                               (ea(i,j,nz) + sink(i,nz)) * tr(i,j,nz-1))
       endif ; enddo
       if (present(btm_reservoir)) then ; do i=is,ie ; if (g%mask2dT(i,j)>0.5) then
         btm_reservoir(i,j) = btm_reservoir(i,j) + &
                              (sink(i,nz+1)*tr(i,j,nz)) * gv%H_to_kg_m2
       endif ; enddo ; endif
       do k=nz-1,1,-1 ; do i=is,ie ; if (g%mask2dT(i,j) > 0.5) then
         tr(i,j,k) = tr(i,j,k) + c1(i,k+1)*tr(i,j,k+1)
       endif ; enddo ; enddo
     enddo
   else
 !$OMP do
     do j=js,je
       do i=is,ie ; if (g%mask2dT(i,j) > 0.5) then
         h_tr = h_old(i,j,1) + h_neglect
         b_denom_1 = h_tr + ea(i,j,1)
         b1(i) = 1.0 / (b_denom_1 + eb(i,j,1))
         d1(i) = b_denom_1 * b1(i)
         tr(i,j,1) = b1(i)*(h_tr*tr(i,j,1) + sfc_src(i,j))
        endif
       enddo
       do k=2,nz-1 ; do i=is,ie ; if (g%mask2dT(i,j) > 0.5) then
         c1(i,k) = eb(i,j,k-1) * b1(i)
         h_tr = h_old(i,j,k) + h_neglect
         b_denom_1 = h_tr + d1(i) * ea(i,j,k)
         b1(i) = 1.0 / (b_denom_1 + eb(i,j,k))
         d1(i) = b_denom_1 * b1(i)
         tr(i,j,k) = b1(i) * (h_tr * tr(i,j,k) + ea(i,j,k) * tr(i,j,k-1))
       endif ; enddo ; enddo
       do i=is,ie ; if (g%mask2dT(i,j) > 0.5) then
         c1(i,nz) = eb(i,j,nz-1) * b1(i)
         h_tr = h_old(i,j,nz) + h_neglect
         b1(i) = 1.0 / (h_tr + d1(i) * ea(i,j,nz) + eb(i,j,nz))
         tr(i,j,nz) = b1(i) * ((h_tr * tr(i,j,nz) + btm_src(i,j)) + &
                               ea(i,j,nz) * tr(i,j,nz-1))
       endif ; enddo
       do k=nz-1,1,-1 ; do i=is,ie ; if (g%mask2dT(i,j) > 0.5) then
         tr(i,j,k) = tr(i,j,k) + c1(i,k+1)*tr(i,j,k+1)
       endif ; enddo ; enddo
     enddo
   endif
 !$OMP end parallel