MOM6: cvmix_utils Module Reference
cvmix_utils Module Reference
Functions/Subroutines
subroutine, public cvmix_update_wrap (old_vals, nlev, Mdiff_out, new_Mdiff, Tdiff_out, new_Tdiff, Sdiff_out, new_Sdiff)
character(len=cvmix_strlen) function, public cvmix_att_name (varname)
Function/Subroutine Documentation
character(len=cvmix_strlen) function, public cvmix_utils::cvmix_att_name (character(len=*), intent(in) varname)
Definition at line 112 of file cvmix_utils.F90.
Referenced by cvmix_put_get::cvmix_put_int(), cvmix_put_get::cvmix_put_real(), and cvmix_put_get::cvmix_put_real_1d().
 ! !DESCRIPTION:
 !  Given a variable short name, returns the precise name of the desired
 !  attribute in the cvmix\_data\_type structure.
 !\\
 !\\
 ! !USES:
 !  Only those used by entire module.
 ! !INPUT PARAMETERS:
     character(len=*), intent(in) :: varname
 ! !OUTPUT PARAMETERS:
     character(len=cvmix_strlen) :: cvmix_att_name
 !EOP
 !BOC
     select case(trim(varname))
       ! Scalars
       case ("nlev", "NumberLevels", "NumberOfLevels")
         cvmix_att_name = "nlev"
       case ("max_nlev", "MaxNumberLevels", "MaxNumberOfLevels")
         cvmix_att_name = "max_nlev"
       case ("depth", "ocn_depth", "OceanDepth", "DepthOfOcean")
         cvmix_att_name = "OceanDepth"
       case ('BoundaryLayerDepth','OBL_depth')
         cvmix_att_name = "BoundaryLayerDepth"
       case ("SSH", "surf_hgt", "SeaSurfaceHeight", "SurfaceHeight", "height")
         cvmix_att_name = "SeaSurfaceHeight"
       case ("surf_fric", "SurfaceFriction")
         cvmix_att_name = "SurfaceFriction"
       case ("surf_buoy", "SurfaceBuoyancy", "SurfaceBuoyancyForcing")
         cvmix_att_name = "SurfaceBuoyancyForcing"
       case ("lat", "latitude", "Latitude")
         cvmix_att_name = "lat"
       case ("lon", "longitude", "Longitude")
         cvmix_att_name = "lon"
       case ("coriolis", "Coriolis", "CoriolisFreq", "CoriolisFrequency")
         cvmix_att_name = "Coriolis"
       case ("kOBL_depth", "BoundaryLayerDepthIndex")
         cvmix_att_name = "kOBL_depth"
       ! Variables on level interfaces
       case ("zw", "zw_iface")
         cvmix_att_name = "zw_iface"
       case ("dzw", "dzw_iface")
         cvmix_att_name = "dzw"
       case ("Mdiff", "Udiff", "MomentumDiff", "MomentumDiffusivity")
         cvmix_att_name = "Mdiff_iface"
       case ("Tdiff", "TempDiff", "TemperatureDiff", "TemperatureDiffusivity")
         cvmix_att_name = "Tdiff_iface"
       case ("Sdiff", "SaltDiff", "SalinityDiff", "SalinityDiffusivity")
         cvmix_att_name = "Sdiff_iface"
       case ("Ri", "Ri_iface", "Richardson", "ShearRichardson",                &
             "RichardsonNumber", "ShearRichardsonNumber",                      &
             "ShearRichardson_iface")
         cvmix_att_name = "ShearRichardson_iface"
       case ("buoy", "buoy_iface", "N", "Nsqr", "BuoyancyFreq", "SqrBuoyancy", &
             "SqrBuoyancyFreq", "SqrBuoyancyFreq_iface")
         cvmix_att_name = "SqrBuoyancyFreq_iface"
       case ("kpp_transport", "kpp_nonlocal", "nonlocal_transport",            &
             "nonlocal", "kpp_nonlocal_iface")
         ! Note: this isn't an attribute in the data type, but put / get
         !       uses this as short hand for "both Tnonlocal and Snonlocal"
         cvmix_att_name = "kpp_nonlocal_iface"
       case ("Tnonlocal", "KPP_T_Nonlocal", "kpp_Tnonlocal", "kpp_Ttransport", &
             "kpp_Tnonlocal_iface")
         cvmix_att_name = "kpp_Tnonlocal_iface"
       case ("Snonlocal", "KPP_S_Nonlocal", "kpp_Snonlocal", "kpp_Stransport", &
             "kpp_Snonlocal_iface")
         cvmix_att_name = "kpp_Snonlocal_iface"
       ! Variables on level centers
       case ("z","zt","zt_cntr")
         cvmix_att_name = "zt_cntr"
       case ("dz", "dzt", "CellThickness")
         cvmix_att_name = "dzt"
       case ("rho", "dens", "WaterDensity", "WaterDensity_cntr")
         cvmix_att_name = "WaterDensity_cntr"
       case ("rho_lwr", "dens_lwr", "AdiabWaterDensity",                       &
             "AdiabWaterDensity_cntr")
         cvmix_att_name = "AdiabWaterDensity_cntr"
       case ("Rib", "Ri_bulk", "BulkRichardson", "BulkRichardsonNumber",       &
             "BulkRichardson_cntr")
         cvmix_att_name = "BulkRichardson_cntr"
       case ("Rrho", "strat_param")
         ! Note: this isn't an attribute in the data type, but the I/O routines
         !       use it to denote strat_param_num / strat_param_denom
         cvmix_att_name = "strat_param"
       case ("Rrho_num", "strat_param_num")
         cvmix_att_name = "strat_param_num"
       case ("Rrho_denom", "strat_param_denom")
         cvmix_att_name = "strat_param_denom"
       case ("Buoyancy","buoyancy","buoyancy_cntr")
         cvmix_att_name = "buoyancy_cntr"
       case ("U", "Vx", "Vx_cntr")
         cvmix_att_name = "Vx_cntr"
       case ("V", "Vy", "Vy_cntr")
         cvmix_att_name = "Vy_cntr"
       case DEFAULT
         print*, "ERROR: ", trim(varname), " is not tied to an attribute of",  &
                 "the cvmix_data_type structure."
         stop 1
     end select
 !EOC
subroutine, public cvmix_utils::cvmix_update_wrap (integer, intent(in) old_vals, integer, intent(in) nlev, real(cvmix_r8), dimension(nlev+1), intent(inout), optional Mdiff_out, real(cvmix_r8), dimension(nlev+1), intent(in), optional new_Mdiff, real(cvmix_r8), dimension(nlev+1), intent(inout), optional Tdiff_out, real(cvmix_r8), dimension(nlev+1), intent(in), optional new_Tdiff, real(cvmix_r8), dimension(nlev+1), intent(inout), optional Sdiff_out, real(cvmix_r8), dimension(nlev+1), intent(in), optional new_Sdiff)
Definition at line 47 of file cvmix_utils.F90.
References cvmix_kinds_and_types::cvmix_max_old_and_new_vals, cvmix_kinds_and_types::cvmix_overwrite_old_val, and cvmix_kinds_and_types::cvmix_sum_old_and_new_vals.
Referenced by cvmix_background::cvmix_coeffs_bkgnd_wrap(), cvmix_convection::cvmix_coeffs_conv_wrap(), cvmix_ddiff::cvmix_coeffs_ddiff_wrap(), cvmix_kpp::cvmix_coeffs_kpp_wrap(), cvmix_shear::cvmix_coeffs_shear_wrap(), and cvmix_tidal::cvmix_coeffs_tidal_wrap().
 ! !DESCRIPTION:
 !  Update diffusivity values based on \verb|old_vals| (either overwrite, sum, or find
 !  the level-by-level max)
 !\\
 !\\
 ! !USES:
 !  Only those used by entire module.
 ! !INPUT PARAMETERS:
     integer, intent(in) :: old_vals, nlev
     real(cvmix_r8), dimension(nlev+1), optional, intent(in) :: new_mdiff,     &
                                                                new_tdiff,     &
                                                                new_sdiff
 ! !OUTPUT PARAMETERS:
     real(cvmix_r8), dimension(nlev+1), optional, intent(inout) :: mdiff_out,  &
                                                                   tdiff_out,  &
                                                                   sdiff_out
 !EOP
 !BOC
     integer :: kw
     select case (old_vals)
       case (cvmix_sum_old_and_new_vals)
         if ((present(mdiff_out)).and.(present(new_mdiff))) &
           mdiff_out = mdiff_out + new_mdiff
         if ((present(tdiff_out)).and.(present(new_tdiff))) &
           tdiff_out = tdiff_out + new_tdiff
         if ((present(sdiff_out)).and.(present(new_sdiff))) &
           sdiff_out = sdiff_out + new_sdiff
       case (cvmix_max_old_and_new_vals)
         do kw=1,nlev+1
           if ((present(mdiff_out)).and.(present(new_mdiff))) &
             mdiff_out(kw) = max(mdiff_out(kw), new_mdiff(kw))
           if ((present(tdiff_out)).and.(present(new_tdiff))) &
             tdiff_out(kw) = max(tdiff_out(kw), new_tdiff(kw))
           if ((present(sdiff_out)).and.(present(new_sdiff))) &
             sdiff_out(kw) = max(sdiff_out(kw), new_sdiff(kw))
         end do
       case (cvmix_overwrite_old_val)
         if ((present(mdiff_out)).and.(present(new_mdiff))) &
           mdiff_out = new_mdiff
         if ((present(tdiff_out)).and.(present(new_tdiff))) &
           tdiff_out = new_tdiff
         if ((present(sdiff_out)).and.(present(new_sdiff))) &
           sdiff_out = new_sdiff
       case DEFAULT
         print*, "ERROR: do not know how to handle old values!"
         stop 1
     end select
 !EOC