MOM6: mom_string_functions Module Reference
mom_string_functions Module Reference
Functions/Subroutines
character(len=len(input_string)) function, public lowercase (input_string)
character(len=len(input_string)) function, public uppercase (input_string)
character(len=19) function, public left_int (i)
character(len=1320) function, public left_ints (i)
character(len=32) function, public left_real (val)
character(len=1320) function, public left_reals (r, sep)
logical function isformattedfloatequalto (str, val)
character(len=120) function, public extractword (string, n)
logical function, public stringfunctionsunittests ()
character(len=len(dir)+2) function, public slasher (dir)
Function/Subroutine Documentation
character(len=120) function, public mom_string_functions::extractword (character(len=*), intent(in) string, integer, intent(in) n)
Definition at line 210 of file MOM_string_functions.F90.
Referenced by mom_ale::ale_initregridding(), and stringfunctionsunittests().
 ! Returns string corresponding to the nth word in the argument
 ! or "" if the string is not long enough. Both spaces and commas
 ! are interpretted as separators.
   character(len=*), intent(in) :: string
   integer,          intent(in) :: n
   character(len=120) :: extractword
   ! Local variables
   integer :: ns, i, b, e, nw
   logical :: lastcharisseperator
   extractword = ''
   lastcharisseperator = .true.
   ns = len_trim(string)
   i = 0; b=0; e=0; nw=0;
   do while (i<ns)
     i = i+1
     if (lastcharisseperator) then ! search for end of word
       if (string(i:i)==' ' .or. string(i:i)==',') then
         continue ! Multiple separators, .e.g '  ' or ', '
       else
         lastcharisseperator = .false. ! character is beginning of word
         b = i
         continue
       endif
     else ! continue search for end of word
       if (string(i:i)==' ' .or. string(i:i)==',') then
         lastcharisseperator = .true.
         e = i-1 ! Previous character is end of word
         nw = nw+1
         if (nw==n) then
           extractword = trim(string(b:e))
           return
         endif
       endif
     endif
   enddo
   if (b<=ns) extractword = trim(string(b:ns))
logical function mom_string_functions::isformattedfloatequalto (character(len=*), intent(in) str, real, intent(in) val) private
Definition at line 195 of file MOM_string_functions.F90.
Referenced by left_real().
 ! Returns True if the string can be read/parsed to give the exact
 ! value of "val"
   character(len=*), intent(in) :: str
   real,             intent(in) :: val
   logical                      :: isformattedfloatequalto
   ! Local variables
   real :: scannedval
   isformattedfloatequalto=.false.
   read(str(1:),*,err=987) scannedval
   if (scannedval == val) isformattedfloatequalto=.true.
  987 return
character(len=19) function, public mom_string_functions::left_int (integer, intent(in) i)
Definition at line 79 of file MOM_string_functions.F90.
Referenced by left_ints(), left_reals(), and stringfunctionsunittests().
 ! Returns a character string of a left-formatted integer
 ! e.g. "123       "  (assumes 19 digit maximum)
   ! Arguments
   character(len=19) :: left_int
   integer, intent(in) :: i
   ! Local variables
   character(len=19) :: tmp
   write(tmp(1:19),'(I19)') i
   write(left_int(1:19),'(A)') adjustl(tmp)
character(len=1320) function, public mom_string_functions::left_ints (integer, dimension(:), intent(in) i)
Definition at line 91 of file MOM_string_functions.F90.
References left_int().
Referenced by stringfunctionsunittests().
 ! Returns a character string of a comma-separated, compact formatted,
 ! integers  e.g. "1, 2, 3, 4"
   ! Arguments
   character(len=1320) :: left_ints
   integer, intent(in) :: i(:)
   ! Local variables
   character(len=1320) :: tmp
   integer :: j
   write(left_ints(1:1320),'(A)') trim(left_int(i(1)))
   if (size(i)>1) then
     do j=2,size(i)
       tmp=left_ints
       write(left_ints(1:1320),'(A,", ",A)') trim(tmp),trim(left_int(i(j)))
     enddo
   endif
character(len=32) function, public mom_string_functions::left_real (real, intent(in) val)
Definition at line 109 of file MOM_string_functions.F90.
References isformattedfloatequalto().
Referenced by left_reals(), mom_file_parser::log_param_real(), and stringfunctionsunittests().
   real, intent(in)  :: val
   character(len=32) :: left_real
 ! Returns a left-justified string with a real formatted like '(G)'
   integer :: l, ind
   if ((abs(val) < 1.0e4) .and. (abs(val) >= 1.0e-3)) then
     write(left_real, '(F30.11)') val
     if (.not.isformattedfloatequalto(left_real,val)) then
       write(left_real, '(F30.12)') val
       if (.not.isformattedfloatequalto(left_real,val)) then
         write(left_real, '(F30.13)') val
         if (.not.isformattedfloatequalto(left_real,val)) then
           write(left_real, '(F30.14)') val
           if (.not.isformattedfloatequalto(left_real,val)) then
             write(left_real, '(F30.15)') val
             if (.not.isformattedfloatequalto(left_real,val)) then
               write(left_real, '(F30.16)') val
             endif
           endif
         endif
       endif
     endif
     do
       l = len_trim(left_real)
       if ((l<2) .or. (left_real(l-1:l) == ".0") .or. &
           (left_real(l:l) /= "0")) exit
       left_real(l:l) = " "
     enddo
   elseif (val == 0.) then
     left_real = "0.0"
   else
     write(left_real(1:32), '(ES23.14)') val
     if (.not.isformattedfloatequalto(left_real,val)) then
      write(left_real(1:32), '(ES23.15)') val
     endif
     do
       ind = index(left_real,"0E")
       if (ind == 0) exit
       if (left_real(ind-1:ind-1) == ".") exit
       left_real = left_real(1:ind-1)//left_real(ind+1:)
     enddo
   endif
   left_real = adjustl(left_real)
character(len=1320) function, public mom_string_functions::left_reals (real, dimension(:), intent(in) r, character(len=*), optional sep)
Definition at line 155 of file MOM_string_functions.F90.
References left_int(), and left_real().
Referenced by mom_file_parser::log_param_real_array(), and stringfunctionsunittests().
 ! Returns a character string of a comma-separated, compact formatted, reals
 ! e.g. "1., 2., 5*3., 5.E2"
   ! Arguments
   character(len=1320) :: left_reals
   real, intent(in) :: r(:)
   character(len=*), optional :: sep
   ! Local variables
   integer :: j, n, b, ns
   logical :: dowrite
   character(len=10) :: separator
   n=1 ; dowrite=.true. ; left_reals='' ; b=1
   if (present(sep)) then
     separator=sep ; ns=len(sep)
   else
     separator=', ' ; ns=2
   endif
   do j=1,size(r)
     dowrite=.true.
     if (j<size(r)) then
       if (r(j)==r(j+1)) then
         n=n+1
         dowrite=.false.
       endif
     endif
     if (dowrite) then
       if (b>1) then ! Write separator if a number has already been written
         write(left_reals(b:),'(A)') separator
         b=b+ns
       endif
       if (n>1) then
         write(left_reals(b:),'(A,"*",A)') trim(left_int(n)),trim(left_real(r(j)))
       else
         write(left_reals(b:),'(A)') trim(left_real(r(j)))
       endif
       n=1 ; b=len_trim(left_reals)+1
     endif
   enddo
character(len=len(input_string)) function, public mom_string_functions::lowercase (character(len=*), intent(in) input_string)
Definition at line 44 of file MOM_string_functions.F90.
Referenced by mom_io::num_timelevels(), and mom_restart::restore_state().
 !   This function returns a string in which all uppercase letters have been
 ! replaced by their lowercase counterparts.  It is loosely based on the
 ! lowercase function in mpp_util.F90.
   ! Arguments
   character(len=*),     intent(in) :: input_string
   character(len=len(input_string)) :: lowercase
   ! Local variables
   integer, parameter :: co=iachar('a')-iachar('A') ! case offset
   integer :: k
   lowercase = input_string
   do k=1, len_trim(input_string)
     if (lowercase(k:k) >= 'A' .and. lowercase(k:k) <= 'Z') &
         lowercase(k:k) = achar(ichar(lowercase(k:k))+co)
   end do
character(len=len(dir)+2) function, public mom_string_functions::slasher (character(len=*), intent(in) dir)
Definition at line 277 of file MOM_string_functions.F90.
Referenced by mom_domains::mom_domains_init().
   character(len=*), intent(in) :: dir
   character(len=len(dir)+2) :: slasher
   if (len_trim(dir) == 0) then
     slasher = "./"
   elseif (dir(len_trim(dir):len_trim(dir)) == '/') then
     slasher = trim(dir)
   else
     slasher = trim(dir)//"/"
   endif
logical function, public mom_string_functions::stringfunctionsunittests ()
Definition at line 249 of file MOM_string_functions.F90.
References extractword(), left_int(), left_ints(), left_real(), left_reals(), and localtest().
Referenced by localtest(), and mom::unittests().
   ! Should only be called from a single/root thread
   ! Returns True is a test fails, otherwise False
   integer :: i(5) = (/ -1, 1, 3, 3, 0 /)
   real :: r(8) = (/ 0., 1., -2., 1.3, 3.e-11, 3.e-11, 3.e-11, -5.1e12 /)
   stringfunctionsunittests = .false.
   write(*,*) '===== MOM_string_functions: stringFunctionsUnitTests ====='
   call localtest(left_int(i(1)),'-1')
   call localtest(left_ints(i(:)),'-1, 1, 3, 3, 0')
   call localtest(left_real(r(1)),'0.0')
   call localtest(left_reals(r(:)),'0.0, 1.0, -2.0, 1.3, 3*3.0E-11, -5.1E+12')
   call localtest(left_reals(r(:),sep=' '),'0.0 1.0 -2.0 1.3 3*3.0E-11 -5.1E+12')
   call localtest(left_reals(r(:),sep=','),'0.0,1.0,-2.0,1.3,3*3.0E-11,-5.1E+12')
   call localtest(extractword("One Two,Three",1),"One")
   call localtest(extractword("One Two,Three",2),"Two")
   call localtest(extractword("One Two,Three",3),"Three")
   call localtest(extractword("One Two,  Three",3),"Three")
   call localtest(extractword(" One Two,Three",1),"One")
   write(*,*) '=========================================================='
   contains
   subroutine localtest(str1,str2)
     character(len=*) :: str1, str2
     write(*,*) '>'//trim(str1)//'<'
     if (trim(str1)/=trim(str2)) write(*,*) 'FAIL:',trim(str1),':',trim(str2)
     if (trim(str1)/=trim(str2)) stringfunctionsunittests=.true.
   end subroutine localtest
character(len=len(input_string)) function, public mom_string_functions::uppercase (character(len=*), intent(in) input_string)
Definition at line 62 of file MOM_string_functions.F90.
Referenced by mom_continuity::continuity_init(), regrid_consts::coordinatemode(), mom_coriolisadv::coriolisadv_init(), mom_eos::eos_init(), mom_regridding::initialize_regridding(), ocean_model_mod::ocean_model_init(), mom_fixed_initialization::read_face_length_list(), mom_fixed_initialization::reset_face_lengths_list(), mom_remapping::setreconstructiontype(), mom_surface_forcing::wind_forcing_const(), and mom_surface_forcing::wind_forcing_from_file().
   character(len=*),     intent(in) :: input_string
   character(len=len(input_string)) :: uppercase
 !   This function returns a string in which all lowercase letters have been
 ! replaced by their uppercase counterparts.  It is loosely based on the
 ! uppercase function in mpp_util.F90.
   ! Arguments
   integer, parameter :: co=iachar('A')-iachar('a') ! case offset
   integer :: k
   uppercase = input_string
   do k=1, len_trim(input_string)
     if (uppercase(k:k) >= 'a' .and. uppercase(k:k) <= 'z') &
         uppercase(k:k) = achar(ichar(uppercase(k:k))+co)
   end do