MOM6: cvmix_ddiff Module Reference
cvmix_ddiff Module Reference
Data Types
interface cvmix_coeffs_ddiff
type cvmix_ddiff_params_type
interface cvmix_put_ddiff
Functions/Subroutines
subroutine, public cvmix_init_ddiff (CVmix_ddiff_params_user, strat_param_max, kappa_ddiff_s, ddiff_exp1, ddiff_exp2, mol_diff, kappa_ddiff_param1, kappa_ddiff_param2, kappa_ddiff_param3, diff_conv_type, old_vals)
subroutine cvmix_coeffs_ddiff_wrap (CVmix_vars, CVmix_ddiff_params_user)
subroutine cvmix_coeffs_ddiff_low (Tdiff_out, Sdiff_out, strat_param_num, strat_param_denom, nlev, max_nlev, CVmix_ddiff_params_user)
subroutine cvmix_put_ddiff_str (varname, val, CVmix_ddiff_params_user)
subroutine cvmix_put_ddiff_real (varname, val, CVmix_ddiff_params_user)
subroutine cvmix_put_ddiff_int (varname, val, CVmix_ddiff_params_user)
real(cvmix_r8) function, public cvmix_get_ddiff_real (varname, CVmix_ddiff_params_user)
Variables
type(cvmix_ddiff_params_type), target cvmix_ddiff_params_saved
Function/Subroutine Documentation
subroutine cvmix_ddiff::cvmix_coeffs_ddiff_low (real(cvmix_r8), dimension(max_nlev+1), intent(inout) Tdiff_out, real(cvmix_r8), dimension(max_nlev+1), intent(inout) Sdiff_out, real(cvmix_r8), dimension(max_nlev), intent(in) strat_param_num, real(cvmix_r8), dimension(max_nlev), intent(in) strat_param_denom, integer, intent(in) nlev, integer, intent(in) max_nlev, type(cvmix_ddiff_params_type), intent(in), optional, target CVmix_ddiff_params_user) private
Definition at line 358 of file cvmix_ddiff.F90.
References cvmix_ddiff_params_saved, cvmix_kinds_and_types::cvmix_one, and cvmix_kinds_and_types::cvmix_zero.
 ! !DESCRIPTION:
 !  Computes vertical diffusion coefficients for the double diffusion mixing
 !  parameterization.
 !\\
 !\\
 !
 ! !USES:
 !  only those used by entire module.
 ! !INPUT PARAMETERS:
     type(cvmix_ddiff_params_type), optional, target, intent(in) ::            &
                                            cvmix_ddiff_params_user
     integer,                             intent(in) :: nlev, max_nlev
     real(cvmix_r8), dimension(max_nlev), intent(in) :: strat_param_num,       &
                                                        strat_param_denom
 ! !INPUT/OUTPUT PARAMETERS:
     real(cvmix_r8), dimension(max_nlev+1), intent(inout) :: tdiff_out,        &
                                                             sdiff_out
 ! !LOCAL VARIABLES:
     integer :: k
     real(cvmix_r8) :: ddiff, rrho
 !EOP
 !BOC
     type(cvmix_ddiff_params_type), pointer :: cvmix_ddiff_params_in
     if (present(cvmix_ddiff_params_user)) then
       cvmix_ddiff_params_in => cvmix_ddiff_params_user
     else
       cvmix_ddiff_params_in => cvmix_ddiff_params_saved
     end if
     ! Determine coefficients
     tdiff_out=cvmix_zero
     sdiff_out=cvmix_zero
     do k = 1, nlev
       if ((strat_param_num(k).ge.strat_param_denom(k)).and.                   &
           (strat_param_denom(k).gt.cvmix_zero)) then
         ! Rrho > 1 and dS/dz < 0 => Salt fingering
         rrho = strat_param_num(k) / strat_param_denom(k)
         if (rrho.lt.cvmix_ddiff_params_in%strat_param_max) then
           ddiff = (cvmix_one - ((rrho-cvmix_one)/                             &
                   (cvmix_ddiff_params_in%strat_param_max-cvmix_one))**        &
             cvmix_ddiff_params_in%ddiff_exp1)**cvmix_ddiff_params_in%ddiff_exp2
           sdiff_out(k) = cvmix_ddiff_params_in%kappa_ddiff_s*ddiff
         end if
         tdiff_out = sdiff_out*0.7_cvmix_r8
       end if
       if ((strat_param_num(k).ge.strat_param_denom(k)).and.                   &
           (strat_param_num(k).lt.cvmix_zero)) then
         ! Rrho < 1 and dT/dz > 0 => Diffusive convection
         rrho = strat_param_num(k) / strat_param_denom(k)
         select case (trim(cvmix_ddiff_params_in%diff_conv_type))
           case ("MC76")
             ddiff = cvmix_ddiff_params_in%mol_diff *                          &
                     cvmix_ddiff_params_in%kappa_ddiff_param1 *                &
                     exp(cvmix_ddiff_params_in%kappa_ddiff_param2*exp(         &
                         cvmix_ddiff_params_in%kappa_ddiff_param3*             &
                         (cvmix_one/rrho-cvmix_one)))
           case ("K88")
             ddiff = cvmix_ddiff_params_in%mol_diff * 8.7_cvmix_r8 *           &
                     (rrho**1.1_cvmix_r8)
           case DEFAULT
             print*, "ERROR: ", trim(cvmix_ddiff_params_in%diff_conv_type),    &
                     " is not a valid value for diff_conv_type"
             stop 1
         end select
         tdiff_out(k) = ddiff
         if (rrho.lt.0.5_cvmix_r8) then
           sdiff_out(k) = 0.15_cvmix_r8*rrho*ddiff
         else
           sdiff_out(k) = (1.85_cvmix_r8*rrho-0.85_cvmix_r8)*ddiff
         end if
       end if
     end do
     tdiff_out(nlev+1) = cvmix_zero
     sdiff_out(nlev+1) = cvmix_zero
 !EOC
subroutine cvmix_ddiff::cvmix_coeffs_ddiff_wrap (type(cvmix_data_type), intent(inout) CVmix_vars, type(cvmix_ddiff_params_type), intent(in), optional, target CVmix_ddiff_params_user) private
Definition at line 300 of file cvmix_ddiff.F90.
References cvmix_ddiff_params_saved, cvmix_utils::cvmix_update_wrap(), and cvmix_kinds_and_types::cvmix_zero.
 ! !DESCRIPTION:
 !  Computes vertical diffusion coefficients for the double diffusion mixing
 !  parameterization.
 !\\
 !\\
 !
 ! !USES:
 !  only those used by entire module.
 ! !INPUT PARAMETERS:
     type(cvmix_ddiff_params_type), optional, target, intent(in) ::            &
                                            cvmix_ddiff_params_user
 ! !INPUT/OUTPUT PARAMETERS:
     type(cvmix_data_type), intent(inout) :: cvmix_vars
 !EOP
 !BOC
     real(cvmix_r8), dimension(CVmix_vars%max_nlev+1) :: new_tdiff, new_sdiff
     integer :: nlev, max_nlev
     type(cvmix_ddiff_params_type), pointer :: cvmix_ddiff_params_in
     if (present(cvmix_ddiff_params_user)) then
       cvmix_ddiff_params_in => cvmix_ddiff_params_user
     else
       cvmix_ddiff_params_in => cvmix_ddiff_params_saved
     end if
     nlev = cvmix_vars%nlev
     max_nlev = cvmix_vars%max_nlev
     if (.not.associated(cvmix_vars%Tdiff_iface)) &
       call cvmix_put(cvmix_vars, "Tdiff", cvmix_zero, max_nlev)
     if (.not.associated(cvmix_vars%Sdiff_iface)) &
       call cvmix_put(cvmix_vars, "Sdiff", cvmix_zero, max_nlev)
     call cvmix_coeffs_ddiff(new_tdiff, new_sdiff, cvmix_vars%strat_param_num, &
                             cvmix_vars%strat_param_denom, nlev, max_nlev,     &
                             cvmix_ddiff_params_user)
     call cvmix_update_wrap(cvmix_ddiff_params_in%handle_old_vals, max_nlev,   &
                            tdiff_out = cvmix_vars%Tdiff_iface,                &
                            new_tdiff = new_tdiff,                             &
                            sdiff_out = cvmix_vars%Sdiff_iface,                &
                            new_sdiff = new_sdiff)
 !EOC
real(cvmix_r8) function, public cvmix_ddiff::cvmix_get_ddiff_real (character(len=*), intent(in) varname, type(cvmix_ddiff_params_type), intent(inout), optional, target CVmix_ddiff_params_user)
Definition at line 611 of file cvmix_ddiff.F90.
References cvmix_ddiff_params_saved, and cvmix_kinds_and_types::cvmix_zero.
 ! !DESCRIPTION:
 !  Return the real value of a cvmix\_ddiff\_params\_type variable.
 !  NOTE: This function is not efficient and is only for infrequent
 !  queries of ddiff parameters, such as at initialization.
 !\\
 !\\
 ! !USES:
 !  Only those used by entire module.
 ! !INPUT PARAMETERS:
     character(len=*),                                intent(in)    :: varname
     type(cvmix_ddiff_params_type), optional, target, intent(inout) ::         &
                                               cvmix_ddiff_params_user
 ! !OUTPUT PARAMETERS:
     real(cvmix_r8) :: cvmix_get_ddiff_real
 !EOP
 !BOC
     type(cvmix_ddiff_params_type), pointer :: cvmix_ddiff_params_get
     if (present(cvmix_ddiff_params_user)) then
       cvmix_ddiff_params_get => cvmix_ddiff_params_user
     else
       cvmix_ddiff_params_get => cvmix_ddiff_params_saved
     end if
     cvmix_get_ddiff_real = cvmix_zero
     select case (trim(varname))
       case ('strat_param_max')
         cvmix_get_ddiff_real = cvmix_ddiff_params_get%strat_param_max
       case ('ddiff_exp1')
         cvmix_get_ddiff_real = cvmix_ddiff_params_get%ddiff_exp1
       case ('ddiff_exp2')
         cvmix_get_ddiff_real = cvmix_ddiff_params_get%ddiff_exp2
       case ('kappa_ddiff_param1')
         cvmix_get_ddiff_real = cvmix_ddiff_params_get%kappa_ddiff_param1
       case ('kappa_ddiff_param2')
         cvmix_get_ddiff_real = cvmix_ddiff_params_get%kappa_ddiff_param2
       case ('kappa_ddiff_param3')
         cvmix_get_ddiff_real = cvmix_ddiff_params_get%kappa_ddiff_param3
       case ('kappa_ddiff_s')
         cvmix_get_ddiff_real = cvmix_ddiff_params_get%kappa_ddiff_s
       case ('mol_diff')
         cvmix_get_ddiff_real = cvmix_ddiff_params_get%mol_diff
       case DEFAULT
         print*, "ERROR: ", trim(varname), " not a valid choice!"
         stop 1
     end select
 !EOC
subroutine, public cvmix_ddiff::cvmix_init_ddiff (type(cvmix_ddiff_params_type), intent(inout), optional, target CVmix_ddiff_params_user, real(cvmix_r8), intent(in), optional strat_param_max, real(cvmix_r8), intent(in), optional kappa_ddiff_s, real(cvmix_r8), intent(in), optional ddiff_exp1, real(cvmix_r8), intent(in), optional ddiff_exp2, real(cvmix_r8), intent(in), optional mol_diff, real(cvmix_r8), intent(in), optional kappa_ddiff_param1, real(cvmix_r8), intent(in), optional kappa_ddiff_param2, real(cvmix_r8), intent(in), optional kappa_ddiff_param3, character(len=*), intent(in), optional diff_conv_type, character(len=*), intent(in), optional old_vals)
Definition at line 130 of file cvmix_ddiff.F90.
References cvmix_kinds_and_types::cvmix_max_old_and_new_vals, cvmix_kinds_and_types::cvmix_one, cvmix_kinds_and_types::cvmix_overwrite_old_val, and cvmix_kinds_and_types::cvmix_sum_old_and_new_vals.
 ! !DESCRIPTION:
 !  Initialization routine for double diffusion mixing. This mixing technique
 !  looks for two unstable cases in a column - salty water over fresher
 !  water and colder water over warmer water - and computes different
 !  diffusivity coefficients in each of these two locations. The parameter
 !  \begin{eqnarray*}
 !  R_\rho = \frac{\alpha (\partial \Theta / \partial z)}
 !                {\beta (\partial S / \partial z)}
 !  \end{eqnarray*}
 !  to determine as a stratification parameter. If $(\partial S / \partial z)$
 !  is positive and $1 < R_\rho < R_\rho^0$ then salt water sits on top
 !  of fresh water and the diffusivity is given by
 !  \begin{eqnarray*}
 !  \kappa = \kappa^0 \left[ 1 - \left(\frac{R_\rho - 1}{R_\rho^0 - 1} \right)^{p_1}\right]^{p_2}
 !  \end{eqnarray*}
 !  By default, $R_\rho^0 = 2.55$, but that can be changed by setting
 !  \verb|strat_param_max| in the code. Similarly, by default $p_1 = 1$
 ! (\verb|ddiff_exp1|), $p_2 = 3$ (\verb|ddiff_exp2|), and
 !  \begin{eqnarray*}
 !  \kappa^0 = \left\{ \begin{array}{r l}
 !             7 \cdot 10^{-5}\ \textrm{m}^2\textrm{/s} & \textrm{for temperature}
 !             \ (0.7 \cdot \verb|kappa_ddiff_s|\ \textrm{in this routine})\\
 !             10^{-4}\ \textrm{m}^2\textrm{/s} & \textrm{for salinity and other tracers}
 !             \ (\verb|kappa_ddiff_s|\ \textrm{in this routine}).
 !                     \end{array} \right.
 !  \end{eqnarray*}
 !  On the other hand, if $(\partial \Theta / \partial z)$ is negative and
 !  $0 < R_\rho < 1$ then cold water sits on warm warm water and the
 !  diffusivity for temperature is given by
 !  \begin{eqnarray*}
 !  \kappa = \nu_\textrm{molecular} \cdot 0.909\exp\left\{ 4.6\exp\left[
 !           -0.54\left( \frac{1}{R_\rho} - 1 \right) \right] \right\}
 !  \end{eqnarray*}
 !  where $\nu_\textrm{molecular}$ Is the molecular viscosity of water. By default it
 !  is set to $1.5 \cdot 10^{-6}\ \textrm{m}^2\textrm{/s}$, but it can be changed
 !  through \verb|mol_diff| in the code. Similarly, 0.909, 4.6, and -0.54 are the
 !  default values of \verb|kappa_ddiff_param1|, \verb|kappa_ddiff_param2|, and
 !  \verb|kappa_ddiff_param3|, respectively.\\
 !\\
 !  For salinity and other tracers, $\kappa$ above is multiplied by the factor
 !  \begin{eqnarray*}
 !  \textrm{factor} = \left\{ \begin{array}{c l}
 !                    0.15R_\rho & R_\rho < 0.5\\
 !                    1.85R_\rho - 0.85 & 0.5 \le R_\rho < 1\\
 !                     \end{array} \right.
 !  \end{eqnarray*}
 !  $\kappa$ is stored in \verb|CVmix_vars%diff_iface(:,1)|, while the modified value
 !  for non-temperature tracers is stored in \verb|CVmix_vars%diff_iface(:,2)|.
 !  Note that CVMix assumes units are |'mks'|.\\
 !\\
 ! !USES:
 !  Only those used by entire module.
 ! !INPUT PARAMETERS:
     real(cvmix_r8),   optional, intent(in) :: strat_param_max,                &
                                               kappa_ddiff_s,                  &
                                               ddiff_exp1,                     &
                                               ddiff_exp2,                     &
                                               mol_diff,                       &
                                               kappa_ddiff_param1,             &
                                               kappa_ddiff_param2,             &
                                               kappa_ddiff_param3
     character(len=*), optional, intent(in) :: diff_conv_type, old_vals
 ! !OUTPUT PARAMETERS:
     type(cvmix_ddiff_params_type), optional, target, intent(inout) ::         &
                                               cvmix_ddiff_params_user
 !EOP
 !BOC
     ! Unitless parameters
     if (present(strat_param_max)) then
       call cvmix_put_ddiff("strat_param_max", strat_param_max,                 &
                            cvmix_ddiff_params_user)
     else
       call cvmix_put_ddiff("strat_param_max", 2.55_cvmix_r8,                   &
                            cvmix_ddiff_params_user)
     end if
     if (present(diff_conv_type)) then
       call cvmix_put_ddiff("diff_conv_type", diff_conv_type,                  &
                             cvmix_ddiff_params_user)
     else
       call cvmix_put_ddiff("diff_conv_type", "MC76", cvmix_ddiff_params_user)
     end if
     if (present(ddiff_exp1)) then
       call cvmix_put_ddiff("ddiff_exp1", ddiff_exp1, cvmix_ddiff_params_user)
     else
       call cvmix_put_ddiff("ddiff_exp1", cvmix_one, cvmix_ddiff_params_user)
     end if
     if (present(ddiff_exp2)) then
       call cvmix_put_ddiff("ddiff_exp2", ddiff_exp2, cvmix_ddiff_params_user)
     else
       call cvmix_put_ddiff("ddiff_exp2", 3, cvmix_ddiff_params_user)
     end if
     if (present(kappa_ddiff_param1)) then
       call cvmix_put_ddiff("kappa_ddiff_param1", kappa_ddiff_param1,          &
                            cvmix_ddiff_params_user)
     else
       call cvmix_put_ddiff("kappa_ddiff_param1", 0.909_cvmix_r8,              &
                            cvmix_ddiff_params_user)
     end if
     if (present(kappa_ddiff_param2)) then
       call cvmix_put_ddiff("kappa_ddiff_param2", kappa_ddiff_param2,          &
                            cvmix_ddiff_params_user)
     else
       call cvmix_put_ddiff("kappa_ddiff_param2", 4.6_cvmix_r8,                &
                            cvmix_ddiff_params_user)
     end if
     if (present(kappa_ddiff_param3)) then
       call cvmix_put_ddiff("kappa_ddiff_param3", kappa_ddiff_param3,          &
                            cvmix_ddiff_params_user)
     else
       call cvmix_put_ddiff("kappa_ddiff_param3", -0.54_cvmix_r8,              &
                            cvmix_ddiff_params_user)
     end if
     ! Parameters with physical units
     if (present(kappa_ddiff_s)) then
       call cvmix_put_ddiff("kappa_ddiff_s", kappa_ddiff_s,                    &
                            cvmix_ddiff_params_user)
     else
       call cvmix_put_ddiff("kappa_ddiff_s", 1e-4_cvmix_r8,                    &
                            cvmix_ddiff_params_user)
     end if
     if (present(mol_diff)) then
       call cvmix_put_ddiff("mol_diff", mol_diff, cvmix_ddiff_params_user)
     else
       call cvmix_put_ddiff("mol_diff", 1.5e-6_cvmix_r8,                       &
                            cvmix_ddiff_params_user)
     end if
     if (present(old_vals)) then
       select case (trim(old_vals))
         case ("overwrite")
           call cvmix_put_ddiff('handle_old_vals', cvmix_overwrite_old_val,    &
                                cvmix_ddiff_params_user)
         case ("sum")
           call cvmix_put_ddiff('handle_old_vals', cvmix_sum_old_and_new_vals, &
                                cvmix_ddiff_params_user)
         case ("max")
           call cvmix_put_ddiff('handle_old_vals', cvmix_max_old_and_new_vals, &
                                cvmix_ddiff_params_user)
         case DEFAULT
           print*, "ERROR: ", trim(old_vals), " is not a valid option for ",   &
                   "handling old values of diff and visc."
           stop 1
       end select
     else
       call cvmix_put_ddiff('handle_old_vals', cvmix_overwrite_old_val,        &
                                cvmix_ddiff_params_user)
     end if
 !EOC
subroutine cvmix_ddiff::cvmix_put_ddiff_int (character(len=*), intent(in) varname, integer, intent(in) val, type(cvmix_ddiff_params_type), intent(inout), optional, target CVmix_ddiff_params_user) private
Definition at line 565 of file cvmix_ddiff.F90.
References cvmix_ddiff_params_saved.
 ! !DESCRIPTION:
 !  Write an integer value into a cvmix\_ddiff\_params\_type variable.
 !\\
 !\\
 ! !USES:
 !  Only those used by entire module.
 ! !INPUT PARAMETERS:
     character(len=*), intent(in) :: varname
     integer,          intent(in) :: val
 ! !OUTPUT PARAMETERS:
     type(cvmix_ddiff_params_type), optional, target, intent(inout) ::         &
                                               cvmix_ddiff_params_user
 !EOP
 !BOC
     type(cvmix_ddiff_params_type), pointer :: cvmix_ddiff_params_out
     if (present(cvmix_ddiff_params_user)) then
       cvmix_ddiff_params_out => cvmix_ddiff_params_user
     else
       cvmix_ddiff_params_out => cvmix_ddiff_params_saved
     end if
     select case (trim(varname))
       case ('old_vals', 'handle_old_vals')
         cvmix_ddiff_params_out%handle_old_vals = val
       case DEFAULT
         call cvmix_put_ddiff(varname, real(val,cvmix_r8),                     &
                              cvmix_ddiff_params_user)
     end select
 !EOC
subroutine cvmix_ddiff::cvmix_put_ddiff_real (character(len=*), intent(in) varname, real(cvmix_r8), intent(in) val, type(cvmix_ddiff_params_type), intent(inout), optional, target CVmix_ddiff_params_user) private
Definition at line 505 of file cvmix_ddiff.F90.
References cvmix_ddiff_params_saved.
 ! !DESCRIPTION:
 !  Write a real value into a cvmix\_ddiff\_params\_type variable.
 !\\
 !\\
 ! !USES:
 !  Only those used by entire module.
 ! !INPUT PARAMETERS:
     character(len=*), intent(in) :: varname
     real(cvmix_r8),   intent(in) :: val
 ! !OUTPUT PARAMETERS:
     type(cvmix_ddiff_params_type), optional, target, intent(inout) ::         &
                                               cvmix_ddiff_params_user
 !EOP
 !BOC
     type(cvmix_ddiff_params_type), pointer :: cvmix_ddiff_params_out
     if (present(cvmix_ddiff_params_user)) then
       cvmix_ddiff_params_out => cvmix_ddiff_params_user
     else
       cvmix_ddiff_params_out => cvmix_ddiff_params_saved
     end if
     select case (trim(varname))
       case ('strat_param_max')
         cvmix_ddiff_params_out%strat_param_max = val
       case ('ddiff_exp1')
         cvmix_ddiff_params_out%ddiff_exp1 = val
       case ('ddiff_exp2')
         cvmix_ddiff_params_out%ddiff_exp2 = val
       case ('kappa_ddiff_param1')
         cvmix_ddiff_params_out%kappa_ddiff_param1 = val
       case ('kappa_ddiff_param2')
         cvmix_ddiff_params_out%kappa_ddiff_param2 = val
       case ('kappa_ddiff_param3')
         cvmix_ddiff_params_out%kappa_ddiff_param3 = val
       case ('kappa_ddiff_s')
         cvmix_ddiff_params_out%kappa_ddiff_s = val
       case ('mol_diff')
         cvmix_ddiff_params_out%mol_diff = val
       case DEFAULT
         print*, "ERROR: ", trim(varname), " not a valid choice!"
         stop 1
     end select
 !EOC
subroutine cvmix_ddiff::cvmix_put_ddiff_str (character(len=*), intent(in) varname, character(len=*), intent(in) val, type(cvmix_ddiff_params_type), intent(inout), optional, target CVmix_ddiff_params_user) private
Definition at line 450 of file cvmix_ddiff.F90.
References cvmix_ddiff_params_saved.
 ! !DESCRIPTION:
 !  Write a string value into a cvmix\_ddiff\_params\_type variable.
 !\\
 !\\
 ! !USES:
 !  Only those used by entire module.
 ! !INPUT PARAMETERS:
     character(len=*), intent(in) :: varname, val
 ! !OUTPUT PARAMETERS:
     type(cvmix_ddiff_params_type), optional, target, intent(inout) ::         &
                                               cvmix_ddiff_params_user
 !EOP
 !BOC
     type(cvmix_ddiff_params_type), pointer :: cvmix_ddiff_params_out
     if (present(cvmix_ddiff_params_user)) then
       cvmix_ddiff_params_out => cvmix_ddiff_params_user
     else
       cvmix_ddiff_params_out => cvmix_ddiff_params_saved
     end if
     select case (trim(varname))
       case ('diff_conv_type')
         select case (trim(val))
           case ('MC76')
             cvmix_ddiff_params_out%diff_conv_type = 'MC76'
           case ('K88')
             cvmix_ddiff_params_out%diff_conv_type = 'K88'
           case DEFAULT
             print*, "ERROR: ", trim(val),                                     &
                     " is not a valid value for diff_conv_type"
             stop 1
         end select
       case DEFAULT
         print*, "ERROR: ", trim(varname), " not a valid choice!"
         stop 1
     end select
 !EOC
Variable Documentation
type(cvmix_ddiff_params_type), target cvmix_ddiff::cvmix_ddiff_params_saved
Definition at line 117 of file cvmix_ddiff.F90.
Referenced by cvmix_coeffs_ddiff_low(), cvmix_coeffs_ddiff_wrap(), cvmix_get_ddiff_real(), cvmix_put_ddiff_int(), cvmix_put_ddiff_real(), and cvmix_put_ddiff_str().
   type(cvmix_ddiff_params_type), target :: cvmix_ddiff_params_saved