MOM6: mom_regridding Module Reference
mom_regridding Module Reference
Generates vertical grids as part of the ALE algorithm.
Data Types
type regridding_cs
Regridding control structure.
Functions/Subroutines
subroutine, public initialize_regridding (nk, coordMode, interpScheme, CS, compressibility_fraction)
Initialization of regridding.
subroutine, public end_regridding (CS)
Deallocation of regridding memory.
subroutine, public regridding_main (remapCS, CS, G, GV, h, tv, h_new, dzInterface)
subroutine calc_h_new_by_dz (G, GV, h, dzInterface, h_new)
Calculates h_new from h + delta_k dzInterface.
subroutine, public check_remapping_grid (G, GV, h, dzInterface, msg)
Check that the total thickness of two grids match.
subroutine, public check_grid_column (nk, depth, h, dzInterface, msg)
Check that the total thickness of new and old grids are consistent.
subroutine filtered_grid_motion (CS, nk, z_old, z_new, dz_g)
Returns the change in interface position motion after filtering and assuming the top and bottom interfaces do not move. The filtering is a function of depth, and is applied as the integrated average filtering over the trajectory of the interface. By design, this code can not give tangled interfaces provided that z_old and z_new are not already tangled.
subroutine build_zstar_grid (CS, G, GV, h, dzInterface)
Builds a z*-ccordinate grid with partial steps (Adcroft and Campin, 2004). z* is defined as z* = (z-eta)/(H+eta)*H s.t. z*=0 when z=eta and z*=-H when z=-H .
subroutine, public build_zstar_column (CS, nz, depth, total_thickness, zInterface, z_rigid_top, eta_orig)
Builds a z* coordinate with a minimum thickness.
subroutine build_sigma_grid (CS, G, GV, h, dzInterface)
subroutine build_rho_grid (G, GV, h, tv, dzInterface, remapCS, CS)
subroutine build_grid_hycom1 (G, GV, h, tv, dzInterface, remapCS, CS)
Builds a simple HyCOM-like grid with the deepest location of potential density interpolated from the column profile and a clipping of depth for each interface to a fixed z* or p* grid. This should probably be (optionally?) changed to find the nearest location of the target density.
subroutine build_grid_slight (G, GV, h, tv, dzInterface, remapCS, CS)
Builds a grid that tracks density interfaces for water that is denser than the surface density plus an increment of some number of layers, and uses all lighter layers uniformly above this location. Note that this amounts to interpolating to find the depth of an arbitrary (non-integer) interface index which should make the results vary smoothly in space to the extent that the surface density and interior stratification vary smoothly in space. Over shallow topography, this will tend to give a uniform sigma-like coordinate. For sufficiently shallow water, a minimum grid spacing is used to avoid certain instabilities.
subroutine rho_interfaces_col (rho_col, h_col, z_col, rho_tgt, nz, z_col_new, CS, reliable, debug)
Finds the new interface locations in a column of water that match the prescribed target densities.
subroutine, public adjust_interface_motion (nk, min_thickness, h_old, dz_int)
Adjust dz_Interface to ensure non-negative future thicknesses.
subroutine build_grid_arbitrary (G, GV, h, dzInterface, h_new, CS)
subroutine regridding_set_ppolys (densities, CS, n0, h0, ppoly0_E, ppoly0_S, ppoly0_coefficients, degree)
Given the set of target values and cell densities, this routine builds an interpolated profile for the densities within each grid cell. It may happen that, given a high-order interpolator, the number of available layers is insufficient (e.g., there are two available layers for a third-order PPM ih4 scheme). In these cases, we resort to the simplest continuous linear scheme (P1M h2).
subroutine interpolate_grid (n0, h0, x0, ppoly0_E, ppoly0_coefficients, target_values, degree, n1, h1, x1)
real function get_polynomial_coordinate (N, h, x_g, ppoly_E, ppoly_coefficients, target_value, degree)
subroutine, public inflate_vanished_layers_old (CS, G, GV, h)
subroutine old_inflate_layers_1d (minThickness, N, h)
subroutine convective_adjustment (G, GV, h, tv)
real function, dimension(nk), public uniformresolution (nk, coordMode, maxDepth, rhoLight, rhoHeavy)
subroutine, public setcoordinateresolution (dz, CS)
subroutine, public set_target_densities_from_gv (GV, CS)
Set target densities based on the old Rlay variable.
subroutine, public set_target_densities (CS, rho_int)
Set target densities based on vector of interface values.
subroutine, public set_regrid_max_depths (CS, max_depths, units_to_H)
Set maximum interface depths based on a vector of input values.
subroutine, public set_regrid_max_thickness (CS, max_h, units_to_H)
Set maximum layer thicknesses based on a vector of input values.
real function, dimension(cs%nk), public getcoordinateresolution (CS)
real function, dimension(cs%nk+1), public getcoordinateinterfaces (CS)
Query the target coordinate interface positions.
character(len=20) function, public getcoordinateunits (CS)
character(len=20) function, public getcoordinateshortname (CS)
subroutine, public set_regrid_params (CS, boundary_extrapolation, min_thickness, old_grid_weight, depth_of_time_filter_shallow, depth_of_time_filter_deep, compress_fraction, dz_min_surface, nz_fixed_surface, Rho_ML_avg_depth, nlay_ML_to_interior, fix_haloclines, halocline_filt_len, halocline_strat_tol, integrate_downward_for_e, height_of_rigid_surface)
This subroutine can be used to set many of the parameters for MOM_regridding.
real function, dimension(cs%nk), public getstaticthickness (CS, SSH, depth)
subroutine allocate_regridding (CS)
subroutine regridding_memory_deallocation (CS)
Deallocate memory for regridding.
Variables
character(len=320), parameter, public regriddingcoordinatemodedoc = " LAYER - Isopycnal or stacked shallow water layers\n"// " Z* - stetched geopotential z*\n"// " SIGMA - terrain following coordinates\n"// " RHO - continuous isopycnal\n"// " HYCOM1 - HyCOM-like hybrid coordinate\n"// " SLIGHT - stretched coordinates above continuous isopycnal"
Documentation for coordinate options.
character(len=338), parameter, public regriddinginterpschemedoc = " P1M_H2 (2nd-order accurate)\n"// " P1M_H4 (2nd-order accurate)\n"// " P1M_IH4 (2nd-order accurate)\n"// " PLM (2nd-order accurate)\n"// " PPM_H4 (3rd-order accurate)\n"// " PPM_IH4 (3rd-order accurate)\n"// " P3M_IH4IH3 (4th-order accurate)\n"// " P3M_IH6IH5 (4th-order accurate)\n"// " PQM_IH4IH3 (4th-order accurate)\n"// " PQM_IH6IH5 (5th-order accurate)"
character(len=6), parameter, public regriddingdefaultinterpscheme = "P1M_H2"
logical, parameter, public regriddingdefaultboundaryextrapolation = .false.
real, parameter, public regriddingdefaultminthickness = 1.e-3
integer, parameter interpolation_p1m_h2 = 0
O(h^2)
integer, parameter interpolation_p1m_h4 = 1
O(h^2)
integer, parameter interpolation_p1m_ih4 = 2
O(h^2)
integer, parameter interpolation_plm = 3
O(h^2)
integer, parameter interpolation_ppm_h4 = 4
O(h^3)
integer, parameter interpolation_ppm_ih4 = 5
O(h^3)
integer, parameter interpolation_p3m_ih4ih3 = 6
O(h^4)
integer, parameter interpolation_p3m_ih6ih5 = 7
O(h^4)
integer, parameter interpolation_pqm_ih4ih3 = 8
O(h^4)
integer, parameter interpolation_pqm_ih6ih5 = 9
O(h^5)
integer, parameter degree_1 = 1
List of interpolant degrees.
integer, parameter degree_2 = 2
integer, parameter degree_3 = 3
integer, parameter degree_4 = 4
integer, parameter nb_regridding_iterations = 1
Maximum number of regridding iterations.
real, parameter deviation_tolerance = 1e-10
Deviation tolerance between succesive grids in regridding iterations.
integer, parameter nr_iterations = 8
Maximum number of Newton-Raphson iterations. Newton-Raphson iterations are used to build the new grid by finding the coordinates associated with target densities and interpolations of degree larger than 1.
real, parameter nr_tolerance = 1e-12
Tolerance for Newton-Raphson iterations (stop when increment falls below this)
real, parameter nr_offset = 1e-6
When the N-R algorithm produces an estimate that lies outside [0,1], the estimate is set to be equal to the boundary location, 0 or 1, plus or minus an offset, respectively, when the derivative is zero at the boundary.
Detailed Description
Generates vertical grids as part of the ALE algorithm.
A vertical grid is defined solely by the cell thicknesses, \(h\). Most calculations in this module start with the coordinate at the bottom of the column set to -depth, and use a increasing value of coordinate with decreasing k. This is consistent with the rest of MOM6 that uses position, f$z.
Function/Subroutine Documentation
subroutine, public mom_regridding::adjust_interface_motion (integer, intent(in) nk, real, intent(in) min_thickness, real, dimension(nk), intent(in) h_old, real, dimension(nk+1), intent(inout) dz_int)
Adjust dz_Interface to ensure non-negative future thicknesses.
Parameters
[in] nk Number of layers
[in] min_thickness Minium allowed thickness of h (H units)
[in] h_old Minium allowed thickness of h (H units)
[in,out] dz_int Minium allowed thickness of h (H units)
Definition at line 1726 of file MOM_regridding.F90.
Referenced by build_grid_hycom1(), build_grid_slight(), and build_zstar_grid().
   integer,               intent(in)    :: nk !< Number of layers
   real,                  intent(in)    :: min_thickness !< Minium allowed thickness of h (H units)
   real, dimension(nk),   intent(in)    :: h_old !< Minium allowed thickness of h (H units)
   real, dimension(nk+1), intent(inout) :: dz_int !< Minium allowed thickness of h (H units)
   ! Local variables
   integer :: k
   real :: h_new, eps, h_total, h_err
   eps = 1. ; eps = epsilon(eps)
   h_total = 0. ; h_err = 0.
   do k = 1, nk
     h_total = h_total + h_old(k)
     h_err = h_err + max( h_old(k), abs(dz_int(k)), abs(dz_int(k+1)) )*eps
     h_new = h_old(k) + ( dz_int(k) - dz_int(k+1) )
     if (h_new < -3.0*h_err) then
       write(0,*) 'h<0 at k=',k,'h_old=',h_old(k), &
         'wup=',dz_int(k),'wdn=',dz_int(k+1),'dw_dz=',dz_int(k) - dz_int(k+1), &
         'h_new=',h_new,'h_err=',h_err
       call mom_error( fatal, 'MOM_regridding: adjust_interface_motion() - '//&
                      'implied h<0 is larger than roundoff!')
     endif
   enddo
   do k = nk,2,-1
     h_new = h_old(k) + ( dz_int(k) - dz_int(k+1) )
     if (h_new<min_thickness) dz_int(k) = ( dz_int(k+1) - h_old(k) ) + min_thickness ! Implies next h_new = min_thickness
     h_new = h_old(k) + ( dz_int(k) - dz_int(k+1) )
     if (h_new<0.) dz_int(k) = ( 1. - eps ) * ( dz_int(k+1) - h_old(k) ) ! Backup in case min_thickness==0
     h_new = h_old(k) + ( dz_int(k) - dz_int(k+1) )
     if (h_new<0.) then
       write(0,*) 'h<0 at k=',k,'h_old=',h_old(k), &
         'wup=',dz_int(k),'wdn=',dz_int(k+1),'dw_dz=',dz_int(k) - dz_int(k+1), &
         'h_new=',h_new
       stop 'Still did not work!'
       call mom_error( fatal, 'MOM_regridding: adjust_interface_motion() - '//&
                      'Repeated adjustment for roundoff h<0 failed!')
     endif
   enddo
  !if (dz_int(1)/=0.) stop 'MOM_regridding: adjust_interface_motion() surface moved'
subroutine mom_regridding::allocate_regridding (type(regridding_cs), intent(inout) CS) private
Definition at line 2738 of file MOM_regridding.F90.
Referenced by initialize_regridding().
 !------------------------------------------------------------------------------
 ! In this routine, we allocate the memory needed to carry out regridding
 ! steps in the course of the simulation.
 ! For example, to compute implicit edge-value estimates, a tridiagonal system
 ! must be solved. We allocate the needed memory at the beginning of the
 ! simulation because the number of layers never changes.
 !------------------------------------------------------------------------------
   ! Arguments
   type(regridding_cs), intent(inout) :: cs
   ! Local variables
   ! Target values
   allocate( cs%target_density(cs%nk+1) )
   ! Target resolution (for fixed coordinates)
   allocate( cs%coordinateResolution(cs%nk) ); cs%coordinateResolution(:) = -1.e30
subroutine mom_regridding::build_grid_arbitrary (type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, real, dimension(szi_(g),szj_(g), szk_(gv)), intent(in) h, real, dimension(szi_(g),szj_(g), szk_(gv)+1), intent(inout) dzInterface, real, intent(inout) h_new, type(regridding_cs), intent(in) CS) private
Parameters
[in] g Ocean grid structure
[in] gv Ocean vertical grid structure
[in] h Original ayer thicknesses, in H
[in,out] dzinterface The change in interface depth in H
[in,out] h_new New layer thicknesses, in H
[in] cs Regridding control structure
Definition at line 1772 of file MOM_regridding.F90.
Referenced by regridding_main().
 !------------------------------------------------------------------------------
 ! This routine builds a grid based on arbitrary rules
 !------------------------------------------------------------------------------
   ! Arguments
   type(ocean_grid_type),                        intent(in)    :: g  !< Ocean grid structure
   type(verticalgrid_type),                      intent(in)    :: gv !< Ocean vertical grid structure
   real, dimension(SZI_(G),SZJ_(G), SZK_(GV)),   intent(in)    :: h  !< Original ayer thicknesses, in H
   real, dimension(SZI_(G),SZJ_(G), SZK_(GV)+1), intent(inout) :: dzinterface !< The change in interface depth in H
   real,                                         intent(inout) :: h_new !< New layer thicknesses, in H
   type(regridding_cs),                          intent(in)    :: cs !< Regridding control structure
   ! Local variables
   integer   :: i, j, k
   integer   :: nz
   real      :: z_inter(szk_(gv)+1)
   real      :: total_height
   real      :: delta_h
   real      :: max_depth
   real      :: min_thickness
   real      :: eta              ! local elevation
   real      :: local_depth
   real      :: x1, y1, x2, y2
   real      :: x, t
   nz = gv%ke
   max_depth = g%max_depth
   min_thickness = cs%min_thickness
   do j = g%jsc-1,g%jec+1
     do i = g%isc-1,g%iec+1
       ! Local depth
       local_depth = g%bathyT(i,j)*gv%m_to_H
       ! Determine water column height
       total_height = 0.0
       do k = 1,nz
         total_height = total_height + h(i,j,k)
       end do
       eta = total_height - local_depth
       ! Compute new thicknesses based on stretched water column
       delta_h = (max_depth + eta) / nz
       ! Define interfaces
       z_inter(1) = eta
       do k = 1,nz
         z_inter(k+1) = z_inter(k) - delta_h
       end do
       ! Refine grid in the middle
       do k = 1,nz+1
         x1 = 0.35; y1 = 0.45; x2 = 0.65; y2 = 0.55
         x = - ( z_inter(k) - eta ) / max_depth
         if ( x <= x1 ) then
           t = y1*x/x1
         else if ( (x > x1 ) .and. ( x < x2 )) then
           t = y1 + (y2-y1) * (x-x1) / (x2-x1)
         else
           t = y2 + (1.0-y2) * (x-x2) / (1.0-x2)
         end if
         z_inter(k) = -t * max_depth + eta
       end do
       ! Modify interface heights to account for topography
       z_inter(nz+1) = - local_depth
       ! Modify interface heights to avoid layers of zero thicknesses
       do k = nz,1,-1
         if ( z_inter(k) < (z_inter(k+1) + min_thickness) ) then
           z_inter(k) = z_inter(k+1) + min_thickness
         end if
       end do
       ! Chnage in interface position
       x = 0. ! Left boundary at x=0
       dzinterface(i,j,1) = 0.
       do k = 2,nz
         x = x + h(i,j,k)
         dzinterface(i,j,k) = z_inter(k) - x
       end do
       dzinterface(i,j,nz+1) = 0.
     end do
   end do
 stop 'OOOOOOPS' ! For some reason the gnu compiler will not let me delete this
                 ! routine????
subroutine mom_regridding::build_grid_hycom1 (type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, real, dimension(szi_(g),szj_(g),szk_(gv)), intent(in) h, type(thermo_var_ptrs), intent(in) tv, real, dimension(szi_(g),szj_(g),szk_(gv)+1), intent(inout) dzInterface, type(remapping_cs), intent(in) remapCS, type(regridding_cs), intent(in) CS) private
Builds a simple HyCOM-like grid with the deepest location of potential density interpolated from the column profile and a clipping of depth for each interface to a fixed z* or p* grid. This should probably be (optionally?) changed to find the nearest location of the target density.
Remarks
{ Based on Bleck, 2002: An oceanice general circulation model framed in hybrid isopycnic-Cartesian coordinates, Ocean Modelling 37, 55-88. http://dx.doi.org/10.1016/S1463-5003(01)00012-9 }
Parameters
[in] g Grid structure
[in] gv Ocean vertical grid structure
[in] h Existing model thickness, in H units
[in] tv Thermodynamics structure
[in,out] dzinterface Changes in interface position
[in] remapcs Remapping control structure
[in] cs Regridding control structure
Definition at line 1045 of file MOM_regridding.F90.
References adjust_interface_motion(), filtered_grid_motion(), interpolate_grid(), mom_error_handler::mom_error(), and regridding_set_ppolys().
Referenced by regridding_main().
   type(ocean_grid_type),                       intent(in)    :: g  !< Grid structure
   type(verticalgrid_type),                     intent(in)    :: gv !< Ocean vertical grid structure
   real, dimension(SZI_(G),SZJ_(G),SZK_(GV)),   intent(in)    :: h  !< Existing model thickness, in H units
   type(thermo_var_ptrs),                       intent(in)    :: tv !< Thermodynamics structure
   real, dimension(SZI_(G),SZJ_(G),SZK_(GV)+1), intent(inout) :: dzinterface !< Changes in interface position
   type(remapping_cs),                          intent(in)    :: remapcs !< Remapping control structure
   type(regridding_cs),                         intent(in)    :: cs !< Regridding control structure
   ! Local variables
   integer   :: i, j, k, nz
   real, dimension(SZK_(GV)) :: t_col, s_col, p_col, rho_col, h_col_new ! Layer quantities
   real, dimension(SZK_(GV)+1) :: z_col, z_col_new ! Interface positions relative to the surface in H units (m or kg m-2)
   real, dimension(SZK_(GV)+1) :: dz_col  ! The realized change in z_col in H units (m or kg m-2)
   real, dimension(CS%nk,2) :: ppoly_i_e ! Edge value of polynomial
   real, dimension(CS%nk,2) :: ppoly_i_s ! Edge slope of polynomial
   real, dimension(CS%nk,CS%degree_i+1) :: ppoly_i_coefficients ! Coefficients of polynomial
   real :: nominal_z ! Nominal depth of interface is using z* (m or Pa)
   real :: stretching ! z* stretching, converts z* to z.
   real :: hnew
   logical :: maximum_depths_set ! If true, the maximum depths of interface have been set.
   logical :: maximum_h_set      ! If true, the maximum layer thicknesses have been set.
   integer :: ppoly_degree
   nz = gv%ke
   maximum_depths_set = allocated(cs%max_interface_depths)
   maximum_h_set = allocated(cs%max_layer_thickness)
   if (.not.cs%target_density_set) call mom_error(fatal, "build_grid_HyCOM1 : "//&
         "Target densities must be set before build_grid_HyCOM1 is called.")
   ! Build grid based on target interface densities
   do j = g%jsc-1,g%jec+1 ; do i = g%isc-1,g%iec+1
     if (g%mask2dT(i,j)>0.) then
       ! Copy T and S onto new variables so as to not alter the original values
       ! of T and S (these are remapped at the end of the regridding iterations
       ! once the final grid has been determined).
       t_col(:) = tv%T(i,j,:)
       s_col(:) = tv%S(i,j,:)
       z_col(1) = 0. ! Work downward rather than bottom up
       do k = 1, nz
         z_col(k+1) = z_col(k) + h(i,j,k) ! Work in units of h (m or Pa)
         p_col(k) = cs%ref_pressure + cs%compressibility_fraction * &
              ( 0.5 * ( z_col(k) + z_col(k+1) ) * gv%H_to_Pa - cs%ref_pressure )
       enddo
       ! Work bottom recording potential density
       call calculate_density(t_col, s_col, p_col, &
                              rho_col, 1, nz, tv%eqn_of_state )
       ! This ensures the potential density profile is monotonic
       ! although not necessarily single valued.
       do k = nz-1, 1, -1
         rho_col(k) = min( rho_col(k), rho_col(k+1) )
       enddo
       ! Interpolates for the target interface position with the rho_col profile
       call regridding_set_ppolys(rho_col, cs, nz, h(i,j,:), ppoly_i_e, ppoly_i_s, &
                                  ppoly_i_coefficients, ppoly_degree)
       ! Based on global density profile, interpolate to generate a new grid
       call interpolate_grid(nz, h(i,j,:), z_col, ppoly_i_e, ppoly_i_coefficients, &
                             cs%target_density, ppoly_degree, nz, h_col_new, z_col_new)
       ! Sweep down the interfaces and make sure that the interface is at least
       ! as deep as a nominal target z* grid
       nominal_z = 0.
       stretching = z_col(nz+1) / g%bathyT(i,j) * gv%m_to_H ! Stretches z* to z
       do k = 2, nz+1
         nominal_z = nominal_z + cs%coordinateResolution(k-1) * stretching
         z_col_new(k) = max( z_col_new(k), nominal_z )
         z_col_new(k) = min( z_col_new(k), z_col(nz+1) )
       enddo
       if (maximum_depths_set .and. maximum_h_set) then ; do k=2,nz
         ! The loop bounds are 2 & nz so the top and bottom interfaces do not move.
         ! Recall that z_col_new is positive downward.
         z_col_new(k) = min(z_col_new(k), cs%max_interface_depths(k), &
                            z_col_new(k-1) + cs%max_layer_thickness(k-1))
       enddo ; elseif (maximum_depths_set) then ; do k=2,nz
         z_col_new(k) = min(z_col_new(k), cs%max_interface_depths(k))
       enddo ; elseif (maximum_h_set) then ; do k=2,nz
         z_col_new(k) = min(z_col_new(k), z_col_new(k-1) + cs%max_layer_thickness(k-1))
       enddo ; endif
       ! Calculate the final change in grid position after blending new and old grids
       call filtered_grid_motion( cs, nz, z_col, z_col_new, dz_col )
       do k=1,nz+1 ; dzinterface(i,j,k) = -dz_col(k) ; enddo
       ! This adjusts things robust to round-off errors
       call adjust_interface_motion( nz, cs%min_thickness, h(i,j,:), dzinterface(i,j,:) )
     else ! on land
       dzinterface(i,j,:) = 0.
     endif ! mask2dT
   enddo; enddo ! i,j
subroutine mom_regridding::build_grid_slight (type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, real, dimension(szi_(g),szj_(g),szk_(gv)), intent(in) h, type(thermo_var_ptrs), intent(in) tv, real, dimension(szi_(g),szj_(g),szk_(gv)+1), intent(inout) dzInterface, type(remapping_cs), intent(in) remapCS, type(regridding_cs), intent(in) CS) private
Builds a grid that tracks density interfaces for water that is denser than the surface density plus an increment of some number of layers, and uses all lighter layers uniformly above this location. Note that this amounts to interpolating to find the depth of an arbitrary (non-integer) interface index which should make the results vary smoothly in space to the extent that the surface density and interior stratification vary smoothly in space. Over shallow topography, this will tend to give a uniform sigma-like coordinate. For sufficiently shallow water, a minimum grid spacing is used to avoid certain instabilities.
Parameters
[in] g Grid structure
[in] gv Ocean vertical grid structure
[in] h Existing model thickness, in H units
[in] tv Thermodynamics structure
[in,out] dzinterface Changes in interface position
[in] remapcs Remapping control structure
[in] cs Regridding control structure
Definition at line 1151 of file MOM_regridding.F90.
References adjust_interface_motion(), filtered_grid_motion(), and rho_interfaces_col().
Referenced by regridding_main().
   type(ocean_grid_type),                       intent(in)    :: g  !< Grid structure
   type(verticalgrid_type),                     intent(in)    :: gv !< Ocean vertical grid structure
   real, dimension(SZI_(G),SZJ_(G),SZK_(GV)),   intent(in)    :: h  !< Existing model thickness, in H units
   type(thermo_var_ptrs),                       intent(in)    :: tv !< Thermodynamics structure
   real, dimension(SZI_(G),SZJ_(G),SZK_(GV)+1), intent(inout) :: dzinterface !< Changes in interface position
   type(remapping_cs),                          intent(in)    :: remapcs !< Remapping control structure
   type(regridding_cs),                         intent(in)    :: cs !< Regridding control structure
   ! Local variables
   real, dimension(SZK_(GV)) :: t_col, s_col, p_col, rho_col ! Layer quantities
   real, dimension(SZK_(GV)) :: h_col     ! A column of layer thicknesses on the original grid in H units.
   real, dimension(SZK_(GV)) :: t_f, s_f  ! Filtered ayer quantities
   real, dimension(SZK_(GV)+1) :: z_col, z_col_new ! Interface positions relative to the surface in H units (m or kg m-2)
   real, dimension(SZK_(GV)+1) :: dz_col  ! The realized change in z_col in H units (m or kg m-2)
   logical, dimension(SZK_(GV)+1) :: reliable  ! If true, this interface is in a reliable position.
   real, dimension(SZK_(GV)+1) :: t_int, s_int ! Temperature and salinity interpolated to interfaces.
   real, dimension(SZK_(GV)+1) :: rho_tmp, drho_dp, p_is, p_r
   real, dimension(SZK_(GV)+1) :: drhois_dt, drhois_ds
   real, dimension(SZK_(GV)+1) :: drhor_dt, drhor_ds
   real, dimension(SZK_(GV)+1) :: strat_rat
   real :: h_to_cpa
   real :: dris, drr, fn_now, i_hstol, fn_zero_val
   real :: z_int_unst
   real :: dz      ! A uniform layer thickness in very shallow water, in H.
   real :: dz_ur   ! The total thickness of an unstable region, in H.
   real :: wgt, cowgt  ! A weight and its complement, nondim.
   real :: rho_ml_av ! The average potential density in a near-surface region, in kg m-3.
   real :: h_ml_av ! A thickness to try to use in taking the near-surface average, in H.
   real :: rho_x_z ! A cumulative integral of a density, in kg m-3 H.
   real :: z_wt    ! The thickness actually used in taking the near-surface average, in H.
   real :: k_interior  ! The (real) value of k where the interior grid starts.
   real :: k_int2      ! The (real) value of k where the interior grid starts.
   real :: z_interior  ! The depth where the interior grid starts, in H.
   real :: z_ml_fix    ! The depth at which the fixed-thickness near-surface layers end, in H.
   real :: dz_dk       ! The thickness of layers between the fixed-thickness
                       ! near-surface layars and the interior, in H.
   real :: lfilt       ! A filtering lengthscale, in H.
   logical :: maximum_depths_set ! If true, the maximum depths of interface have been set.
   logical :: maximum_h_set      ! If true, the maximum layer thicknesses have been set.
   real :: k2_used, k2here, dz_sum, z_max
   integer :: k2
   real :: h_tr, b_denom_1, b1, d1 ! Temporary variables used by the tridiagonal solver.
   real, dimension(SZK_(GV)) :: c1  ! Temporary variables used by the tridiagonal solver.
   integer :: kur1, kur2  ! The indicies at the top and bottom of an unreliable region.
   integer :: kur_ss      ! The index to start with in the search for the next unstable region.
   integer :: i, j, k, nz, nkml
   nz = gv%ke
   maximum_depths_set = allocated(cs%max_interface_depths)
   maximum_h_set = allocated(cs%max_layer_thickness)
   if (.not.cs%target_density_set) call mom_error(fatal, "build_grid_SLight : "//&
         "Target densities must be set before build_grid_SLight is called.")
   ! Build grid based on target interface densities
   do j = g%jsc-1,g%jec+1 ; do i = g%isc-1,g%iec+1
     if (g%mask2dT(i,j)>0.) then
       ! Copy T and S onto new variables so as to not alter the original values
       ! of T and S (these are remapped at the end of the regridding iterations
       ! once the final grid has been determined).
       do k=1,nz
         t_col(k) = tv%T(i,j,k) ; s_col(k) = tv%S(i,j,k)
         h_col(k) = h(i,j,k)
       enddo
       z_col(1) = 0. ! Work downward rather than bottom up
       do k=1,nz
         z_col(k+1) = z_col(k) + h_col(k) ! Work in units of h (m or Pa)
         p_col(k) = cs%ref_pressure + cs%compressibility_fraction * &
              ( 0.5 * ( z_col(k) + z_col(k+1) ) * gv%H_to_Pa - cs%ref_pressure )
       enddo
       if (z_col(nz+1) - z_col(1) < nz*cs%min_thickness) then
         ! This is a nearly massless total depth, so distribute the water evenly.
         dz = (z_col(nz+1) - z_col(1)) / real(nz)
         do k=2,nz ; z_col_new(k) = z_col(1) + dz*real(K-1) ; enddo
       else
         call calculate_density(t_col, s_col, p_col, rho_col, 1, nz, &
                                tv%eqn_of_state)
         ! Find the locations of the target potential densities, flagging
         ! locations in apparently unstable regions as not reliable.
         call rho_interfaces_col(rho_col, h_col, z_col, cs%target_density, nz, &
                                 z_col_new, cs, reliable, debug=.true.)
         ! Ensure that the interfaces are at least CS%min_thickness apart.
         if (cs%min_thickness > 0.0) then
           ! Move down interfaces below overly thin layers.
           do k=2,nz ; if (z_col_new(k) < z_col_new(k-1) + cs%min_thickness) then
             z_col_new(k) = z_col_new(k-1) + cs%min_thickness
           endif ; enddo
           ! Now move up any interfaces that are too close to the bottom.
           do k=nz,2,-1 ; if (z_col_new(k) > z_col_new(k+1) - cs%min_thickness) then
             z_col_new(k) = z_col_new(k+1) - cs%min_thickness
           else
             exit ! No more interfaces can be too close to the bottom.
           endif ; enddo
         endif
         ! Fix up the unreliable regions.
         kur_ss = 2 ! reliable(1) and reliable(nz+1) must always be true.
         do
           ! Search for the uppermost unreliable interface postion.
           kur1 = nz+2
           do k=kur_ss,nz ; if (.not.reliable(k)) then
             kur1 = k ; exit
           endif ; enddo
           if (kur1 > nz) exit ! Everything is now reliable.
           kur2 = kur1-1 ! For error checking.
           do k=kur1+1,nz+1 ; if (reliable(k)) then
             kur2 = k-1 ; kur_ss = k ; exit
           endif ; enddo
           if (kur2 < kur1) call mom_error(fatal, "Bad unreliable range.")
           dz_ur = z_col_new(kur2+1) - z_col_new(kur1-1)
   !        drho = CS%target_density(kur2+1) - CS%target_density(kur1-1)
           ! Perhaps reset the wgt and cowgt depending on how bad the old interface
           ! locations were.
           wgt = 1.0 ; cowgt = 0.0 ! = 1.0-wgt
           do k=kur1,kur2
             z_col_new(k) = cowgt*z_col_new(k) + &
                   wgt * (z_col_new(kur1-1) + dz_ur*(k - (kur1-1)) / ((kur2 - kur1) + 2))
           enddo
         enddo
         ! Determine which interfaces are in the s-space region and the depth extent
         ! of this region.
         z_wt = 0.0 ; rho_x_z = 0.0
         h_ml_av = gv%m_to_H*cs%Rho_ml_avg_depth
         do k=1,nz
           if (z_wt + h_col(k) >= h_ml_av) then
             rho_x_z = rho_x_z + rho_col(k) * (h_ml_av - z_wt)
             z_wt = h_ml_av
             exit
           else
             rho_x_z =  rho_x_z + rho_col(k) * h_col(k)
             z_wt = z_wt + h_col(k)
           endif
         enddo
         if (z_wt > 0.0) rho_ml_av = rho_x_z / z_wt
         nkml = cs%nz_fixed_surface
         ! Find the interface that matches rho_ml_av.
         if (rho_ml_av <= cs%target_density(nkml)) then
           k_interior = cs%nlay_ml_offset + real(nkml)
         elseif (rho_ml_av > cs%target_density(nz+1)) then
           k_interior = real(nz+1)
         else ; do k=nkml,nz
           if ((rho_ml_av >= cs%target_density(k)) .and. &
               (rho_ml_av <  cs%target_density(k+1))) then
             k_interior = (cs%nlay_ml_offset + k) + &
                     (rho_ml_av - cs%target_density(k)) / &
                     (cs%target_density(k+1) - cs%target_density(k))
             exit
           endif
         enddo ; endif
         if (k_interior > real(nz+1)) k_interior = real(nz+1)
         ! Linearly interpolate to find z_interior.  This could be made more sophisticated.
         k = int(ceiling(k_interior))
         z_interior = (k-k_interior)*z_col_new(k-1) + (1.0+(k_interior-k))*z_col_new(k)
         if (cs%fix_haloclines) then
 !       ! Identify regions above the reference pressure where the chosen
 !       ! potential density significantly underestimates the actual
 !       ! stratification, and use these to find a second estimate of
 !       ! z_int_unst and k_interior.
           if (cs%halocline_filter_length > 0.0) then
             lfilt = cs%halocline_filter_length*gv%m_to_H
             ! Filter the temperature and salnity with a fixed lengthscale.
             h_tr = h_col(1) + gv%H_subroundoff
             b1 = 1.0 / (h_tr + lfilt) ; d1 = h_tr * b1
             t_f(1) = (b1*h_tr)*t_col(1) ;  s_f(1) = (b1*h_tr)*s_col(1)
             do k=2,nz
               c1(k) = lfilt * b1
               h_tr = h_col(k) + gv%H_subroundoff ; b_denom_1 = h_tr + d1*lfilt
               b1 = 1.0 / (b_denom_1 + lfilt) ; d1 = b_denom_1 * b1
               t_f(k) = b1 * (h_tr*t_col(k) + lfilt*t_f(k-1))
               s_f(k) = b1 * (h_tr*s_col(k) + lfilt*s_f(k-1))
             enddo
             do k=nz-1,1,-1
               t_f(k) = t_f(k) + c1(k+1)*t_f(k+1) ; s_f(k) = s_f(k) + c1(k+1)*s_f(k+1)
             enddo
           else
             do k=1,nz ; t_f(k) = t_col(k) ; s_f(k) = s_col(k) ; enddo
           endif
           t_int(1) = t_f(1) ; s_int(1) = s_f(1)
           do k=2,nz
             t_int(k) = 0.5*(t_f(k-1) + t_f(k)) ; s_int(k) = 0.5*(s_f(k-1) + s_f(k))
             p_is(k) = z_col(k) * gv%H_to_Pa
             p_r(k) = cs%ref_pressure + cs%compressibility_fraction * ( p_is(k) - cs%ref_pressure )
           enddo
           t_int(nz+1) = t_f(nz) ; s_int(nz+1) = s_f(nz)
           p_is(nz+1) = z_col(nz+1) * gv%H_to_Pa
           call calculate_density_derivs(t_int, s_int, p_is, drhois_dt, drhois_ds, 2, nz-1, &
                                         tv%eqn_of_state)
           call calculate_density_derivs(t_int, s_int, p_r, drhor_dt, drhor_ds, 2, nz-1, &
                                         tv%eqn_of_state)
           if (cs%compressibility_fraction > 0.0) then
             call calculate_compress(t_int, s_int, p_r, rho_tmp, drho_dp, 2, nz-1, &
                                           tv%eqn_of_state)
           else
             do k=2,nz ; drho_dp(k) = 0.0 ; enddo
           endif
           h_to_cpa = cs%compressibility_fraction*gv%H_to_Pa
           strat_rat(1) = 1.0
           do k=2,nz
             dris = drhois_dt(k) * (t_f(k) - t_f(k-1)) + &
                    drhois_ds(k) * (s_f(k) - s_f(k-1))
             drr = (drhor_dt(k) * (t_f(k) - t_f(k-1)) + &
                    drhor_ds(k) * (s_f(k) - s_f(k-1))) + &
                   drho_dp(k) * (h_to_cpa*0.5*(h_col(k) + h_col(k-1)))
             if (dris <= 0.0) then
               strat_rat(k) = 2.0 ! Maybe do this? => ; if (drR < 0.0) strat_rat(K) = -2.0
             else
               strat_rat(k) = 2.0*max(drr,0.0) / (dris + abs(drr))
             endif
           enddo
           strat_rat(nz+1) = 1.0
           z_int_unst = 0.0 ; fn_now = 0.0
           fn_zero_val = min(2.0*cs%halocline_strat_tol, &
                             0.5*(1.0 + cs%halocline_strat_tol))
           if (cs%halocline_strat_tol > 0.0) then
             ! Use Adcroft's reciprocal rule.
             i_hstol = 0.0 ; if (fn_zero_val - cs%halocline_strat_tol > 0.0) &
               i_hstol = 1.0 / (fn_zero_val - cs%halocline_strat_tol)
             do k=nz,1,-1 ; if (cs%ref_pressure > p_is(k+1)) then
               z_int_unst = z_int_unst + fn_now * h_col(k)
               if (strat_rat(k) <= fn_zero_val) then
                 if (strat_rat(k) <= cs%halocline_strat_tol) then ; fn_now = 1.0
                 else
                   fn_now = max(fn_now, (fn_zero_val - strat_rat(k)) * i_hstol)
                 endif
               endif
             endif ; enddo
           else
             do k=nz,1,-1 ; if (cs%ref_pressure > p_is(k+1)) then
               z_int_unst = z_int_unst + fn_now * h_col(k)
               if (strat_rat(k) <= cs%halocline_strat_tol) fn_now = 1.0
             endif ; enddo
           endif
           if (z_interior < z_int_unst) then
             ! Find a second estimate of the extent of the s-coordinate region.
             kur1 = max(int(ceiling(k_interior)),2)
             if (z_col_new(kur1-1) < z_interior) then
               k_int2 = kur1
               do k = kur1,nz+1 ; if (z_col_new(k) >= z_int_unst) then
                 ! This is linear interpolation again.
                 if (z_col_new(k-1) >= z_int_unst) &
                   call mom_error(fatal,"build_grid_SLight, bad halocline structure.")
                 k_int2 = real(K-1) + (z_int_unst - z_col_new(k-1)) / &
                                          (z_col_new(k) - z_col_new(k-1))
                 exit
               endif ; enddo
               if (z_col_new(nz+1) < z_int_unst) then
                 ! This should be unnecessary.
                 z_int_unst = z_col_new(nz+1) ; k_int2 = real(nz+1)
               endif
               ! Now take the larger values.
               if (k_int2 > k_interior) then
                 k_interior = k_int2 ; z_interior = z_int_unst
               endif
             endif
           endif
         endif  ! fix_haloclines
         z_col_new(1) = 0.0
         do k=2,nkml+1
           z_col_new(k) = min((k-1)*cs%dz_ml_min, &
                              z_col_new(nz+1) - cs%min_thickness*(nz+1-k))
         enddo
         z_ml_fix = z_col_new(nkml+1)
         if (z_interior > z_ml_fix) then
           dz_dk = (z_interior - z_ml_fix) / (k_interior - (nkml+1))
           do k=nkml+2,int(floor(k_interior))
             z_col_new(k) = z_ml_fix + dz_dk * (k - (nkml+1))
           enddo
         else ! The fixed-thickness z-region penetrates into the interior.
           do k=nkml+2,nz
             if (z_col_new(k) <= z_col_new(cs%nz_fixed_surface+1)) then
               z_col_new(k) = z_col_new(cs%nz_fixed_surface+1)
             else ; exit ; endif
           enddo
         endif
         if (maximum_depths_set .and. maximum_h_set) then ; do k=2,nz
           ! The loop bounds are 2 & nz so the top and bottom interfaces do not move.
           ! Recall that z_col_new is positive downward.
           z_col_new(k) = min(z_col_new(k), cs%max_interface_depths(k), &
                                 z_col_new(k-1) + cs%max_layer_thickness(k-1))
         enddo ; elseif (maximum_depths_set) then ; do k=2,nz
           z_col_new(k) = min(z_col_new(k), cs%max_interface_depths(k))
         enddo ; elseif (maximum_h_set) then ; do k=2,nz
           z_col_new(k) = min(z_col_new(k), z_col_new(k-1) + cs%max_layer_thickness(k-1))
         enddo ; endif
       endif ! Total thickness exceeds nz*CS%min_thickness.
       ! Calculate the final change in grid position after blending new and old grids
       call filtered_grid_motion( cs, nz, z_col, z_col_new, dz_col )
       do k=1,nz+1 ; dzinterface(i,j,k) = -dz_col(k) ; enddo
 #ifdef __DO_SAFETY_CHECKS__
       if (dzinterface(i,j,1) /= 0.) stop 'build_grid_SLight: Surface moved?!'
       if (dzinterface(i,j,nz+1) /= 0.) stop 'build_grid_SLight: Bottom moved?!'
 #endif
       ! This adjusts things robust to round-off errors
       call adjust_interface_motion( nz, cs%min_thickness, h(i,j,:), dzinterface(i,j,:) )
     else ! on land
       dzinterface(i,j,:) = 0.
     endif ! mask2dT
   enddo; enddo ! i,j
subroutine mom_regridding::build_rho_grid (type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, real, dimension(szi_(g),szj_(g),szk_(gv)), intent(in) h, type(thermo_var_ptrs), intent(in) tv, real, dimension(szi_(g),szj_(g), szk_(gv)+1), intent(inout) dzInterface, type(remapping_cs), intent(in) remapCS, type(regridding_cs), intent(in) CS) private
Parameters
[in] g Ocean grid structure
[in] gv Ocean vertical grid structure
[in] h Layer thicknesses, in H
[in] tv Thermodynamics structure
[in,out] dzinterface The change in interface depth in H
[in] remapcs The remapping control structure
[in] cs Regridding control structure
Definition at line 806 of file MOM_regridding.F90.
References deviation_tolerance, filtered_grid_motion(), interpolate_grid(), mom_error_handler::mom_error(), nb_regridding_iterations, old_inflate_layers_1d(), and regridding_set_ppolys().
Referenced by regridding_main().
 !------------------------------------------------------------------------------
 ! This routine builds a new grid based on a given set of target interface
 ! densities (these target densities are computed by taking the mean value
 ! of given layer densities). The algorithn operates as follows within each
 ! column:
 ! 1. Given T & S within each layer, the layer densities are computed.
 ! 2. Based on these layer densities, a global density profile is reconstructed
 !    (this profile is monotonically increasing and may be discontinuous)
 ! 3. The new grid interfaces are determined based on the target interface
 !    densities.
 ! 4. T & S are remapped onto the new grid.
 ! 5. Return to step 1 until convergence or until the maximum number of
 !    iterations is reached, whichever comes first.
 !------------------------------------------------------------------------------
   ! Arguments
   type(ocean_grid_type),                        intent(in)    :: g  !< Ocean grid structure
   type(verticalgrid_type),                      intent(in)    :: gv !< Ocean vertical grid structure
   real, dimension(SZI_(G),SZJ_(G),SZK_(GV)),    intent(in)    :: h  !< Layer thicknesses, in H
   type(thermo_var_ptrs),                        intent(in)    :: tv !< Thermodynamics structure
   real, dimension(SZI_(G),SZJ_(G), SZK_(GV)+1), intent(inout) :: dzinterface !< The change in interface depth in H
   type(remapping_cs),                           intent(in)    :: remapcs !< The remapping control structure
   type(regridding_cs),                          intent(in)    :: cs !< Regridding control structure
   ! Local variables
   integer   :: i, j, k, m
   integer   :: map_index
   integer   :: nz
   integer   :: k_found
   integer   :: count_nonzero_layers
   real      :: deviation            ! When iterating to determine the final
                                     ! grid, this is the deviation between two
                                     ! successive grids.
   real      :: threshold
   real      :: max_thickness
   real      :: correction
   real, dimension(CS%nk,2) :: ppoly_i_e            !Edge value of polynomial
   real, dimension(CS%nk,2) :: ppoly_i_s            !Edge slope of polynomial
   real, dimension(CS%nk,CS%degree_i+1) :: ppoly_i_coefficients !Coefficients of polynomial
   integer   :: ppoly_degree         ! The actual degree of the polynomials.
   real, dimension(SZK_(GV)) :: p_col, densities, t_col, s_col, tmp_col
   integer, dimension(SZK_(GV)) :: mapping
   real    :: nominaldepth, totalthickness, dh
   real, dimension(SZK_(GV)+1) :: zold, znew
   real, dimension(SZK_(GV)) :: h0, h1, htmp
   real, dimension(SZK_(GV)+1) :: x0, x1, xtmp
   nz = gv%ke
   threshold = cs%min_thickness
   p_col(:) = cs%ref_pressure
   if (.not.cs%target_density_set) call mom_error(fatal, "build_rho_grid: "//&
         "Target densities must be set before build_rho_grid is called.")
   ! Build grid based on target interface densities
   do j = g%jsc-1,g%jec+1
     do i = g%isc-1,g%iec+1
       ! Copy T and S onto new variables so as to not alter the original values
       ! of T and S (these are remapped at the end of the regridding iterations
       ! once the final grid has been determined).
       t_col = tv%T(i,j,:)
       s_col = tv%S(i,j,:)
       ! Copy original grid
       h0(1:nz) = h(i,j,1:nz)
       ! Start iterations to build grid
       m = 1
       deviation = 1e10
       do while ( ( m <= nb_regridding_iterations ) .and. &
                  ( deviation > deviation_tolerance ) )
         ! Count number of nonzero layers within current water column
         count_nonzero_layers = 0
         do k = 1,nz
           if ( h0(k) > threshold ) then
             count_nonzero_layers = count_nonzero_layers + 1
           end if
         end do
         ! If there is at most one nonzero layer, stop here (no regridding)
         if ( count_nonzero_layers <= 1 ) then
           h1(1:nz) = h0(1:nz)
           exit  ! stop iterations here
         end if
         ! Build new grid containing only nonzero layers
         map_index = 1
         correction = 0.0
         do k = 1,nz
           if ( h0(k) > threshold ) then
             mapping(map_index) = k
             htmp(map_index) = h0(k)
             map_index = map_index + 1
           else
             correction = correction + h0(k)
           end if
         end do
         max_thickness = htmp(1)
         k_found = 1
         do k = 1,count_nonzero_layers
           if ( htmp(k) > max_thickness ) then
             max_thickness = htmp(k)
             k_found = k
           end if
         end do
         htmp(k_found) = htmp(k_found) + correction
         xtmp(1) = 0.0
         do k = 1,count_nonzero_layers
           xtmp(k+1) = xtmp(k) + htmp(k)
         end do
         ! Compute densities within current water column
         call calculate_density( t_col, s_col, p_col, densities,&
                                  1, nz, tv%eqn_of_state )
         do k = 1,count_nonzero_layers
           densities(k) = densities(mapping(k))
         end do
         ! One regridding iteration
         call regridding_set_ppolys(densities, cs, count_nonzero_layers, htmp, &
                                    ppoly_i_e, ppoly_i_s, ppoly_i_coefficients, ppoly_degree)
         ! Based on global density profile, interpolate to generate a new grid
         call interpolate_grid(count_nonzero_layers, htmp, xtmp, ppoly_i_e, ppoly_i_coefficients, &
                               cs%target_density, ppoly_degree, nz, h1, x1 )
         call old_inflate_layers_1d( cs%min_thickness, nz, h1 )
         x1(1) = 0.0 ; do k = 1,nz ; x1(k+1) = x1(k) + h1(k) ; end do
         ! Remap T and S from previous grid to new grid
         do k = 1,nz
           h1(k) = x1(k+1) - x1(k)
         end do
         call remapping_core_h(nz, h0, s_col, nz, h1, tmp_col, remapcs)
         s_col(:) = tmp_col(:)
         call remapping_core_h(nz, h0, t_col, nz, h1, tmp_col, remapcs)
         t_col(:) = tmp_col(:)
         ! Compute the deviation between two successive grids
         deviation = 0.0
         x0(1) = 0.0
         x1(1) = 0.0
         do k = 2,nz
           x0(k) = x0(k-1) + h0(k-1)
           x1(k) = x1(k-1) + h1(k-1)
           deviation = deviation + (x0(k)-x1(k))**2
         end do
         deviation = sqrt( deviation / (nz-1) )
         m = m + 1
         ! Copy final grid onto start grid for next iteration
         h0(:) = h1(:)
       end do ! end regridding iterations
       ! Local depth (G%bathyT is positive)
       nominaldepth = g%bathyT(i,j)*gv%m_to_H
       totalthickness = 0.0
       if (cs%integrate_downward_for_e) then
         zold(1) = 0.
         znew(1) = 0.
         do k = 1,nz
           totalthickness = totalthickness + h(i,j,k)
           znew(k+1) = znew(k) - h1(k)
           ! Adjust interface position to accomodate inflating layers
           ! without disturbing the interface above
           zold(k+1) = zold(k) - h(i,j,k)
         enddo
       else
         ! The rest of the model defines grids integrating up from the bottom
         zold(nz+1) = - nominaldepth
         znew(nz+1) = - nominaldepth
         do k = nz,1,-1
           totalthickness = totalthickness + h(i,j,k)
           znew(k) = znew(k+1) + h1(k)
           ! Adjust interface position to accomodate inflating layers
           ! without disturbing the interface above
           zold(k) = zold(k+1) + h(i,j,k)
         enddo
       endif
       ! Calculate the final change in grid position after blending new and old grids
       call filtered_grid_motion( cs, nz, zold, znew, dzinterface(i,j,:) )
 #ifdef __DO_SAFETY_CHECKS__
       do k = 2,nz
         if (znew(k) > zold(1)) then
           write(0,*) 'zOld=',zold
           write(0,*) 'zNew=',znew
           call mom_error( fatal, 'MOM_regridding, build_rho_grid: '//&
                'interior interface above surface!' )
         endif
         if (znew(k) > znew(k-1)) then
           write(0,*) 'zOld=',zold
           write(0,*) 'zNew=',znew
           call mom_error( fatal, 'MOM_regridding, build_rho_grid: '//&
                'interior interfaces cross!' )
         endif
       enddo
 #endif
 #ifdef __DO_SAFETY_CHECKS__
       dh=max(nominaldepth,totalthickness)
       if (abs(znew(1)-zold(1))>(nz-1)*0.5*epsilon(dh)*dh) then
         write(0,*) 'min_thickness=',cs%min_thickness
         write(0,*) 'nominalDepth=',nominaldepth,'totalThickness=',totalthickness
         write(0,*) 'zNew(1)-zOld(1) = ',znew(1)-zold(1),epsilon(dh),nz
         do k=1,nz+1
           write(0,*) k,zold(k),znew(k)
         enddo
         do k=1,nz
           write(0,*) k,h(i,j,k),znew(k)-znew(k+1)
         enddo
         call mom_error( fatal, &
                'MOM_regridding, build_rho_grid: top surface has moved!!!' )
       endif
 #endif
     end do  ! end loop on i
   end do  ! end loop on j
subroutine mom_regridding::build_sigma_grid (type(regridding_cs), intent(in) CS, type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, real, dimension(szi_(g),szj_(g),szk_(gv)), intent(in) h, real, dimension(szi_(g),szj_(g), szk_(gv)+1), intent(inout) dzInterface) private
Parameters
[in] cs Regridding control structure
[in] g Ocean grid structure
[in] gv ocean vertical grid structure
[in] h Layer thicknesses, in H
[in,out] dzinterface The change in interface depth in H.
Definition at line 729 of file MOM_regridding.F90.
References filtered_grid_motion(), and mom_error_handler::mom_error().
Referenced by regridding_main().
 !------------------------------------------------------------------------------
 ! This routine builds a grid based on terrain-following coordinates.
 ! The module parameter coordinateResolution(:) determines the resolution in
 ! sigma coordinate, dSigma(:). sigma-coordinates are defined by
 !   sigma = (eta-z)/(H+eta)  s.t. sigma=0 at z=eta and sigma=1 at z=-H .
 !------------------------------------------------------------------------------
   ! Arguments
   type(regridding_cs),                          intent(in)    :: cs !< Regridding control structure
   type(ocean_grid_type),                        intent(in)    :: g  !< Ocean grid structure
   type(verticalgrid_type),                      intent(in)    :: gv !< ocean vertical grid structure
   real, dimension(SZI_(G),SZJ_(G),SZK_(GV)),    intent(in)    :: h  !< Layer thicknesses, in H
   real, dimension(SZI_(G),SZJ_(G), SZK_(GV)+1), intent(inout) :: dzinterface !< The change in interface depth in H.
   ! Local variables
   integer :: i, j, k
   integer :: nz
   real    :: nominaldepth, totalthickness, dh
   real, dimension(SZK_(GV)+1) :: zold, znew
   nz = gv%ke
   do i = g%isc-1,g%iec+1
     do j = g%jsc-1,g%jec+1
       ! Determine water column height
       totalthickness = 0.0
       do k = 1,nz
         totalthickness = totalthickness + h(i,j,k)
       end do
       ! The rest of the model defines grids integrating up from the bottom
       nominaldepth = g%bathyT(i,j)*gv%m_to_H
       zold(nz+1) = - nominaldepth
       znew(nz+1) = - nominaldepth
       do k = nz,1,-1
         znew(k) = znew(k+1) + ( totalthickness * cs%coordinateResolution(k) )
         ! Adjust interface position to accomodate inflating layers
         ! without disturbing the interface above
         if ( znew(k) < (znew(k+1) + cs%min_thickness) ) then
           znew(k) = znew(k+1) + cs%min_thickness
         endif
         zold(k) = zold(k+1) + h(i,j,k)
       enddo
       ! Calculate the final change in grid position after blending new and old grids
       call filtered_grid_motion( cs, nz, zold, znew, dzinterface(i,j,:) )
 #ifdef __DO_SAFETY_CHECKS__
       dh=max(nominaldepth,totalthickness)
       if (abs(znew(1)-zold(1))>(nz-1)*0.5*epsilon(dh)*dh) then
         write(0,*) 'min_thickness=',cs%min_thickness
         write(0,*) 'nominalDepth=',nominaldepth,'totalThickness=',totalthickness
         write(0,*) 'dzInterface(1) = ',dzinterface(i,j,1),epsilon(dh),nz
         do k=1,nz+1
           write(0,*) k,zold(k),znew(k)
         enddo
         do k=1,nz
           write(0,*) k,h(i,j,k),znew(k)-znew(k+1),totalthickness*cs%coordinateResolution(k),cs%coordinateResolution(k)
         enddo
         call mom_error( fatal, &
                'MOM_regridding, build_sigma_grid: top surface has moved!!!' )
       endif
       dzinterface(i,j,1) = 0.
       dzinterface(i,j,nz+1) = 0.
 #endif
     end do
   end do
subroutine, public mom_regridding::build_zstar_column (type(regridding_cs), intent(in) CS, integer, intent(in) nz, real, intent(in) depth, real, intent(in) total_thickness, real, dimension(nz+1), intent(inout) zInterface, real, intent(in), optional z_rigid_top, real, intent(in), optional eta_orig)
Builds a z* coordinate with a minimum thickness.
Parameters
[in] cs Regridding control structure
[in] nz Number of levels
[in] depth Depth of ocean bottom (positive in m)
[in] total_thickness Column thickness (positive in m)
[in,out] zinterface Absolute positions of interfaces
[in] z_rigid_top The height of a rigid top (negative in m)
[in] eta_orig The actual original height of the top (m)
Definition at line 654 of file MOM_regridding.F90.
Referenced by build_zstar_grid(), and mom_diag_mediator::diag_update_target_grids().
   type(regridding_cs),   intent(in)    :: cs !< Regridding control structure
   integer,               intent(in)    :: nz !< Number of levels
   real,                  intent(in)    :: depth !< Depth of ocean bottom (positive in m)
   real,                  intent(in)    :: total_thickness !< Column thickness (positive in m)
   real, dimension(nz+1), intent(inout) :: zinterface !< Absolute positions of interfaces
   real, optional,        intent(in)    :: z_rigid_top !< The height of a rigid top (negative in m)
   real, optional,        intent(in)    :: eta_orig !< The actual original height of the top (m)
   ! Local variables
   real :: eta, stretching, dh, min_thickness, z0_top, z_star
   integer :: k
   logical :: new_zstar_def
   new_zstar_def = .false.
   min_thickness = min( cs%min_thickness, total_thickness/real(nz) )
   z0_top = 0.
   if (present(z_rigid_top)) then
     z0_top = z_rigid_top
     new_zstar_def = .true.
   endif
   ! Position of free-surface (or the rigid top, for which eta ~ z0_top)
   eta = total_thickness - depth
   if (present(eta_orig)) eta = eta_orig
   ! Conventional z* coordinate:
   !   z* = (z-eta) / stretching   where stretching = (H+eta)/H
   !   z = eta + stretching * z*
   ! The above gives z*(z=eta) = 0, z*(z=-H) = -H.
   ! With a rigid top boundary at eta = z0_top then
   !   z* = z0 + (z-eta) / stretching   where stretching = (H+eta)/(H+z0)
   !   z = eta + stretching * (z*-z0) * stretching
   stretching = total_thickness / ( depth + z0_top )
   if (new_zstar_def) then
     ! z_star is the notional z* coordinate in absence of upper/lower topography
     z_star = 0. ! z*=0 at the free-surface
     zinterface(1) = eta ! The actual position of the top of the column
     do k = 2,nz
       z_star = z_star - cs%coordinateResolution(k-1)
       ! This ensures that z is below a rigid upper surface (ice shelf bottom)
       zinterface(k) = min( eta + stretching * ( z_star - z0_top ), z0_top )
       ! This ensures that the layer in inflated
       zinterface(k) = min( zinterface(k), zinterface(k-1) - min_thickness )
       ! This ensures that z is above or at the topography
       zinterface(k) = max( zinterface(k), -depth + real(nz+1-k) * min_thickness )
     enddo
     zinterface(nz+1) = -depth
   else
     ! Integrate down from the top for a notional new grid, ignoring topography
     ! The starting position is offset by z0_top which, if z0_top<0, will place
     ! interfaces above the rigid boundary.
     zinterface(1) = eta
     do k = 1,nz
       dh = stretching * cs%coordinateResolution(k) ! Notional grid spacing
       zinterface(k+1) = zinterface(k) - dh
     enddo
     ! Integrating up from the bottom adjusting interface position to accommodate
     ! inflating layers without disturbing the interface above
     zinterface(nz+1) = -depth
     do k = nz,1,-1
       if ( zinterface(k) < (zinterface(k+1) + min_thickness) ) then
         zinterface(k) = zinterface(k+1) + min_thickness
       endif
     enddo
   endif
subroutine mom_regridding::build_zstar_grid (type(regridding_cs), intent(in) CS, type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, real, dimension(szi_(g),szj_(g),szk_(gv)), intent(in) h, real, dimension(szi_(g),szj_(g), szk_(gv)+1), intent(inout) dzInterface) private
Builds a z*-ccordinate grid with partial steps (Adcroft and Campin, 2004). z* is defined as z* = (z-eta)/(H+eta)*H s.t. z*=0 when z=eta and z*=-H when z=-H .
Parameters
[in] cs Regridding control structure
[in] g Ocean grid structure
[in] gv ocean vertical grid structure
[in] h Layer thicknesses, in H
[in,out] dzinterface The change in interface depth in H.
Definition at line 574 of file MOM_regridding.F90.
References adjust_interface_motion(), build_zstar_column(), filtered_grid_motion(), and mom_error_handler::mom_error().
Referenced by regridding_main().
   ! Arguments
   type(regridding_cs),                          intent(in)    :: cs !< Regridding control structure
   type(ocean_grid_type),                        intent(in)    :: g  !< Ocean grid structure
   type(verticalgrid_type),                      intent(in)    :: gv !< ocean vertical grid structure
   real, dimension(SZI_(G),SZJ_(G),SZK_(GV)),    intent(in)    :: h  !< Layer thicknesses, in H
   real, dimension(SZI_(G),SZJ_(G), SZK_(GV)+1), intent(inout) :: dzinterface !< The change in interface depth in H.
   ! Local variables
   integer :: i, j, k
   integer :: nz
   real    :: nominaldepth, totalthickness, dh
   real, dimension(SZK_(GV)+1) :: zold, znew
   real :: minthickness
   nz = gv%ke
   minthickness = cs%min_thickness
 !$OMP parallel do default(none) shared(G,GV,dzInterface,CS,nz,h)                 &
 !$OMP                          private(nominalDepth,totalThickness,minThickness, &
 !$OMP                                  zNew,dh,zOld)
   do j = g%jsc-1,g%jec+1
     do i = g%isc-1,g%iec+1
       if (g%mask2dT(i,j)==0.) then
         dzinterface(i,j,:) = 0.
         cycle
       endif
       ! Local depth (G%bathyT is positive)
       nominaldepth = g%bathyT(i,j)*gv%m_to_H
       ! Determine water column thickness
       totalthickness = 0.0
       do k = 1,nz
         totalthickness = totalthickness + h(i,j,k)
       end do
       zold(nz+1) = - nominaldepth
       do k = nz,1,-1
         zold(k) = zold(k+1) + h(i,j,k)
       enddo
       if (totalthickness-nominaldepth<cs%height_of_rigid_surface) then
         call build_zstar_column(cs, nz, nominaldepth, totalthickness, znew, &
                                 z_rigid_top = totalthickness-nominaldepth, &
                                 eta_orig = zold(1))
       else
         call build_zstar_column(cs, nz, nominaldepth, totalthickness, znew)
       endif
       ! Calculate the final change in grid position after blending new and old grids
       call filtered_grid_motion( cs, nz, zold, znew, dzinterface(i,j,:) )
 #ifdef __DO_SAFETY_CHECKS__
       dh=max(nominaldepth,totalthickness)
       if (abs(znew(1)-zold(1))>(nz-1)*0.5*epsilon(dh)*dh) then
         write(0,*) 'min_thickness=',minthickness
         write(0,*) 'nominalDepth=',nominaldepth,'totalThickness=',totalthickness
         write(0,*) 'dzInterface(1) = ',dzinterface(i,j,1),epsilon(dh),nz
         do k=1,nz+1
           write(0,*) k,zold(k),znew(k)
         enddo
         do k=1,nz
           write(0,*) k,h(i,j,k),znew(k)-znew(k+1),cs%coordinateResolution(k)
         enddo
         call mom_error( fatal, &
                'MOM_regridding, build_zstar_grid(): top surface has moved!!!' )
       endif
 #endif
       call adjust_interface_motion( nz, cs%min_thickness, h(i,j,:), dzinterface(i,j,:) )
     end do
   end do
subroutine mom_regridding::calc_h_new_by_dz (type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, real, dimension(szi_(g),szj_(g),szk_(gv)), intent(in) h, real, dimension(szi_(g),szj_(g),szk_(gv)+1), intent(in) dzInterface, real, dimension(szi_(g),szj_(g),szk_(gv)), intent(inout) h_new) private
Calculates h_new from h + delta_k dzInterface.
Parameters
[in] g Grid structure
[in] gv Ocean vertical grid structure
[in] h Old layer thicknesses (m)
[in] dzinterface Change in interface positions (m)
[in,out] h_new New layer thicknesses (m)
Definition at line 339 of file MOM_regridding.F90.
Referenced by regridding_main().
   type(ocean_grid_type),                      intent(in)    :: g !< Grid structure
   type(verticalgrid_type),                    intent(in)    :: gv !< Ocean vertical grid structure
   real, dimension(SZI_(G),SZJ_(G),SZK_(GV)),   intent(in)    :: h !< Old layer thicknesses (m)
   real, dimension(SZI_(G),SZJ_(G),SZK_(GV)+1), intent(in)    :: dzinterface !< Change in interface positions (m)
   real, dimension(SZI_(G),SZJ_(G),SZK_(GV)),   intent(inout) :: h_new !< New layer thicknesses (m)
   ! Local variables
   integer :: i, j, k
 !$OMP parallel do default(none) shared(G,GV,h,dzInterface,h_new)
   do j = g%jsc-1,g%jec+1
     do i = g%isc-1,g%iec+1
       if (g%mask2dT(i,j)>0.) then
         do k=1,gv%ke
           h_new(i,j,k) = max( 0., h(i,j,k) + ( dzinterface(i,j,k) - dzinterface(i,j,k+1) ) )
         enddo
       else
         h_new(i,j,:) = h(i,j,:)
       endif
     enddo
   enddo
subroutine, public mom_regridding::check_grid_column (integer, intent(in) nk, real, intent(in) depth, real, dimension(nk), intent(in) h, real, dimension(nk+1), intent(in) dzInterface, character(len=*), intent(in) msg)
Check that the total thickness of new and old grids are consistent.
Parameters
[in] nk Number of cells
[in] depth Depth of bottom (m)
[in] h Cell thicknesses (m)
[in] dzinterface Change in interface positions (m)
[in] msg Message to append to errors
Definition at line 383 of file MOM_regridding.F90.
References mom_error_handler::mom_error().
Referenced by check_remapping_grid().
   integer,               intent(in) :: nk !< Number of cells
   real,                  intent(in) :: depth !< Depth of bottom (m)
   real, dimension(nk),   intent(in) :: h !< Cell thicknesses (m)
   real, dimension(nk+1), intent(in) :: dzinterface !< Change in interface positions (m)
   character(len=*),      intent(in) :: msg !< Message to append to errors
   ! Local variables
   integer :: k
   real    :: eps, total_h_old, total_h_new, h_new, z_old, z_new
   eps =1. ; eps = epsilon(eps)
   ! Total thickness of grid h
   total_h_old = 0.
   do k = 1,nk
     total_h_old = total_h_old + h(k)
   enddo
   ! Integrate upwards for the interfaces consistent with the rest of MOM6
   z_old = - depth
   if (depth == 0.) z_old = - total_h_old
   total_h_new = 0.
   do k = nk,1,-1
     z_old = z_old + h(k) ! Old interface position above layer k
     z_new = z_old + dzinterface(k) ! New interface position based on dzInterface
     h_new = h(k) + ( dzinterface(k) - dzinterface(k+1) ) ! New thickness
     if (h_new<0.) then
       write(0,*) 'k,h,hnew=',k,h(k),h_new
       write(0,*) 'dzI(k+1),dzI(k)=',dzinterface(k+1),dzinterface(k)
       call mom_error( fatal, 'MOM_regridding, check_grid_column: '//&
         'Negative layer thickness implied by re-gridding, '//trim(msg))
     endif
     total_h_new = total_h_new + h_new
   enddo
   ! Conservation by implied h_new
   if (abs(total_h_new-total_h_old)>real(nk-1)*0.5*(total_h_old+total_h_new)*eps) then
     write(0,*) 'nk=',nk
     do k = 1,nk
       write(0,*) 'k,h,hnew=',k,h(k),h(k)+(dzinterface(k)-dzinterface(k+1))
     enddo
     write(0,*) 'Hold,Hnew,Hnew-Hold=',total_h_old,total_h_new,total_h_new-total_h_old
     write(0,*) 'eps,(n)/2*eps*H=',eps,real(nk-1)*0.5*(total_h_old+total_h_new)*eps
     call mom_error( fatal, 'MOM_regridding, check_grid_column: '//&
       'Re-gridding did NOT conserve total thickness to within roundoff '//trim(msg))
   endif
   ! Check that the top and bottom are intentionally moving
   if (dzinterface(1) /= 0.) call mom_error( fatal, &
     'MOM_regridding, check_grid_column: Non-zero dzInterface at surface! '//trim(msg))
   if (dzinterface(nk+1) /= 0.) call mom_error( fatal, &
     'MOM_regridding, check_grid_column: Non-zero dzInterface at bottom! '//trim(msg))
subroutine, public mom_regridding::check_remapping_grid (type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, real, dimension(szi_(g),szj_(g),szk_(gv)), intent(in) h, real, dimension(szi_(g),szj_(g),szk_(gv)+1), intent(in) dzInterface, character(len=*), intent(in) msg)
Check that the total thickness of two grids match.
Parameters
[in] g Grid structure
[in] gv Ocean vertical grid structure
[in] h Layer thicknesses (m)
[in] dzinterface Change in interface positions (m)
[in] msg Message to append to errors
Definition at line 364 of file MOM_regridding.F90.
References check_grid_column().
Referenced by regridding_main().
   type(ocean_grid_type),                       intent(in) :: g !< Grid structure
   type(verticalgrid_type),                     intent(in) :: gv !< Ocean vertical grid structure
   real, dimension(SZI_(G),SZJ_(G),SZK_(GV)),   intent(in) :: h !< Layer thicknesses (m)
   real, dimension(SZI_(G),SZJ_(G),SZK_(GV)+1), intent(in) :: dzinterface !< Change in interface positions (m)
   character(len=*),                            intent(in) :: msg !< Message to append to errors
   ! Local variables
   integer :: i, j
 !$OMP parallel do default(none) shared(G,GV,h,dzInterface,msg)
   do j = g%jsc-1,g%jec+1
     do i = g%isc-1,g%iec+1
       if (g%mask2dT(i,j)>0.) call check_grid_column( gv%ke, g%bathyT(i,j), h(i,j,:), dzinterface(i,j,:), msg )
     enddo
   enddo
subroutine mom_regridding::convective_adjustment (type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, real, dimension(szi_(g),szj_(g),szk_(gv)), intent(inout) h, type(thermo_var_ptrs), intent(inout) tv) private
Definition at line 2360 of file MOM_regridding.F90.
Referenced by regridding_main().
 !------------------------------------------------------------------------------
 ! Check each water column to see whether it is stratified. If not, sort the
 ! layers by successive swappings of water masses (bubble sort algorithm)
 !------------------------------------------------------------------------------
   ! Arguments
   type(ocean_grid_type), intent(in)                  :: g
   type(verticalgrid_type), intent(in)                :: gv
   real, dimension(SZI_(G),SZJ_(G),SZK_(GV)), intent(inout) :: h
   type(thermo_var_ptrs), intent(inout)               :: tv
   ! Local variables
   integer   :: i, j, k
   real      :: t0, t1       ! temperatures
   real      :: s0, s1       ! salinities
   real      :: r0, r1       ! densities
   real      :: h0, h1
   logical   :: stratified
   real, dimension(GV%ke) :: p_col, densities
   p_col(:) = 0.
   ! Loop on columns
   do j = g%jsc-1,g%jec+1 ; do i = g%isc-1,g%iec+1
     ! Compute densities within current water column
     call calculate_density( tv%T(i,j,:), tv%S(i,j,:), p_col, &
                             densities, 1, gv%ke, tv%eqn_of_state )
     ! Repeat restratification until complete
     do
       stratified = .true.
       do k = 1,gv%ke-1
         ! Gather information of current and next cells
         t0 = tv%T(i,j,k)  ; t1 = tv%T(i,j,k+1)
         s0 = tv%S(i,j,k)  ; s1 = tv%S(i,j,k+1)
         r0 = densities(k) ; r1 = densities(k+1)
         h0 = h(i,j,k) ; h1 = h(i,j,k+1)
         ! If the density of the current cell is larger than the density
         ! below it, we swap the cells and recalculate the densitiies
         ! within the swapped cells
         if ( r0 > r1 ) then
           tv%T(i,j,k) = t1 ; tv%T(i,j,k+1) = t0
           tv%S(i,j,k) = s1 ; tv%S(i,j,k+1) = s0
           h(i,j,k)    = h1 ; h(i,j,k+1)    = h0
           ! Recompute densities at levels k and k+1
           call calculate_density( tv%T(i,j,k), tv%S(i,j,k), p_col(k), &
                                   densities(k), tv%eqn_of_state )
           call calculate_density( tv%T(i,j,k+1), tv%S(i,j,k+1), p_col(k+1), &
                                   densities(k+1), tv%eqn_of_state )
           stratified = .false.
         end if
       enddo  ! k
       if ( stratified ) exit
     enddo
   enddo ; enddo  ! i & j
subroutine, public mom_regridding::end_regridding (type(regridding_cs), intent(inout) CS)
Deallocation of regridding memory.
Parameters
[in,out] cs Regridding control structure
Definition at line 259 of file MOM_regridding.F90.
References regridding_memory_deallocation().
   type(regridding_cs), intent(inout) :: cs !< Regridding control structure
   call regridding_memory_deallocation( cs )
subroutine mom_regridding::filtered_grid_motion (type(regridding_cs), intent(in) CS, integer, intent(in) nk, real, dimension(nk+1), intent(in) z_old, real, dimension(nk+1), intent(in) z_new, real, dimension(nk+1), intent(inout) dz_g) private
Returns the change in interface position motion after filtering and assuming the top and bottom interfaces do not move. The filtering is a function of depth, and is applied as the integrated average filtering over the trajectory of the interface. By design, this code can not give tangled interfaces provided that z_old and z_new are not already tangled.
Parameters
[in] cs Regridding control structure
[in] nk Number of cells
[in] z_old Old grid position (m)
[in] z_new New grid position (m)
[in,out] dz_g Change in interface positions (m)
Definition at line 444 of file MOM_regridding.F90.
References mom_error_handler::mom_error().
Referenced by build_grid_hycom1(), build_grid_slight(), build_rho_grid(), build_sigma_grid(), and build_zstar_grid().
   type(regridding_cs),                           intent(in)    :: cs !< Regridding control structure
   integer,               intent(in)    :: nk !< Number of cells
   real, dimension(nk+1), intent(in)    :: z_old !< Old grid position (m)
   real, dimension(nk+1), intent(in)    :: z_new !< New grid position (m)
   real, dimension(nk+1), intent(inout) :: dz_g !< Change in interface positions (m)
   ! Local variables
   real :: sgn  ! The sign convention for downward.
   real :: dz_tgt, zr1
   real :: aq, bq, dz0, z0, f0
   real :: zs, zd, dzwt, idzwt
   real :: wtd, iwtd
   real :: int_zs, int_zd, dint_zs_zd
 ! For debugging:
   real, dimension(nk+1) :: z_act
 !  real, dimension(nk+1) :: ddz_g_s, ddz_g_d
   logical :: debug = .false.
   integer :: k
   if ((z_old(nk+1) - z_old(1)) * (z_new(nk+1) - z_new(1)) < 0.0) then
     call mom_error(fatal, "filtered_grid_motion: z_old and z_new use different sign conventions.")
   elseif ((z_old(nk+1) - z_old(1)) * (z_new(nk+1) - z_new(1)) == 0.0) then
     ! This is a massless column, so do nothing and return.
     do k=1,nk+1 ; dz_g(k) = 0.0 ; enddo ; return
   elseif ((z_old(nk+1) - z_old(1)) + (z_new(nk+1) - z_new(1)) > 0.0) then
     sgn = 1.0
   else
     sgn = -1.0
   endif
   if (debug) then
     do k=2,nk+1
       if (sgn*(z_new(k)-z_new(k-1)) < -5e-16*(abs(z_new(k))+abs(z_new(k-1))) ) &
         call mom_error(fatal, "filtered_grid_motion: z_new is tangled.")
       if (sgn*(z_old(k)-z_old(k-1)) < -5e-16*(abs(z_old(k))+abs(z_old(k-1))) ) &
         call mom_error(fatal, "filtered_grid_motion: z_old is tangled.")
     enddo
     ! ddz_g_s(:) = 0.0 ; ddz_g_d(:) = 0.0
   endif
   zs = cs%depth_of_time_filter_shallow
   zd = cs%depth_of_time_filter_deep
   wtd = 1.0 - cs%old_grid_weight
   iwtd = 1.0 / wtd
   dzwt = (zd - zs)
   idzwt = 0.0 ; if (abs(zd - zs) > 0.0) idzwt = 1.0 / (zd - zs)
   dint_zs_zd = 0.5*(1.0 + iwtd) * (zd - zs)
   aq = 0.5*(iwtd - 1.0)
   dz_g(1) = 0.0
   do k = 2,nk
     ! zr1 is positive and increases with depth, and dz_tgt is positive downward.
     dz_tgt = sgn*(z_new(k) - z_old(k))
     zr1 = sgn*(z_old(k) - z_old(1))
     !   First, handle the two simple and common cases that do not pass through
     ! the adjustment rate transition zone.
     if ((zr1 > zd) .and. (zr1 + wtd * dz_tgt > zd)) then
       dz_g(k) = sgn * wtd * dz_tgt
     elseif ((zr1 < zs) .and. (zr1 + dz_tgt < zs)) then
       dz_g(k) = sgn * dz_tgt
     else
       ! Find the new value by inverting the equation
       !   integral(0 to dz_new) Iwt(z) dz = dz_tgt
       ! This is trivial where Iwt is a constant, and agrees with the two limits above.
       ! Take test values at the transition points to figure out which segment
       ! the new value will be found in.
       if (zr1 >= zd) then
         int_zd = iwtd*(zd - zr1)
         int_zs = int_zd - dint_zs_zd
       elseif (zr1 <= zs) then
         int_zs = (zs - zr1)
         int_zd = dint_zs_zd + (zs - zr1)
       else
 !        Int_zd = (zd - zr1) * (Iwtd + 0.5*(1.0 - Iwtd) * (zd - zr1) / (zd - zs))
         int_zd = (zd - zr1) * (iwtd*(0.5*(zd+zr1) - zs) + 0.5*(zd - zr1)) * idzwt
         int_zs = (zs - zr1) * (0.5*iwtd * ((zr1 - zs)) + (zd - 0.5*(zr1+zs))) * idzwt
         ! It has been verified that  Int_zs = Int_zd - dInt_zs_zd to within roundoff.
       endif
       if (dz_tgt >= int_zd) then ! The new location is in the deep, slow region.
         dz_g(k) = sgn * ((zd-zr1) + wtd*(dz_tgt - int_zd))
       elseif (dz_tgt <= int_zs) then ! The new location is in the shallow region.
         dz_g(k) = sgn * ((zs-zr1) + (dz_tgt - int_zs))
       else  ! We need to solve a quadratic equation for z_new.
         ! For accuracy, do the integral from the starting depth or the nearest
         ! edge of the transition region.  The results with each choice are
         ! mathematically equivalent, but differ in roundoff, and this choice
         ! should minimize the likelihood of inadvertently overlapping interfaces.
         if (zr1 <= zs) then ; dz0 = zs-zr1 ; z0 = zs ; f0 = dz_tgt - int_zs
         elseif (zr1 >= zd) then ; dz0 = zd-zr1 ; z0 = zd ; f0 = dz_tgt - int_zd
         else ; dz0 = 0.0 ; z0 = zr1 ; f0 = dz_tgt ; endif
         bq = (dzwt + 2.0*aq*(z0-zs))
         ! Solve the quadratic: Aq*(zn-z0)**2 + Bq*(zn-z0) - F0*dzwt = 0
         ! Note that b>=0, and the two terms in the standard form cancel for the right root.
         dz_g(k) = sgn * (dz0 + 2.0*f0*dzwt / (bq + sqrt(bq**2 + 4.0*aq*f0*dzwt) ))
 !       if (debug) then
 !         dz0 = zs-zr1 ; z0 = zs ; F0 = dz_tgt - Int_zs ; Bq = (dzwt + 2.0*Aq*(z0-zs))
 !         ddz_g_s(k) = sgn * (dz0 + 2.0*F0*dzwt / (Bq + sqrt(Bq**2 + 4.0*Aq*F0*dzwt) )) - dz_g(k)
 !         dz0 = zd-zr1 ; z0 = zd ; F0 = dz_tgt - Int_zd ; Bq = (dzwt + 2.0*Aq*(z0-zs))
 !         ddz_g_d(k) = sgn * (dz0 + 2.0*F0*dzwt / (Bq + sqrt(Bq**2 + 4.0*Aq*F0*dzwt) )) - dz_g(k)
 !
 !         if (abs(ddz_g_s(k)) > 1e-12*(abs(dz_g(k)) + abs(dz_g(k)+ddz_g_s(k)))) &
 !           call MOM_error(WARNING, "filtered_grid_motion: Expect z_output to be tangled (sc).")
 !         if (abs(ddz_g_d(k) - ddz_g_s(k)) > 1e-12*(abs(dz_g(k)+ddz_g_d(k)) + abs(dz_g(k)+ddz_g_s(k)))) &
 !           call MOM_error(WARNING, "filtered_grid_motion: Expect z_output to be tangled.")
 !       endif
       endif
     endif
   enddo
   dz_g(nk+1) = 0.0
   if (debug) then
     do k=1,nk+1 ; z_act(k) = z_old(k) + dz_g(k) ; enddo
     do k=2,nk+1
       if (sgn*((z_act(k))-z_act(k-1)) < -1e-15*(abs(z_act(k))+abs(z_act(k-1))) ) &
         call mom_error(fatal, "filtered_grid_motion: z_output is tangled.")
     enddo
   endif
real function mom_regridding::get_polynomial_coordinate (integer, intent(in) N, real, dimension(:), intent(in) h, real, dimension(:), intent(in) x_g, real, dimension(:,:), intent(in) ppoly_E, real, dimension(:,:), intent(in) ppoly_coefficients, real, intent(in) target_value, integer, intent(in) degree) private
Returns
The position of x_g at which target_value is found.
Definition at line 2097 of file MOM_regridding.F90.
References nr_iterations, nr_offset, and nr_tolerance.
Referenced by interpolate_grid().
 ! ------------------------------------------------------------------------------
 ! Here, 'ppoly' is assumed to be a piecewise discontinuous polynomial of degree
 ! 'degree' throughout the domain defined by 'grid'. A target value is given
 ! and we need to determine the corresponding grid coordinate to define the
 ! new grid.
 !
 ! If the target value is out of range, the grid coordinate is simply set to
 ! be equal to one of the boundary coordinates, which results in vanished layers
 ! near the boundaries.
 !
 ! IT IS ASSUMED THAT THE PIECEWISE POLYNOMIAL IS MONOTONICALLY INCREASING.
 ! IF THIS IS NOT THE CASE, THE NEW GRID MAY BE ILL-DEFINED.
 !
 ! It is assumed that the number of cells defining 'grid' and 'ppoly' are the
 ! same.
 ! ------------------------------------------------------------------------------
   ! Arguments
   integer,              intent(in) :: n     ! The number of grid cells
   real, dimension(:),   intent(in) :: h     ! Grid cell thicknesses    (size N)
   real, dimension(:),   intent(in) :: x_g   ! Grid interface locations (size N+1)
   real, dimension(:,:), intent(in) :: ppoly_e  !Edge value of polynomial
   real, dimension(:,:), intent(in) :: ppoly_coefficients !Coefficients of polynomial
   real,                 intent(in) :: target_value
   integer,              intent(in) :: degree ! The degree of the polynomials
   real :: x_tgt      !< The position of x_g at which target_value is found.
   ! Local variables
   integer            :: i, k            ! loop indices
   integer            :: k_found         ! index of target cell
   integer            :: iter
   real               :: xi0             ! normalized target coordinate
   real, dimension(5) :: a               ! polynomial coefficients
   real               :: numerator
   real               :: denominator
   real               :: delta           ! Newton-Raphson increment
   real               :: x               ! global target coordinate
   real               :: eps                 ! offset used to get away from
                                         ! boundaries
   real               :: grad            ! gradient during N-R iterations
   eps = nr_offset
   k_found = -1
   ! If the target value is outside the range of all values, we
   ! force the target coordinate to be equal to the lowest or
   ! largest value, depending on which bound is overtaken
   if ( target_value <= ppoly_e(1,1) ) then
     x_tgt = x_g(1)
     return  ! return because there is no need to look further
   end if
   ! Since discontinuous edge values are allowed, we check whether the target
   ! value lies between two discontinuous edge values at interior interfaces
   do k = 2,n
     if ( ( target_value >= ppoly_e(k-1,2) ) .AND. &
       ( target_value <= ppoly_e(k,1) ) ) then
       x_tgt = x_g(k)
       return   ! return because there is no need to look further
       exit
     end if
   end do
   ! If the target value is outside the range of all values, we
   ! force the target coordinate to be equal to the lowest or
   ! largest value, depending on which bound is overtaken
   if ( target_value >= ppoly_e(n,2) ) then
     x_tgt = x_g(n+1)
     return  ! return because there is no need to look further
   end if
   ! At this point, we know that the target value is bounded and does not
   ! lie between discontinuous, monotonic edge values. Therefore,
   ! there is a unique solution. We loop on all cells and find which one
   ! contains the target value. The variable k_found holds the index value
   ! of the cell where the taregt value lies.
   do k = 1,n
     if ( ( target_value > ppoly_e(k,1) ) .AND. &
          ( target_value < ppoly_e(k,2) ) ) then
       k_found = k
       exit
     end if
   end do
   ! At this point, 'k_found' should be strictly positive. If not, this is
   ! a major failure because it means we could not find any target cell
   ! despite the fact that the target value lies between the extremes. It
   ! means there is a major problem with the interpolant. This needs to be
   ! reported.
   if ( k_found == -1 ) then
       write(*,*) target_value, ppoly_e(1,1), ppoly_e(n,2)
       write(*,*) 'Could not find target coordinate in ' //&
                  '"get_polynomial_coordinate". This is caused by an '//&
                  'inconsistent interpolant (perhaps not monotonically '//&
                  'increasing)'
       call mom_error( fatal, 'Aborting execution' )
   end if
   ! Reset all polynomial coefficients to 0 and copy those pertaining to
   ! the found cell
   a(:) = 0.0
   do i = 1,degree+1
     a(i) = ppoly_coefficients(k_found,i)
   end do
   ! Guess value to start Newton-Raphson iterations (middle of cell)
   xi0 = 0.5
   iter = 1
   delta = 1e10
   ! Newton-Raphson iterations
   do
     if ( ( iter > nr_iterations ) .OR. &
          ( abs(delta) < nr_tolerance ) ) then
       exit
     end if
     numerator = a(1) + a(2)*xi0 + a(3)*xi0*xi0 + a(4)*xi0*xi0*xi0 + &
                 a(5)*xi0*xi0*xi0*xi0 - target_value
     denominator = a(2) + 2*a(3)*xi0 + 3*a(4)*xi0*xi0 + 4*a(5)*xi0*xi0*xi0
     delta = - ( numerator ) / &
               ( denominator )
     xi0 = xi0 + delta
     ! Check whether new estimate is out of bounds. If the new estimate is
     ! indeed out of bounds, we manually set it to be equal to the overtaken
     ! bound with a small offset towards the interior when the gradient of
     ! the function at the boundary is zero (in which case, the Newton-Raphson
     ! algorithm does not converge).
     if ( xi0 < 0.0 ) then
       xi0 = 0.0
       grad = a(2)
       if ( grad == 0.0 ) xi0 = xi0 + eps
     end if
     if ( xi0 > 1.0 ) then
       xi0 = 1.0
       grad = a(2) + 2*a(3) + 3*a(4) + 4*a(5)
       if ( grad == 0.0 ) xi0 = xi0 - eps
     end if
     iter = iter + 1
   end do ! end Newton-Raphson iterations
   x_tgt = x_g(k_found) + xi0 * h(k_found)
real function, dimension(cs%nk+1), public mom_regridding::getcoordinateinterfaces (type(regridding_cs), intent(in) CS)
Query the target coordinate interface positions.
Parameters
[in] cs Regridding control structure
Returns
Interface positions in target coordinate
Definition at line 2564 of file MOM_regridding.F90.
   type(regridding_cs), intent(in) :: cs                      !< Regridding control structure
   real, dimension(CS%nk+1)        :: getcoordinateinterfaces !< Interface positions in target coordinate
   integer :: k
   ! When using a coordinate with target densities, we need to get the actual
   ! densities, rather than computing the interfaces based on resolution
   if (cs%regridding_scheme == regridding_rho) then
     if (.not. cs%target_density_set) &
       call mom_error(fatal, 'MOM_regridding, getCoordinateInterfaces: '//&
                             'target densities not set!')
     getcoordinateinterfaces(:) = cs%target_density(:)
   else
     getcoordinateinterfaces(1) = 0.
     do k = 1, cs%nk
       getcoordinateinterfaces(k+1) = getcoordinateinterfaces(k) &
                                     -cs%coordinateResolution(k)
     enddo
     ! The following line has an "abs()" to allow ferret users to reference
     ! data by index. It is a temporary work around...  :(  -AJA
     getcoordinateinterfaces(:) = abs( getcoordinateinterfaces(:) )
   end if
real function, dimension(cs%nk), public mom_regridding::getcoordinateresolution (type(regridding_cs), intent(in) CS)
Definition at line 2555 of file MOM_regridding.F90.
   type(regridding_cs), intent(in) :: cs
   real, dimension(CS%nk)          :: getcoordinateresolution
   getcoordinateresolution(:) = cs%coordinateResolution(:)
character(len=20) function, public mom_regridding::getcoordinateshortname (type(regridding_cs), intent(in) CS)
Definition at line 2617 of file MOM_regridding.F90.
   type(regridding_cs), intent(in) :: cs
   character(len=20)               :: getcoordinateshortname
   select case ( cs%regridding_scheme )
     case ( regridding_zstar )
       !getCoordinateShortName = 'z*'
       ! The following line is a temporary work around...  :(  -AJA
       getcoordinateshortname = 'pseudo-depth, -z*'
     case ( regridding_sigma )
       getcoordinateshortname = 'sigma'
     case ( regridding_rho )
       getcoordinateshortname = 'rho'
     case ( regridding_arbitrary )
       getcoordinateshortname = 'coordinate'
     case ( regridding_hycom1 )
       getcoordinateshortname = 'z-rho'
     case ( regridding_slight )
       getcoordinateshortname = 's-rho'
     case default
       call mom_error(fatal,'MOM_regridding, getCoordinateShortName: '//&
                      'Unknown regridding scheme selected!')
   end select ! type of grid
character(len=20) function, public mom_regridding::getcoordinateunits (type(regridding_cs), intent(in) CS)
Definition at line 2594 of file MOM_regridding.F90.
   type(regridding_cs), intent(in) :: cs
   character(len=20)               :: getcoordinateunits
   select case ( cs%regridding_scheme )
     case ( regridding_zstar, regridding_hycom1, regridding_slight )
       getcoordinateunits = 'meter'
     case ( regridding_sigma )
       getcoordinateunits = 'fraction'
     case ( regridding_rho )
       getcoordinateunits = 'kg/m3'
     case ( regridding_arbitrary )
       getcoordinateunits = 'unknown'
     case default
       call mom_error(fatal,'MOM_regridding, getCoordinateUnits: '//&
                      'Unknown regridding scheme selected!')
   end select ! type of grid
real function, dimension(cs%nk), public mom_regridding::getstaticthickness (type(regridding_cs), intent(in) CS, real, intent(in) SSH, real, intent(in) depth)
Definition at line 2699 of file MOM_regridding.F90.
Referenced by mom_ale::ale_initthicknesstocoord().
   type(regridding_cs), intent(in) :: cs
   real,                intent(in) :: ssh
   real,                intent(in) :: depth
   real, dimension(CS%nk)          :: getstaticthickness
   ! Local
   integer :: k
   real :: z, dz
   select case ( cs%regridding_scheme )
     case ( regridding_zstar, regridding_hycom1, regridding_slight )
       if (depth>0.) then
         z = ssh
         do k = 1, cs%nk
           dz = cs%coordinateResolution(k) * ( 1. + ssh/depth ) ! Nominal dz*
           dz = max(dz, 0.)                                     ! Avoid negative incase ssh=-depth
           dz = min(dz, depth - z)                              ! Clip if below topography
           z = z + dz                                           ! Bottom of layer
           getstaticthickness(k) = dz
         enddo
       else
         getstaticthickness(:) = 0. ! On land ...
       endif
     case ( regridding_sigma )
       getstaticthickness(:) = cs%coordinateResolution(:) * ( depth + ssh )
     case ( regridding_rho )
       getstaticthickness(:) = 0. ! Not applicable
     case ( regridding_arbitrary )
       getstaticthickness(:) = 0.  ! Not applicable
     case default
       call mom_error(fatal,'MOM_regridding, getStaticThickness: '//&
                      'Unknown regridding scheme selected!')
   end select ! type of grid
subroutine, public mom_regridding::inflate_vanished_layers_old (type(regridding_cs), intent(in) CS, type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, real, dimension(szi_(g),szj_(g), szk_(gv)), intent(inout) h)
Definition at line 2256 of file MOM_regridding.F90.
References old_inflate_layers_1d().
 !------------------------------------------------------------------------------
 ! This routine is called when initializing the regridding options. The
 ! objective is to make sure all layers are at least as thick as the minimum
 ! thickness allowed for regridding purposes (this parameter is set in the
 ! MOM_input file or defaulted to 1.0e-3). When layers are too thin, they
 ! are inflated up to the minmum thickness.
 !------------------------------------------------------------------------------
   ! Arguments
   type(regridding_cs),                    intent(in)    :: cs
   type(ocean_grid_type),                  intent(in)    :: g
   type(verticalgrid_type),                intent(in)    :: gv
   real, dimension(SZI_(G),SZJ_(G), SZK_(GV)), intent(inout) :: h
   ! Local variables
   integer :: i, j, k
   real    :: htmp(gv%ke)
   do i = g%isc-1,g%iec+1
     do j = g%jsc-1,g%jec+1
       ! Build grid for current column
       do k = 1,gv%ke
         htmp(k) = h(i,j,k)
       end do
       call old_inflate_layers_1d( cs%min_thickness, gv%ke, htmp )
       ! Save modified grid
       do k = 1,gv%ke
         h(i,j,k) = htmp(k)
       end do
     end do
   end do
subroutine, public mom_regridding::initialize_regridding (integer, intent(in) nk, character(len=*), intent(in) coordMode, character(len=*), intent(in) interpScheme, type(regridding_cs), intent(inout) CS, real, intent(in), optional compressibility_fraction)
Initialization of regridding.
Parameters
[in] nk Number of levels
[in] coordmode Coordinate mode to use
[in] interpscheme Interpolation mode to use
[in,out] cs Regridding control structure
[in] compressibility_fraction Fraction of compressibility to add to potential density profiles (nondim)
Definition at line 221 of file MOM_regridding.F90.
References allocate_regridding(), interpolation_p1m_h2, interpolation_p1m_h4, interpolation_p1m_ih4, interpolation_p3m_ih4ih3, interpolation_p3m_ih6ih5, interpolation_plm, interpolation_ppm_h4, interpolation_ppm_ih4, interpolation_pqm_ih4ih3, interpolation_pqm_ih6ih5, mom_error_handler::mom_error(), regriddingdefaultboundaryextrapolation, regriddingdefaultminthickness, and mom_string_functions::uppercase().
   integer,               intent(in)    :: nk !< Number of levels
   character(len=*),      intent(in)    :: coordmode !< Coordinate mode to use
   character(len=*),      intent(in)    :: interpscheme !< Interpolation mode to use
   type(regridding_cs),   intent(inout) :: cs !< Regridding control structure
   real,        optional, intent(in)    :: compressibility_fraction !< Fraction of compressibility
                                           !! to add to potential density profiles (nondim)
   cs%nk = nk
   cs%regridding_scheme = coordinatemode(coordmode)
   select case ( uppercase(trim(interpscheme)) )
     case ("P1M_H2");     cs%interpolation_scheme = interpolation_p1m_h2
     case ("P1M_H4");     cs%interpolation_scheme = interpolation_p1m_h4
     case ("P1M_IH2");    cs%interpolation_scheme = interpolation_p1m_ih4
     case ("PLM");        cs%interpolation_scheme = interpolation_plm
     case ("PPM_H4");     cs%interpolation_scheme = interpolation_ppm_h4
     case ("PPM_IH4");    cs%interpolation_scheme = interpolation_ppm_ih4
     case ("P3M_IH4IH3"); cs%interpolation_scheme = interpolation_p3m_ih4ih3
     case ("P3M_IH6IH5"); cs%interpolation_scheme = interpolation_p3m_ih6ih5
     case ("PQM_IH4IH3"); cs%interpolation_scheme = interpolation_pqm_ih4ih3
     case ("PQM_IH6IH5"); cs%interpolation_scheme = interpolation_pqm_ih6ih5
     case default ; call mom_error(fatal, "read_regridding_options: "//&
      "Unrecognized choice for INTERPOLATION_SCHEME ("//trim(interpscheme)//").")
   end select
   cs%boundary_extrapolation = regriddingdefaultboundaryextrapolation
   cs%min_thickness = regriddingdefaultminthickness
   if (present(compressibility_fraction)) cs%compressibility_fraction = compressibility_fraction
   call allocate_regridding( cs )
subroutine mom_regridding::interpolate_grid (integer, intent(in) n0, real, dimension(:), intent(in) h0, real, dimension(:), intent(in) x0, real, dimension(:,:), intent(in) ppoly0_E, real, dimension(:,:), intent(in) ppoly0_coefficients, real, dimension(:), intent(in) target_values, integer, intent(in) degree, integer, intent(in) n1, real, dimension(:), intent(inout) h1, real, dimension(:), intent(inout) x1) private
Definition at line 2054 of file MOM_regridding.F90.
References get_polynomial_coordinate().
Referenced by build_grid_hycom1(), and build_rho_grid().
 ! ------------------------------------------------------------------------------
 ! Given the grid 'grid0' and the piecewise polynomial interpolant
 ! 'ppoly0' (possibly discontinuous), the coordinates of the new grid 'grid1'
 ! are determined by finding the corresponding target interface densities.
 ! ------------------------------------------------------------------------------
   ! Arguments
   integer,            intent(in)    :: n0
   real, dimension(:), intent(in)    :: h0
   real, dimension(:), intent(in)    :: x0
   real, dimension(:,:), intent(in)  :: ppoly0_e            !Edge value of polynomial
   real, dimension(:,:), intent(in)  :: ppoly0_coefficients !Coefficients of polynomial
   real, dimension(:), intent(in)    :: target_values
   integer,            intent(in)    :: degree
   integer,            intent(in)    :: n1
   real, dimension(:), intent(inout) :: h1
   real, dimension(:), intent(inout) :: x1
   ! Local variables
   integer        :: k   ! loop index
   real           :: t   ! current interface target density
   ! Make sure boundary coordinates of new grid coincide with boundary
   ! coordinates of previous grid
   x1(1) = x0(1)
   x1(n1+1) = x0(n0+1)
   ! Find coordinates for interior target values
   do k = 2,n1
     t = target_values(k)
     x1(k) = get_polynomial_coordinate( n0, h0, x0, ppoly0_e, ppoly0_coefficients, t, degree )
     h1(k-1) = x1(k) - x1(k-1)
   end do
   h1(n1) = x1(n1+1) - x1(n1)
subroutine mom_regridding::old_inflate_layers_1d (real, intent(in) minThickness, integer, intent(in) N, real, dimension(:), intent(inout) h) private
Definition at line 2298 of file MOM_regridding.F90.
Referenced by build_rho_grid(), and inflate_vanished_layers_old().
   ! Argument
   real,                intent(in) :: minthickness
   integer,             intent(in) :: n
   real,                intent(inout) :: h(:)
   ! Local variable
   integer   :: k
   integer   :: k_found
   integer   :: count_nonzero_layers
   real      :: delta
   real      :: correction
   real      :: maxthickness
   ! Count number of nonzero layers
   count_nonzero_layers = 0
   do k = 1,n
     if ( h(k) > minthickness ) then
       count_nonzero_layers = count_nonzero_layers + 1
     end if
   end do
   ! If all layer thicknesses are greater than the threshold, exit routine
   if ( count_nonzero_layers == n ) return
   ! If all thicknesses are zero, inflate them all and exit
   if ( count_nonzero_layers == 0 ) then
     do k = 1,n
       h(k) = minthickness
     end do
     return
   end if
   ! Inflate zero layers
   correction = 0.0
   do k = 1,n
     if ( h(k) <= minthickness ) then
       delta = minthickness - h(k)
       correction = correction + delta
       h(k) = h(k) + delta
     end if
   end do
   ! Modify thicknesses of nonzero layers to ensure volume conservation
   maxthickness = h(1)
   k_found = 1
   do k = 1,n
     if ( h(k) > maxthickness ) then
       maxthickness = h(k)
       k_found = k
     end if
   end do
   h(k_found) = h(k_found) - correction
subroutine, public mom_regridding::regridding_main (type(remapping_cs), intent(in) remapCS, type(regridding_cs), intent(in) CS, type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, real, dimension(szi_(g),szj_(g), szk_(gv)), intent(inout) h, type(thermo_var_ptrs), intent(inout) tv, real, dimension(szi_(g),szj_(g), szk_(gv)), intent(inout) h_new, real, dimension(szi_(g),szj_(g), szk_(gv)+1), intent(inout) dzInterface)
Parameters
[in] remapcs Remapping parameters and options
[in] cs Regridding control structure
[in] g Ocean grid structure
[in] gv Ocean vertical grid structure
[in,out] h Current 3D grid obtained after the last time step
[in,out] tv Thermodynamical variables (T, S, ...)
[in,out] h_new New 3D grid consistent with target coordinate
[in,out] dzinterface The change in position of each interface
Definition at line 269 of file MOM_regridding.F90.
References build_grid_arbitrary(), build_grid_hycom1(), build_grid_slight(), build_rho_grid(), build_sigma_grid(), build_zstar_grid(), calc_h_new_by_dz(), check_remapping_grid(), convective_adjustment(), mom_error_handler::mom_error(), regrid_consts::regridding_hycom1, and regrid_consts::regridding_slight.
 !------------------------------------------------------------------------------
 ! This routine takes care of (1) building a new grid and (2) remapping between
 ! the old grid and the new grid. The creation of the new grid can be based
 ! on z coordinates, target interface densities, sigma coordinates or any
 ! arbitrary coordinate system.
 !   The MOM6 interface positions are always calculated from the bottom up by
 ! accumulating the layer thicknesses starting at z=-G%bathyT.  z increases
 ! upwards (decreasing k-index).
 !   The new grid is defined by the change in position of those interfaces in z
 !       dzInterface = zNew - zOld.
 !   Thus, if the regridding inflates the top layer, hNew(1) > hOld(1), then the
 ! second interface moves downward, zNew(2) < zOld(2), and dzInterface(2) < 0.
 !       hNew(k) = hOld(k) - dzInterface(k+1) + dzInterface(k)
 ! IMPORTANT NOTE:
 !   This is the converse of the sign convention used in the remapping code!
 !------------------------------------------------------------------------------
   ! Arguments
   type(remapping_cs),                         intent(in)    :: remapcs !< Remapping parameters and options
   type(regridding_cs),                        intent(in)    :: cs     !< Regridding control structure
   type(ocean_grid_type),                      intent(in)    :: g      !< Ocean grid structure
   type(verticalgrid_type),                    intent(in)    :: gv     !< Ocean vertical grid structure
   real, dimension(SZI_(G),SZJ_(G), SZK_(GV)), intent(inout) :: h      !< Current 3D grid obtained after the last time step
   type(thermo_var_ptrs),                      intent(inout) :: tv     !< Thermodynamical variables (T, S, ...)
   real, dimension(SZI_(G),SZJ_(G), SZK_(GV)), intent(inout) :: h_new  !< New 3D grid consistent with target coordinate
   real, dimension(SZI_(G),SZJ_(G), SZK_(GV)+1), intent(inout) :: dzinterface !< The change in position of each interface
   ! Local variables
   real :: trickgnucompiler
   select case ( cs%regridding_scheme )
     case ( regridding_zstar )
       call build_zstar_grid( cs, g, gv, h, dzinterface )
       call calc_h_new_by_dz(g, gv, h, dzinterface, h_new)
     case ( regridding_sigma )
       call build_sigma_grid( cs, g, gv, h, dzinterface )
       call calc_h_new_by_dz(g, gv, h, dzinterface, h_new)
     case ( regridding_rho )
       call convective_adjustment(g, gv, h, tv)
       call build_rho_grid( g, gv, h, tv, dzinterface, remapcs, cs )
       call calc_h_new_by_dz(g, gv, h, dzinterface, h_new)
     case ( regridding_arbitrary )
       call build_grid_arbitrary( g, gv, h, dzinterface, trickgnucompiler, cs )
       call calc_h_new_by_dz(g, gv, h, dzinterface, h_new)
     case ( regridding_hycom1 )
       call build_grid_hycom1( g, gv, h, tv, dzinterface, remapcs, cs )
       call calc_h_new_by_dz(g, gv, h, dzinterface, h_new)
     case ( regridding_slight )
       call build_grid_slight( g, gv, h, tv, dzinterface, remapcs, cs )
       call calc_h_new_by_dz(g, gv, h, dzinterface, h_new)
     case default
       call mom_error(fatal,'MOM_regridding, regridding_main: '//&
                      'Unknown regridding scheme selected!')
   end select ! type of grid
 #ifdef __DO_SAFETY_CHECKS__
   call check_remapping_grid(g, gv, h, dzinterface,'in regridding_main')
 #endif
subroutine mom_regridding::regridding_memory_deallocation (type(regridding_cs), intent(inout) CS) private
Deallocate memory for regridding.
Parameters
[in,out] cs Regridding control structure
Definition at line 2763 of file MOM_regridding.F90.
Referenced by end_regridding().
   type(regridding_cs), intent(inout) :: cs !< Regridding control structure
   ! Target values
   deallocate( cs%target_density )
   deallocate( cs%coordinateResolution )
   if (allocated(cs%max_interface_depths) ) deallocate( cs%max_interface_depths )
   if (allocated(cs%max_layer_thickness) ) deallocate( cs%max_layer_thickness )
subroutine mom_regridding::regridding_set_ppolys (real, dimension(:), intent(in) densities, type(regridding_cs), intent(in) CS, integer, intent(in) n0, real, dimension(:), intent(in) h0, real, dimension(:,:), intent(inout) ppoly0_E, real, dimension(:,:), intent(inout) ppoly0_S, real, dimension(:,:), intent(inout) ppoly0_coefficients, integer, intent(inout) degree) private
Given the set of target values and cell densities, this routine builds an interpolated profile for the densities within each grid cell. It may happen that, given a high-order interpolator, the number of available layers is insufficient (e.g., there are two available layers for a third-order PPM ih4 scheme). In these cases, we resort to the simplest continuous linear scheme (P1M h2).
Parameters
[in] densities Actual cell densities
[in] n0 Number of cells on source grid
[in] h0 cell widths on source grid
[in,out] ppoly0_e Edge value of polynomial
[in,out] ppoly0_s Edge slope of polynomial
[in,out] ppoly0_coefficients Coefficients of polynomial
[in,out] degree The degree of the polynomials
[in] cs Parameters used for regridding
Definition at line 1879 of file MOM_regridding.F90.
References degree_1, degree_2, degree_3, degree_4, interpolation_p1m_h2, interpolation_p1m_h4, interpolation_p1m_ih4, interpolation_p3m_ih4ih3, interpolation_p3m_ih6ih5, interpolation_plm, interpolation_ppm_h4, interpolation_ppm_ih4, interpolation_pqm_ih4ih3, and interpolation_pqm_ih6ih5.
Referenced by build_grid_hycom1(), build_rho_grid(), and rho_interfaces_col().
   real, dimension(:),  intent(in)    :: densities !< Actual cell densities
   integer,             intent(in)    :: n0 !< Number of cells on source grid
   real, dimension(:),  intent(in)    :: h0 !< cell widths on source grid
   real, dimension(:,:),intent(inout) :: ppoly0_e            !< Edge value of polynomial
   real, dimension(:,:),intent(inout) :: ppoly0_s            !< Edge slope of polynomial
   real, dimension(:,:),intent(inout) :: ppoly0_coefficients !< Coefficients of polynomial
   integer,             intent(inout) :: degree  !< The degree of the polynomials
   type(regridding_cs), intent(in)    :: cs !< Parameters used for regridding
   ! Reset piecewise polynomials
   ppoly0_e(:,:) = 0.0
   ppoly0_s(:,:) = 0.0
   ppoly0_coefficients(:,:) = 0.0
   ! Compute the interpolated profile of the density field and build grid
   select case ( cs%interpolation_scheme )
     case ( interpolation_p1m_h2 )
       degree = degree_1
       call edge_values_explicit_h2( n0, h0, densities, ppoly0_e )
       call p1m_interpolation( n0, h0, densities, ppoly0_e, ppoly0_coefficients )
       if ( cs%boundary_extrapolation) then
         call p1m_boundary_extrapolation( n0, h0, densities, ppoly0_e, ppoly0_coefficients )
       end if
     case ( interpolation_p1m_h4 )
       degree = degree_1
       if ( n0 >= 4 ) then
         call edge_values_explicit_h4( n0, h0, densities, ppoly0_e )
       else
         call edge_values_explicit_h2( n0, h0, densities, ppoly0_e )
       end if
       call p1m_interpolation( n0, h0, densities, ppoly0_e, ppoly0_coefficients )
       if ( cs%boundary_extrapolation) then
         call p1m_boundary_extrapolation( n0, h0, densities, ppoly0_e, ppoly0_coefficients )
       end if
     case ( interpolation_p1m_ih4 )
       degree = degree_1
       if ( n0 >= 4 ) then
         call edge_values_implicit_h4( n0, h0, densities, ppoly0_e )
       else
         call edge_values_explicit_h2( n0, h0, densities, ppoly0_e )
       end if
       call p1m_interpolation( n0, h0, densities, ppoly0_e, ppoly0_coefficients )
       if ( cs%boundary_extrapolation) then
         call p1m_boundary_extrapolation( n0, h0, densities, ppoly0_e, ppoly0_coefficients )
       end if
     case ( interpolation_plm )
       degree = degree_1
       call plm_reconstruction( n0, h0, densities, ppoly0_e, ppoly0_coefficients )
       if ( cs%boundary_extrapolation) then
         call plm_boundary_extrapolation( n0, h0, densities, ppoly0_e, ppoly0_coefficients )
       end if
     case ( interpolation_ppm_h4 )
       if ( n0 >= 4 ) then
         degree = degree_2
         call edge_values_explicit_h4( n0, h0, densities, ppoly0_e )
         call ppm_reconstruction( n0, h0, densities, ppoly0_e, ppoly0_coefficients )
         if ( cs%boundary_extrapolation) then
           call ppm_boundary_extrapolation( n0, h0, densities, ppoly0_e, ppoly0_coefficients )
         end if
       else
         degree = degree_1
         call edge_values_explicit_h2( n0, h0, densities, ppoly0_e )
         call p1m_interpolation( n0, h0, densities, ppoly0_e, ppoly0_coefficients )
         if ( cs%boundary_extrapolation) then
           call p1m_boundary_extrapolation( n0, h0, densities, ppoly0_e, ppoly0_coefficients )
         end if
       end if
     case ( interpolation_ppm_ih4 )
       if ( n0 >= 4 ) then
         degree = degree_2
         call edge_values_implicit_h4( n0, h0, densities, ppoly0_e )
         call ppm_reconstruction( n0, h0, densities, ppoly0_e, ppoly0_coefficients )
         if ( cs%boundary_extrapolation) then
           call ppm_boundary_extrapolation( n0, h0, densities, ppoly0_e, ppoly0_coefficients )
         end if
       else
         degree = degree_1
         call edge_values_explicit_h2( n0, h0, densities, ppoly0_e )
         call p1m_interpolation( n0, h0, densities, ppoly0_e, ppoly0_coefficients )
         if ( cs%boundary_extrapolation) then
           call p1m_boundary_extrapolation( n0, h0, densities, ppoly0_e, ppoly0_coefficients )
         end if
       end if
     case ( interpolation_p3m_ih4ih3 )
       if ( n0 >= 4 ) then
         degree = degree_3
         call edge_values_implicit_h4( n0, h0, densities, ppoly0_e )
         call edge_slopes_implicit_h3( n0, h0, densities, ppoly0_s )
         call p3m_interpolation( n0, h0, densities, ppoly0_e, ppoly0_s, ppoly0_coefficients )
         if ( cs%boundary_extrapolation) then
           call p3m_boundary_extrapolation( n0, h0, densities, ppoly0_e, ppoly0_s, ppoly0_coefficients )
         end if
       else
         degree = degree_1
         call edge_values_explicit_h2( n0, h0, densities, ppoly0_e )
         call p1m_interpolation( n0, h0, densities, ppoly0_e, ppoly0_coefficients )
         if ( cs%boundary_extrapolation) then
           call p1m_boundary_extrapolation( n0, h0, densities, ppoly0_e, ppoly0_coefficients )
         end if
       end if
     case ( interpolation_p3m_ih6ih5 )
       if ( n0 >= 6 ) then
         degree = degree_3
         call edge_values_implicit_h6( n0, h0, densities, ppoly0_e )
         call edge_slopes_implicit_h5( n0, h0, densities, ppoly0_s )
         call p3m_interpolation( n0, h0, densities, ppoly0_e, ppoly0_s, ppoly0_coefficients )
         if ( cs%boundary_extrapolation) then
           call p3m_boundary_extrapolation( n0, h0, densities, ppoly0_e, ppoly0_s, ppoly0_coefficients )
         end if
       else
         degree = degree_1
         call edge_values_explicit_h2( n0, h0, densities, ppoly0_e )
         call p1m_interpolation( n0, h0, densities, ppoly0_e, ppoly0_coefficients )
         if ( cs%boundary_extrapolation) then
           call p1m_boundary_extrapolation( n0, h0, densities, ppoly0_e, ppoly0_coefficients )
         end if
       end if
     case ( interpolation_pqm_ih4ih3 )
       if ( n0 >= 4 ) then
         degree = degree_4
         call edge_values_implicit_h4( n0, h0, densities, ppoly0_e )
         call edge_slopes_implicit_h3( n0, h0, densities, ppoly0_s )
         call pqm_reconstruction( n0, h0, densities, ppoly0_e, ppoly0_s, ppoly0_coefficients )
         if ( cs%boundary_extrapolation) then
           call pqm_boundary_extrapolation_v1( n0, h0, densities, ppoly0_e, ppoly0_s, ppoly0_coefficients )
         end if
       else
         degree = degree_1
         call edge_values_explicit_h2( n0, h0, densities, ppoly0_e )
         call p1m_interpolation( n0, h0, densities, ppoly0_e, ppoly0_coefficients )
         if ( cs%boundary_extrapolation) then
           call p1m_boundary_extrapolation( n0, h0, densities, ppoly0_e, ppoly0_coefficients )
         end if
       end if
     case ( interpolation_pqm_ih6ih5 )
       if ( n0 >= 6 ) then
         degree = degree_4
         call edge_values_implicit_h6( n0, h0, densities, ppoly0_e )
         call edge_slopes_implicit_h5( n0, h0, densities, ppoly0_s )
         call pqm_reconstruction( n0, h0, densities, ppoly0_e, ppoly0_s, ppoly0_coefficients )
         if ( cs%boundary_extrapolation) then
           call pqm_boundary_extrapolation_v1( n0, h0, densities, ppoly0_e, ppoly0_s, ppoly0_coefficients )
         end if
       else
         degree = degree_1
         call edge_values_explicit_h2( n0, h0, densities, ppoly0_e )
         call p1m_interpolation( n0, h0, densities, ppoly0_e, ppoly0_coefficients )
         if ( cs%boundary_extrapolation) then
           call p1m_boundary_extrapolation( n0, h0, densities, ppoly0_e, ppoly0_coefficients )
         end if
       end if
   end select
subroutine mom_regridding::rho_interfaces_col (real, dimension(nz), intent(in) rho_col, real, dimension(nz), intent(in) h_col, real, dimension(nz+1), intent(in) z_col, real, dimension(nz+1), intent(in) rho_tgt, integer, intent(in) nz, real, dimension(nz+1), intent(inout) z_col_new, type(regridding_cs), intent(in) CS, logical, dimension(nz+1), intent(inout) reliable, logical, intent(in), optional debug) private
Finds the new interface locations in a column of water that match the prescribed target densities.
Parameters
[in] nz Number of layers
[in] rho_col Initial layer reference densities.
[in] h_col Initial layer thicknesses.
[in] z_col Initial interface heights.
[in] rho_tgt Interface target densities.
[in,out] z_col_new New interface heights.
[in] cs Regridding control structure
[in,out] reliable If true, the interface positions are well defined from a stable region.
[in] debug If present and true, do debugging checks.
Definition at line 1484 of file MOM_regridding.F90.
References nr_iterations, nr_tolerance, and regridding_set_ppolys().
Referenced by build_grid_slight().
   integer,               intent(in)    :: nz      !< Number of layers
   real, dimension(nz),   intent(in)    :: rho_col !< Initial layer reference densities.
   real, dimension(nz),   intent(in)    :: h_col   !< Initial layer thicknesses.
   real, dimension(nz+1), intent(in)    :: z_col   !< Initial interface heights.
   real, dimension(nz+1), intent(in)    :: rho_tgt !< Interface target densities.
   real, dimension(nz+1), intent(inout) :: z_col_new !< New interface heights.
   type(regridding_cs),   intent(in)    :: cs      !< Regridding control structure
   logical, dimension(nz+1), intent(inout) :: reliable !< If true, the interface positions
                                                   !! are well defined from a stable region.
   logical, optional,     intent(in) :: debug      !< If present and true, do debugging checks.
   real, dimension(nz+1) :: ru_max_int ! The maximum and minimum densities in
   real, dimension(nz+1) :: ru_min_int ! an unstable region around an interface.
   real, dimension(nz)   :: ru_max_lay ! The maximum and minimum densities in
   real, dimension(nz)   :: ru_min_lay ! an unstable region containing a layer.
   real, dimension(nz,2) :: ppoly_i_e ! Edge value of polynomial
   real, dimension(nz,2) :: ppoly_i_s ! Edge slope of polynomial
   real, dimension(nz,CS%degree_i+1) :: ppoly_i_coefficients ! Coefficients of polynomial
   logical, dimension(nz)   :: unstable_lay ! If true, this layer is in an unstable region.
   logical, dimension(nz+1) :: unstable_int ! If true, this interface is in an unstable region.
   real :: rt  ! The current target density, in kg m-3.
   real :: zf  ! The fractional z-position within a layer of the target density.
   real :: rfn
   real :: a(5) ! Coefficients of a local polynomial minus the target density.
   real :: zf1, zf2, rfn1, rfn2
   real :: drfn_dzf, sgn, delta_zf, zf_prev
   real :: tol
   logical :: k_found ! If true, the position has been found.
   integer :: k_layer ! The index of the stable layer containing an interface.
   integer :: ppoly_degree
   integer :: k, k1, k1_min, itt, max_itt, m
   real :: z_sgn  ! 1 or -1, depending on whether z increases with increasing K.
   logical :: debugging
   debugging = .false. ; if (present(debug)) debugging = debug
   max_itt = nr_iterations
   tol = nr_tolerance
   z_sgn = 1.0 ; if ( z_col(1) > z_col(nz+1) ) z_sgn = -1.0
   if (debugging) then
     do k=1,nz
       if (abs((z_col(k+1) - z_col(k)) - z_sgn*h_col(k)) > &
           1.0e-14*(abs(z_col(k+1)) + abs(z_col(k)) + abs(h_col(k))) ) &
         call mom_error(fatal, "rho_interfaces_col: Inconsistent z_col and h_col")
     enddo
   endif
   if ( z_col(1) == z_col(nz+1) ) then
     ! This is a massless column!
     do k=1,nz+1 ; z_col_new(k) = z_col(1) ; reliable(k) = .true. ; enddo
     return
   endif
   ! This sets up the piecewise polynomials based on the rho_col profile.
   call regridding_set_ppolys(rho_col, cs, nz, h_col, ppoly_i_e, ppoly_i_s, &
                              ppoly_i_coefficients, ppoly_degree)
   ! Determine the density ranges of unstably stratified segments.
   ! Interfaces that start out in an unstably stratified segment can
   ! only escape if they are outside of the bounds of that segment, and no
   ! interfaces are ever mapped into an unstable segment.
   unstable_int(1) = .false.
   ru_max_int(1) = ppoly_i_e(1,1)
   unstable_lay(1) = (ppoly_i_e(1,1) > ppoly_i_e(1,2))
   ru_max_lay(1) = max(ppoly_i_e(1,1), ppoly_i_e(1,2))
   do k=2,nz
     unstable_int(k) = (ppoly_i_e(k-1,2) > ppoly_i_e(k,1))
     ru_max_int(k) = max(ppoly_i_e(k-1,2), ppoly_i_e(k,1))
     ru_min_int(k) = min(ppoly_i_e(k-1,2), ppoly_i_e(k,1))
     if (unstable_int(k) .and. unstable_lay(k-1)) &
       ru_max_int(k) = max(ru_max_lay(k-1), ru_max_int(k))
     unstable_lay(k) = (ppoly_i_e(k,1) > ppoly_i_e(k,2))
     ru_max_lay(k) = max(ppoly_i_e(k,1), ppoly_i_e(k,2))
     ru_min_lay(k) = min(ppoly_i_e(k,1), ppoly_i_e(k,2))
     if (unstable_lay(k) .and. unstable_int(k)) &
       ru_max_lay(k) = max(ru_max_int(k), ru_max_lay(k))
   enddo
   unstable_int(nz+1) = .false.
   ru_min_int(nz+1) = ppoly_i_e(nz,2)
   do k=nz,1,-1
     if (unstable_lay(k) .and. unstable_int(k+1)) &
       ru_min_lay(k) = min(ru_min_int(k+1), ru_min_lay(k))
     if (unstable_int(k) .and. unstable_lay(k)) &
       ru_min_int(k) = min(ru_min_lay(k), ru_min_int(k))
   enddo
   z_col_new(1) = z_col(1) ; reliable(1) = .true.
   k1_min = 1
   do k=2,nz ! Find the locations of the various target densities for the interfaces.
     rt = rho_tgt(k)
     k_layer = -1
     k_found = .false.
     ! Many light layers are found at the top, so start there.
     if (rt <= ppoly_i_e(k1_min,1)) then
       z_col_new(k) = z_col(k1_min)
       k_found = .true.
       ! Do not change k1_min for the next layer.
     elseif (k1_min == nz+1) then
       z_col_new(k) = z_col(nz+1)
     else
       ! Start with the previous location and search outward.
       if (unstable_int(k) .and. (rt >= ru_min_int(k)) .and. (rt <= ru_max_int(k))) then
         ! This interface started in an unstable region and should not move due to remapping.
         z_col_new(k) = z_col(k) ; reliable(k) = .false.
         k1_min = k ; k_found = .true.
       elseif ((rt >= ppoly_i_e(k-1,2)) .and. (rt <= ppoly_i_e(k,1))) then
         ! This interface is already in the right place and does not move.
         z_col_new(k) = z_col(k) ; reliable(k) = .true.
         k1_min = k ; k_found = .true.
       elseif (rt < ppoly_i_e(k-1,2)) then   ! Search upward
         do k1=k-1,k1_min,-1
           ! Check whether rt is in layer k.
           if ((rt < ppoly_i_e(k1,2)) .and. (rt > ppoly_i_e(k1,1))) then
             ! rt is in layer k.
             k_layer = k1
             k1_min = k1 ; k_found = .true. ; exit
           elseif (unstable_lay(k1) .and. (rt >= ru_min_lay(k1)) .and. (rt <= ru_max_lay(k1))) then
             ! rt would be found at unstable layer that it can not penetrate.
             !   It is possible that this can never happen?
             z_col_new(k) = z_col(k1+1) ; reliable(k) = .false.
             k1_min = k1 ; k_found = .true. ; exit
           endif
           ! Check whether rt is at interface K.
           if (k1 > 1) then ; if ((rt <= ppoly_i_e(k1,1)) .and. (rt >= ppoly_i_e(k1-1,2))) then
             ! rt is at interface K1
             z_col_new(k) = z_col(k1) ; reliable(k) = .true.
             k1_min = k1 ; k_found = .true. ; exit
           elseif (unstable_int(k1) .and. (rt >= ru_min_int(k1)) .and. (rt <= ru_max_int(k1))) then
             ! rt would be found at an unstable interface that it can not pass.
             !   It is possible that this can never happen?
             z_col_new(k) = z_col(k1) ; reliable(k) = .false.
             k1_min = k1 ; k_found = .true. ; exit
           endif ; endif
         enddo
         if (.not.k_found) then
           ! This should not happen unless k1_min = 1.
           if (k1_min < 2) then
             z_col_new(k) = z_col(k1_min)
           else
             z_col_new(k) = z_col(k1_min)
           endif
         endif
       else  ! Search downward
         do k1=k,nz
           if ((rt < ppoly_i_e(k1,2)) .and. (rt > ppoly_i_e(k1,1))) then
             ! rt is in layer k.
             k_layer = k1
             k1_min = k1 ; k_found = .true. ; exit
           elseif (unstable_lay(k1) .and. (rt >= ru_min_lay(k1)) .and. (rt <= ru_max_lay(k1))) then
             ! rt would be found at unstable layer that it can not penetrate.
             !   It is possible that this can never happen?
             z_col_new(k) = z_col(k1)
             reliable(k) = .false.
             k1_min = k1 ; k_found = .true. ; exit
           endif
           if (k1 < nz) then ; if ((rt <= ppoly_i_e(k1+1,1)) .and. (rt >= ppoly_i_e(k1,2))) then
             ! rt is at interface K1+1
             z_col_new(k) = z_col(k1+1) ; reliable(k) = .true.
             k1_min = k1+1 ; k_found = .true. ; exit
           elseif (unstable_int(k1+1) .and. (rt >= ru_min_int(k1+1)) .and. (rt <= ru_max_int(k1+1))) then
             ! rt would be found at an unstable interface that it can not pass.
             !   It is possible that this can never happen?
             z_col_new(k) = z_col(k1+1)
             reliable(k) = .false.
             k1_min = k1+1 ; k_found = .true. ; exit
           endif ; endif
         enddo
         if (.not.k_found) then
           z_col_new(k) = z_col(nz+1)
           if (rt >= ppoly_i_e(nz,2)) then
             reliable(k) = .true.
           else
             reliable(k) = .false.
           endif
         endif
       endif
       if (k_layer > 0) then  ! The new location is inside of layer k_layer.
         ! Note that this is coded assuming that this layer is stably stratified.
         if (.not.(ppoly_i_e(k1,2) > ppoly_i_e(k1,1))) call mom_error(fatal, &
           "build_grid_SLight: Erroneously searching for an interface in an unstratified layer.") !### COMMENT OUT LATER?
         ! Use the false position method to find the location (degree <= 1) or the first guess.
         zf = (rt - ppoly_i_e(k1,1)) / (ppoly_i_e(k1,2) - ppoly_i_e(k1,1))
         if (ppoly_degree > 1) then ! Iterate to find the solution.
           a(:) = 0.0 ; a(1) = ppoly_i_coefficients(k_layer,1) - rt
           do m=2,ppoly_degree+1 ; a(m) = ppoly_i_coefficients(k_layer,m) ; enddo
           ! Bracket the root.
           zf1 = 0.0 ; rfn1 = a(1)
           zf2 = 1.0 ; rfn2 =  a(1) + (a(2) + (a(3) + (a(4) + a(5))))
           if (rfn1 * rfn2 > 0.0) call mom_error(fatal, "build_grid_SLight: Bad bracketing.") !### COMMENT OUT LATER?
           do itt=1,max_itt
             rfn = a(1) + zf*(a(2) + zf*(a(3) + zf*(a(4) + zf*a(5))))
             ! Reset one of the ends of the bracket.
             if (rfn * rfn1 > 0.0) then
               zf1 = zf ; rfn1 = rfn
             else
               zf2 = zf ; rfn2 = rfn
             endif
             if (rfn1 == rfn2) exit
             drfn_dzf = (a(2) + zf*(2.0*a(3) + zf*(3.0*a(4) + zf*4.0*a(5))))
             sgn = 1.0 ; if (drfn_dzf < 0.0) sgn = -1.0
             if ((sgn*(zf - rfn) >= zf1 * abs(drfn_dzf)) .and. &
                 (sgn*(zf - rfn) <= zf2 * abs(drfn_dzf))) then
               delta_zf = -rfn / drfn_dzf
               zf = zf + delta_zf
             else ! Newton's method goes out of bounds, so use a false position method estimate
               zf_prev = zf
               zf = ( rfn2 * zf1 - rfn1 * zf2 ) / (rfn2 - rfn1)
               delta_zf = zf - zf_prev
             endif
             if (abs(delta_zf) < tol) exit
           enddo
         endif
         z_col_new(k) = z_col(k_layer) + zf * z_sgn * h_col(k_layer)
         reliable(k) = .true.
       endif
     endif
   enddo
   z_col_new(nz+1) = z_col(nz+1) ; reliable(nz+1) = .true.
subroutine, public mom_regridding::set_regrid_max_depths (type(regridding_cs), intent(inout) CS, real, dimension(cs%nk+1), intent(in) max_depths, real, intent(in), optional units_to_H)
Set maximum interface depths based on a vector of input values.
Parameters
[in,out] cs Regridding control structure
[in] max_depths Maximum interface depths, in arbitrary units
[in] units_to_h A conversion factor for max_depths into H units
Definition at line 2502 of file MOM_regridding.F90.
   type(regridding_cs),      intent(inout) :: cs !< Regridding control structure
   real, dimension(CS%nk+1), intent(in)    :: max_depths !< Maximum interface depths, in arbitrary units
   real, optional,           intent(in)    :: units_to_h !< A conversion factor for max_depths into H units
   ! Local variables
   real :: val_to_h
   integer :: k
   if (.not.allocated(cs%max_interface_depths)) allocate(cs%max_interface_depths(1:cs%nk+1))
   val_to_h = 1.0 ; if (present( units_to_h)) val_to_h = units_to_h
   if (max_depths(cs%nk+1) < max_depths(1)) val_to_h = -1.0*val_to_h
   ! Check for sign reversals in the depths.
   if (max_depths(cs%nk+1) < max_depths(1)) then
     do k=1,cs%nk ; if (max_depths(k+1) > max_depths(k)) &
       call mom_error(fatal, "Unordered list of maximum depths sent to set_regrid_max_depths!")
     enddo
   else
     do k=1,cs%nk ; if (max_depths(k+1) < max_depths(k)) &
       call mom_error(fatal, "Unordered list of maximum depths sent to set_regrid_max_depths.")
     enddo
   endif
   do k=1,cs%nk+1
     cs%max_interface_depths(k) = val_to_h * max_depths(k)
   enddo
subroutine, public mom_regridding::set_regrid_max_thickness (type(regridding_cs), intent(inout) CS, real, dimension(cs%nk+1), intent(in) max_h, real, intent(in), optional units_to_H)
Set maximum layer thicknesses based on a vector of input values.
Parameters
[in,out] cs Regridding control structure
[in] max_h Maximum interface depths, in arbitrary units
[in] units_to_h A conversion factor for max_h into H units
Definition at line 2533 of file MOM_regridding.F90.
   type(regridding_cs),      intent(inout) :: cs !< Regridding control structure
   real, dimension(CS%nk+1), intent(in)    :: max_h !< Maximum interface depths, in arbitrary units
   real, optional,           intent(in)    :: units_to_h !< A conversion factor for max_h into H units
   ! Local variables
   real :: val_to_h
   integer :: k
   if (.not.allocated(cs%max_layer_thickness)) allocate(cs%max_layer_thickness(1:cs%nk))
   val_to_h = 1.0 ; if (present( units_to_h)) val_to_h = units_to_h
   do k=1,cs%nk
     cs%max_layer_thickness(k) = val_to_h * max_h(k)
   enddo
subroutine, public mom_regridding::set_regrid_params (type(regridding_cs), intent(inout) CS, logical, intent(in), optional boundary_extrapolation, real, intent(in), optional min_thickness, real, intent(in), optional old_grid_weight, real, intent(in), optional depth_of_time_filter_shallow, real, intent(in), optional depth_of_time_filter_deep, real, intent(in), optional compress_fraction, real, intent(in), optional dz_min_surface, integer, intent(in), optional nz_fixed_surface, real, intent(in), optional Rho_ML_avg_depth, real, intent(in), optional nlay_ML_to_interior, logical, intent(in), optional fix_haloclines, real, intent(in), optional halocline_filt_len, real, intent(in), optional halocline_strat_tol, logical, intent(in), optional integrate_downward_for_e, real, intent(in), optional height_of_rigid_surface)
This subroutine can be used to set many of the parameters for MOM_regridding.
Parameters
[in,out] cs Regridding control structure
[in] boundary_extrapolation Extrapolate in boundary cells
[in] min_thickness Minimum thickness allowed when building the new grid (m)
[in] old_grid_weight Weight given to old coordinate when time-filtering grid
[in] depth_of_time_filter_shallow Depth to start cubic (H units)
[in] depth_of_time_filter_deep Depth to end cubic (H units)
[in] compress_fraction Fraction of compressibility to add to potential density
[in] dz_min_surface The fixed resolution in the topmost SLight_nkml_min layers (m)
[in] nz_fixed_surface The number of fixed-thickess layers at the top of the model
[in] rho_ml_avg_depth Averaging depth over which to determine mixed layer potential density (m)
[in] nlay_ml_to_interior Number of layers to offset the mixed layer density to find resolved stratification (nondim)
[in] fix_haloclines Detect regions with much weaker stratification in the coordinate
[in] halocline_filt_len Length scale over which to filter T & S when looking for spuriously unstable water mass profiles (m)
[in] halocline_strat_tol Value of the stratification ratio that defines a problematic halocline region.
[in] integrate_downward_for_e If true, integrate for interface positions downward from the top.
[in] height_of_rigid_surface Threshold height for detection of a rigid upper surface.
Definition at line 2648 of file MOM_regridding.F90.
Referenced by mom_diag_mediator::diag_update_target_grids().
   type(regridding_cs), intent(inout) :: cs !< Regridding control structure
   logical, optional, intent(in) :: boundary_extrapolation !< Extrapolate in boundary cells
   real,    optional, intent(in) :: min_thickness !< Minimum thickness allowed when building the new grid (m)
   real,    optional, intent(in) :: old_grid_weight !< Weight given to old coordinate when time-filtering grid
   real,    optional, intent(in) :: depth_of_time_filter_shallow !< Depth to start cubic (H units)
   real,    optional, intent(in) :: depth_of_time_filter_deep !< Depth to end cubic (H units)
   real,    optional, intent(in) :: compress_fraction !< Fraction of compressibility to add to potential density
   real,    optional, intent(in) :: dz_min_surface !< The fixed resolution in the topmost SLight_nkml_min layers (m)
   integer, optional, intent(in) :: nz_fixed_surface !< The number of fixed-thickess layers at the top of the model
   real,    optional, intent(in) :: rho_ml_avg_depth !< Averaging depth over which to determine mixed layer potential density (m)
   real,    optional, intent(in) :: nlay_ml_to_interior !< Number of layers to offset the mixed layer density to find resolved stratification (nondim)
   logical, optional, intent(in) :: fix_haloclines !< Detect regions with much weaker stratification in the coordinate
   real,    optional, intent(in) :: halocline_filt_len !< Length scale over which to filter T & S when looking for spuriously unstable water mass profiles (m)
   real,    optional, intent(in) :: halocline_strat_tol !< Value of the stratification ratio that defines a problematic halocline region.
   logical, optional, intent(in) :: integrate_downward_for_e !< If true, integrate for interface positions downward from the top.
   real,    optional, intent(in) :: height_of_rigid_surface !< Threshold height for detection of a rigid upper surface.
   if (present(boundary_extrapolation)) cs%boundary_extrapolation = boundary_extrapolation
   if (present(min_thickness)) cs%min_thickness = min_thickness
   if (present(old_grid_weight)) then
     if (old_grid_weight<0. .or. old_grid_weight>1.) &
       call mom_error(fatal,'MOM_regridding, set_regrid_params: Weight is out side the range 0..1!')
     cs%old_grid_weight = old_grid_weight
   endif
   if (present(depth_of_time_filter_shallow)) cs%depth_of_time_filter_shallow = depth_of_time_filter_shallow
   if (present(depth_of_time_filter_deep)) cs%depth_of_time_filter_deep = depth_of_time_filter_deep
   if (present(depth_of_time_filter_shallow) .or. present(depth_of_time_filter_deep)) then
     if (cs%depth_of_time_filter_deep<cs%depth_of_time_filter_shallow) call mom_error(fatal,'MOM_regridding, '//&
                      'set_regrid_params: depth_of_time_filter_deep<depth_of_time_filter_shallow!')
   endif
   if (present(compress_fraction)) cs%compressibility_fraction = compress_fraction
   if (present(dz_min_surface)) cs%dz_ml_min = dz_min_surface
   if (present(nz_fixed_surface)) cs%nz_fixed_surface = nz_fixed_surface
   if (present(rho_ml_avg_depth)) cs%Rho_ML_avg_depth = rho_ml_avg_depth
   if (present(nlay_ml_to_interior)) cs%nlay_ML_offset = nlay_ml_to_interior
   if (present(fix_haloclines)) cs%fix_haloclines = fix_haloclines
   if (present(halocline_filt_len)) cs%halocline_filter_length = halocline_filt_len
   if (present(halocline_strat_tol)) then
     if (halocline_strat_tol > 1.0) call mom_error(fatal, "set_regrid_params: "//&
         "HALOCLINE_STRAT_TOL must not exceed 1.0.")
     cs%halocline_strat_tol = halocline_strat_tol
   endif
   if (present(integrate_downward_for_e)) cs%integrate_downward_for_e = integrate_downward_for_e
   if (present(height_of_rigid_surface)) cs%height_of_rigid_surface = height_of_rigid_surface
subroutine, public mom_regridding::set_target_densities (type(regridding_cs), intent(inout) CS, real, dimension(cs%nk+1), intent(in) rho_int)
Set target densities based on vector of interface values.
Parameters
[in,out] cs Regridding control structure
[in] rho_int Interface densities
Definition at line 2492 of file MOM_regridding.F90.
   type(regridding_cs),      intent(inout) :: cs !< Regridding control structure
   real, dimension(CS%nk+1), intent(in)    :: rho_int !< Interface densities
   cs%target_density(:) = rho_int(:)
   cs%target_density_set = .true.
subroutine, public mom_regridding::set_target_densities_from_gv (type(verticalgrid_type), intent(in) GV, type(regridding_cs), intent(inout) CS)
Set target densities based on the old Rlay variable.
Parameters
[in] gv Ocean vertical grid structure
[in,out] cs Regridding control structure
Definition at line 2475 of file MOM_regridding.F90.
   type(verticalgrid_type), intent(in)    :: gv !< Ocean vertical grid structure
   type(regridding_cs),     intent(inout) :: cs !< Regridding control structure
   ! Local variables
   integer :: k, nz
   nz = cs%nk
   cs%target_density(1)    = gv%Rlay(1)+0.5*(gv%Rlay(1)-gv%Rlay(2))
   cs%target_density(nz+1) = gv%Rlay(nz)+0.5*(gv%Rlay(nz)-gv%Rlay(nz-1))
   do k = 2,nz
     cs%target_density(k) = cs%target_density(k-1) + cs%coordinateResolution(k)
   end do
   cs%target_density_set = .true.
subroutine, public mom_regridding::setcoordinateresolution (real, dimension(:), intent(in) dz, type(regridding_cs), intent(inout) CS)
Definition at line 2463 of file MOM_regridding.F90.
   real, dimension(:),  intent(in)    :: dz
   type(regridding_cs), intent(inout) :: cs
   if (size(dz)/=cs%nk) call mom_error( fatal, &
       'setCoordinateResolution: inconsistent number of levels' )
   cs%coordinateResolution(:) = dz(:)
real function, dimension(nk), public mom_regridding::uniformresolution (integer, intent(in) nk, character(len=*), intent(in) coordMode, real, intent(in) maxDepth, real, intent(in) rhoLight, real, intent(in) rhoHeavy)
Definition at line 2426 of file MOM_regridding.F90.
 !------------------------------------------------------------------------------
 ! Calculate a vector of uniform resolution in the units of the coordinate
 !------------------------------------------------------------------------------
   ! Arguments
   integer,          intent(in) :: nk
   character(len=*), intent(in) :: coordmode
   real,             intent(in) :: maxdepth, rholight, rhoheavy
   real                         :: uniformresolution(nk)
   ! Local variables
   integer :: scheme
   scheme = coordinatemode(coordmode)
   select case ( scheme )
     case ( regridding_zstar, regridding_hycom1, regridding_slight )
       uniformresolution(:) = maxdepth / real(nk)
     case ( regridding_rho )
       uniformresolution(:) = (rhoheavy - rholight) / real(nk)
     case ( regridding_sigma )
       uniformresolution(:) = 1. / real(nk)
     case default
       call mom_error(fatal, "MOM_regridding, uniformResolution: "//&
        "Unrecognized choice for coordinate mode ("//trim(coordmode)//").")
   end select ! type of grid
Variable Documentation
integer, parameter mom_regridding::degree_1 = 1 private
List of interpolant degrees.
Definition at line 197 of file MOM_regridding.F90.
Referenced by regridding_set_ppolys().
 integer, parameter :: degree_1 = 1, degree_2 = 2, degree_3 = 3, degree_4 = 4
integer, parameter mom_regridding::degree_2 = 2 private
Definition at line 197 of file MOM_regridding.F90.
Referenced by regridding_set_ppolys().
integer, parameter mom_regridding::degree_3 = 3 private
Definition at line 197 of file MOM_regridding.F90.
Referenced by regridding_set_ppolys().
integer, parameter mom_regridding::degree_4 = 4 private
Definition at line 197 of file MOM_regridding.F90.
Referenced by regridding_set_ppolys().
real, parameter mom_regridding::deviation_tolerance = 1e-10 private
Deviation tolerance between succesive grids in regridding iterations.
Definition at line 202 of file MOM_regridding.F90.
Referenced by build_rho_grid().
 real, parameter    :: deviation_tolerance = 1e-10
integer, parameter mom_regridding::interpolation_p1m_h2 = 0 private
O(h^2)
Definition at line 185 of file MOM_regridding.F90.
Referenced by initialize_regridding(), and regridding_set_ppolys().
 integer, parameter :: interpolation_p1m_h2     = 0 !< O(h^2)
integer, parameter mom_regridding::interpolation_p1m_h4 = 1 private
O(h^2)
Definition at line 186 of file MOM_regridding.F90.
Referenced by initialize_regridding(), and regridding_set_ppolys().
 integer, parameter :: interpolation_p1m_h4     = 1 !< O(h^2)
integer, parameter mom_regridding::interpolation_p1m_ih4 = 2 private
O(h^2)
Definition at line 187 of file MOM_regridding.F90.
Referenced by initialize_regridding(), and regridding_set_ppolys().
 integer, parameter :: interpolation_p1m_ih4    = 2 !< O(h^2)
integer, parameter mom_regridding::interpolation_p3m_ih4ih3 = 6 private
O(h^4)
Definition at line 191 of file MOM_regridding.F90.
Referenced by initialize_regridding(), and regridding_set_ppolys().
 integer, parameter :: interpolation_p3m_ih4ih3 = 6 !< O(h^4)
integer, parameter mom_regridding::interpolation_p3m_ih6ih5 = 7 private
O(h^4)
Definition at line 192 of file MOM_regridding.F90.
Referenced by initialize_regridding(), and regridding_set_ppolys().
 integer, parameter :: interpolation_p3m_ih6ih5 = 7 !< O(h^4)
integer, parameter mom_regridding::interpolation_plm = 3 private
O(h^2)
Definition at line 188 of file MOM_regridding.F90.
Referenced by initialize_regridding(), and regridding_set_ppolys().
 integer, parameter :: interpolation_plm        = 3 !< O(h^2)
integer, parameter mom_regridding::interpolation_ppm_h4 = 4 private
O(h^3)
Definition at line 189 of file MOM_regridding.F90.
Referenced by initialize_regridding(), and regridding_set_ppolys().
 integer, parameter :: interpolation_ppm_h4     = 4 !< O(h^3)
integer, parameter mom_regridding::interpolation_ppm_ih4 = 5 private
O(h^3)
Definition at line 190 of file MOM_regridding.F90.
Referenced by initialize_regridding(), and regridding_set_ppolys().
 integer, parameter :: interpolation_ppm_ih4    = 5 !< O(h^3)
integer, parameter mom_regridding::interpolation_pqm_ih4ih3 = 8 private
O(h^4)
Definition at line 193 of file MOM_regridding.F90.
Referenced by initialize_regridding(), and regridding_set_ppolys().
 integer, parameter :: interpolation_pqm_ih4ih3 = 8 !< O(h^4)
integer, parameter mom_regridding::interpolation_pqm_ih6ih5 = 9 private
O(h^5)
Definition at line 194 of file MOM_regridding.F90.
Referenced by initialize_regridding(), and regridding_set_ppolys().
 integer, parameter :: interpolation_pqm_ih6ih5 = 9 !< O(h^5)
integer, parameter mom_regridding::nb_regridding_iterations = 1 private
Maximum number of regridding iterations.
Definition at line 200 of file MOM_regridding.F90.
Referenced by build_rho_grid().
 integer, parameter :: nb_regridding_iterations = 1
integer, parameter mom_regridding::nr_iterations = 8 private
Maximum number of Newton-Raphson iterations. Newton-Raphson iterations are used to build the new grid by finding the coordinates associated with target densities and interpolations of degree larger than 1.
Definition at line 206 of file MOM_regridding.F90.
Referenced by get_polynomial_coordinate(), and rho_interfaces_col().
 integer, parameter :: nr_iterations = 8
real, parameter mom_regridding::nr_offset = 1e-6 private
When the N-R algorithm produces an estimate that lies outside [0,1], the estimate is set to be equal to the boundary location, 0 or 1, plus or minus an offset, respectively, when the derivative is zero at the boundary.
Definition at line 212 of file MOM_regridding.F90.
Referenced by get_polynomial_coordinate().
 real, parameter    :: nr_offset = 1e-6
real, parameter mom_regridding::nr_tolerance = 1e-12 private
Tolerance for Newton-Raphson iterations (stop when increment falls below this)
Definition at line 208 of file MOM_regridding.F90.
Referenced by get_polynomial_coordinate(), and rho_interfaces_col().
 real, parameter    :: nr_tolerance = 1e-12
character(len=320), parameter, public mom_regridding::regriddingcoordinatemodedoc = " LAYER - Isopycnal or stacked shallow water layers\n"// " Z* - stetched geopotential z*\n"// " SIGMA - terrain following coordinates\n"// " RHO - continuous isopycnal\n"// " HYCOM1 - HyCOM-like hybrid coordinate\n"// " SLIGHT - stretched coordinates above continuous isopycnal"
Documentation for coordinate options.
Definition at line 158 of file MOM_regridding.F90.
 character(len=320), parameter, public :: regriddingCoordinateModeDoc = &
                  " LAYER - Isopycnal or stacked shallow water layers\n"//&
                  " Z*    - stetched geopotential z*\n"//&
                  " SIGMA - terrain following coordinates\n"//&
                  " RHO   - continuous isopycnal\n"//&
                  " HYCOM1 - HyCOM-like hybrid coordinate\n"//&
                  " SLIGHT - stretched coordinates above continuous isopycnal"
logical, parameter, public mom_regridding::regriddingdefaultboundaryextrapolation = .false.
Definition at line 179 of file MOM_regridding.F90.
Referenced by initialize_regridding().
 logical, parameter, public :: regriddingdefaultboundaryextrapolation = .false.
character(len=6), parameter, public mom_regridding::regriddingdefaultinterpscheme = "P1M_H2"
Definition at line 178 of file MOM_regridding.F90.
 character(len=6), parameter, public :: regriddingDefaultInterpScheme = "P1M_H2"
real, parameter, public mom_regridding::regriddingdefaultminthickness = 1.e-3
Definition at line 180 of file MOM_regridding.F90.
Referenced by initialize_regridding().
 real, parameter, public :: regriddingdefaultminthickness = 1.e-3
character(len=338), parameter, public mom_regridding::regriddinginterpschemedoc = " P1M_H2 (2nd-order accurate)\n"// " P1M_H4 (2nd-order accurate)\n"// " P1M_IH4 (2nd-order accurate)\n"// " PLM (2nd-order accurate)\n"// " PPM_H4 (3rd-order accurate)\n"// " PPM_IH4 (3rd-order accurate)\n"// " P3M_IH4IH3 (4th-order accurate)\n"// " P3M_IH6IH5 (4th-order accurate)\n"// " PQM_IH4IH3 (4th-order accurate)\n"// " PQM_IH6IH5 (5th-order accurate)"
Definition at line 167 of file MOM_regridding.F90.
 character(len=338), parameter, public :: regriddingInterpSchemeDoc = &
                  " P1M_H2     (2nd-order accurate)\n"//&
                  " P1M_H4     (2nd-order accurate)\n"//&
                  " P1M_IH4    (2nd-order accurate)\n"//&
                  " PLM        (2nd-order accurate)\n"//&
                  " PPM_H4     (3rd-order accurate)\n"//&
                  " PPM_IH4    (3rd-order accurate)\n"//&
                  " P3M_IH4IH3 (4th-order accurate)\n"//&
                  " P3M_IH6IH5 (4th-order accurate)\n"//&
                  " PQM_IH4IH3 (4th-order accurate)\n"//&
                  " PQM_IH6IH5 (5th-order accurate)"