MOM6: mom_diapyc_energy_req Module Reference
mom_diapyc_energy_req Module Reference
Data Types
type diapyc_energy_req_cs
Functions/Subroutines
subroutine, public diapyc_energy_req_test (h_3d, dt, tv, G, GV)
subroutine, public diapyc_energy_req_calc (h_in, T_in, S_in, Kd, energy_Kd, dt, tv, G, GV)
subroutine find_pe_chg (Kddt_h, h_k, b_den_1, dTe_term, dSe_term, dT_km1_t2, dS_km1_t2, dT_to_dPE_k, dS_to_dPE_k, dT_to_dPEa, dS_to_dPEa, PE_chg, dPE_chg_dKd)
subroutine, public diapyc_energy_req_init (G, param_file, CS)
subroutine, public diapyc_energy_req_end (CS)
Function/Subroutine Documentation
subroutine, public mom_diapyc_energy_req::diapyc_energy_req_calc (real, dimension(szk_(g)), intent(in) h_in, real, dimension(szk_(g)), intent(in) T_in, real, dimension(szk_(g)), intent(in) S_in, real, dimension(szk_(g)+1), intent(in) Kd, real, intent(out) energy_Kd, real, intent(in) dt, type(thermo_var_ptrs), intent(inout) tv, type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV)
Definition at line 106 of file MOM_diapyc_energy_req.F90.
References mom_eos::calculate_specific_vol_derivs(), and find_pe_chg().
Referenced by diapyc_energy_req_test().
   type(ocean_grid_type),                 intent(in)    :: g
   type(verticalgrid_type),               intent(in)    :: gv
   real, dimension(SZK_(G)),              intent(in)    :: h_in, t_in, s_in
   real, dimension(SZK_(G)+1),            intent(in)    :: kd
   real,                                  intent(in)    :: dt
   real,                                  intent(out)   :: energy_kd
   type(thermo_var_ptrs),                 intent(inout) :: tv
 ! Arguments: h_in -  Layer thickness before entrainment, in m or kg m-2.
 !  (in)      T_in - The layer temperatures, in degC.
 !  (in)      S_in - The layer salinities, in g kg-1.
 !  (in)      Kd - The interfaces diapycnal diffusivities, in m2 s-1.
 !  (in/out)  tv - A structure containing pointers to any available
 !                 thermodynamic fields. Absent fields have NULL ptrs.
 !  (in)      dt - The amount of time covered by this call, in s.
 !  (out)     energy_Kd - The column-integrated rate of energy consumption
 !                 by diapycnal diffusion, in W m-2.
 !  (in)      G - The ocean's grid structure.
 !  (in)      GV - The ocean's vertical grid structure.
 !   This subroutine uses a substantially refactored tridiagonal equation for
 ! diapycnal mixing of temperature and salinity to estimate the potential energy
 ! change due to diapycnal mixing in a column of water.  It does this estimate
 ! 4 different ways, all of which should be equivalent, but reports only one.
 ! The various estimates are taken because they will later be used as templates
 ! for other bits of code.
   real, dimension(SZK_(G)) :: &
     p_lay, &    ! Average pressure of a layer, in Pa.
     dsv_dt, &   ! Partial derivative of specific volume with temperature, in m3 kg-1 K-1.
     dsv_ds, &   ! Partial derivative of specific volume with salinity, in m3 kg-1 / (g kg-1).
     t0, s0, &
     te, se, &
     dte, dse, & ! Running (1-way) estimates of temperature and salinity change.
     dt_to_dpe, & ! Partial derivative of column potential energy with the temperature
     ds_to_dpe, & ! and salinity changes within a layer, in J m-2 K-1 and J m-2 / (g kg-1).
     b_denom_1, & ! The first term in the denominator of b1, in m or kg m-2.
     c1, &       ! c1 is used by the tridiagonal solver, ND.
     h_tr        ! h_tr is h at tracer points with a h_neglect added to
                 ! ensure positive definiteness, in m or kg m-2.
   real, dimension(SZK_(G)+1) :: &
     pres, &     ! Interface pressures in Pa.
     dt_to_dpe_a, &
     ds_to_dpe_a, &
     dt_to_dpe_b, &
     ds_to_dpe_b, &
     pe_chg_k, & ! The integrated potential energy change within a timestep due
                 ! to the diffusivity at interface K, in J m-2.
     pechg, &
     kddt_h      ! The diapycnal diffusivity times a timestep divided by the
                 ! average thicknesses around a layer, in m or kg m-2.
   real :: &
     b1              ! b1 is used by the tridiagonal solver, in m-1 or m2 kg-1.
   real :: h_neglect ! A thickness that is so small it is usually lost
                     ! in roundoff and can be neglected, in m.
   real :: dte_term, dse_term
   real :: kddt_h_guess
   real :: htot
   real :: dt_k, dt_km1, ds_k, ds_km1  ! Temporary arrays
   real :: b1kd                        ! Temporary arrays
   real :: kd_rat, kdr_denom, i_kdr_denom  ! Temporary arrays
   real :: dte_t2, dse_t2, dt_km1_t2, ds_km1_t2, dt_k_t2, ds_k_t2
   ! The following are a bunch of diagnostic arrays for debugging purposes.
   real, dimension(SZK_(G)) :: &
     ta, sa
   real, dimension(SZK_(G)+1) :: &
     dpea_dkd, dpea_dkd_est, dpea_dkd_err, dpea_dkd_trunc, dpea_dkd_err_norm, &
     dpeb_dkd, dpeb_dkd_est, dpeb_dkd_err, dpeb_dkd_trunc, dpeb_dkd_err_norm
   real :: pe_chg_tot1a, pe_chg_tot2a, t_chg_tota
   real :: pe_chg_tot1b, pe_chg_tot2b, t_chg_totb
   real, dimension(SZK_(G)+1)  :: dpechg_dkd
   real :: pe_chg(6)
   real, dimension(6) :: dt_k_itt, ds_k_itt, dt_km1_itt, ds_km1_itt
   real :: i_g_earth
   real :: dkd_rat_dkd, ddt_k_dkd, dds_k_dkd, ddt_km1_dkd, dds_km1_dkd
   integer :: k, nz, itt, max_itt
   logical :: surface_bl, bottom_bl, debug
   nz = g%ke
   h_neglect = gv%H_subroundoff
   i_g_earth = 1.0 / g%G_earth
   surface_bl = .true. ; bottom_bl = .true. ; debug = .true.
   dpea_dkd(:) = 0.0 ; dpea_dkd_est(:) = 0.0 ; dpea_dkd_err(:) = 0.0 ; dpea_dkd_err_norm(:) = 0.0 ; dpea_dkd_trunc(:) = 0.0
   dpeb_dkd(:) = 0.0 ; dpeb_dkd_est(:) = 0.0 ; dpeb_dkd_err(:) = 0.0 ; dpeb_dkd_err_norm(:) = 0.0 ; dpeb_dkd_trunc(:) = 0.0
   htot = 0.0 ; pres(1) = 0.0
   do k=1,nz
     t0(k) = t_in(k) ; s0(k) = s_in(k)
     h_tr(k) = h_in(k)
     htot = htot + h_tr(k)
     pres(k+1) = pres(k) + g%g_Earth * gv%H_to_kg_m2 * h_tr(k)
     p_lay(k) = 0.5*(pres(k) + pres(k+1))
   enddo
   do k=1,nz
     h_tr(k) = max(h_tr(k), 1e-15*htot)
   enddo
   ! Introduce a diffusive flux variable, Kddt_h(K) = ea(k) = eb(k-1)
   kddt_h(1) = 0.0 ; kddt_h(nz+1) = 0.0
   do k=2,nz
     kddt_h(k) = min((gv%m_to_H**2*dt)*kd(k) / (0.5*(h_tr(k-1) + h_tr(k))),1e3*htot)
   enddo
   ! Solve the tridiagonal equations for new temperatures.
   call calculate_specific_vol_derivs(t0, s0, p_lay, dsv_dt, dsv_ds, 1, nz, tv%eqn_of_state)
   do k=1,nz
     dt_to_dpe(k) = 0.5 * i_g_earth *(pres(k+1)**2 - pres(k)**2) * dsv_dt(k)
     ds_to_dpe(k) = 0.5 * i_g_earth *(pres(k+1)**2 - pres(k)**2) * dsv_ds(k)
   enddo
   pe_chg_k(1) = 0.0 ; pe_chg_k(nz+1) = 0.0
   pechg(:) = 0.0 ; dpechg_dkd(:) = 0.0
   if (surface_bl) then  ! This version is appropriate for a surface boundary layer.
     b_denom_1(1) = h_tr(1)
     dt_to_dpe_a(1) = dt_to_dpe(1)
     ds_to_dpe_a(1) = ds_to_dpe(1)
     do k=2,nz
       ! At this point, Kddt_h(K) will be unknown because its value may depend
       ! on how much energy is available.
       ! Precalculate some temporary expressions that are independent of Kddt_h_guess.
       if (k==2) then
         dt_km1_t2 = (t0(k)-t0(k-1))
         ds_km1_t2 = (s0(k)-s0(k-1))
         dte_t2 = 0.0 ; dse_t2 = 0.0
       else
         dte_t2 = kddt_h(k-1) * ((t0(k-2) - t0(k-1)) + dte(k-2))
         dse_t2 = kddt_h(k-1) * ((s0(k-2) - s0(k-1)) + dse(k-2))
         dt_km1_t2 = (t0(k)-t0(k-1)) - &
               (kddt_h(k-1) / b_denom_1(k-1)) * ((t0(k-2) - t0(k-1)) + dte(k-2))
         ds_km1_t2 = (s0(k)-s0(k-1)) - &
               (kddt_h(k-1) / b_denom_1(k-1)) * ((s0(k-2) - s0(k-1)) + dse(k-2))
       endif
       dte_term = dte_t2 + b_denom_1(k-1) * (t0(k-1)-t0(k))
       dse_term = dse_t2 + b_denom_1(k-1) * (s0(k-1)-s0(k))
       ! Find the energy change due to a guess at the strength of diffusion at interface K.
       kddt_h_guess = kddt_h(k)
       call find_pe_chg(kddt_h_guess, h_tr(k), b_denom_1(k-1), &
                        dte_term, dse_term, dt_km1_t2, ds_km1_t2, &
                        dt_to_dpe(k), ds_to_dpe(k), dt_to_dpe_a(k-1), ds_to_dpe_a(k-1), &
                        pe_chg_k(k), dpea_dkd(k))
       if (debug) then
         do itt=1,5
           kddt_h_guess = (1.0+0.01*(itt-3))*kddt_h(k)
           call find_pe_chg(kddt_h_guess, h_tr(k), b_denom_1(k-1), &
                            dte_term, dse_term, dt_km1_t2, ds_km1_t2, &
                            dt_to_dpe(k), ds_to_dpe(k), dt_to_dpe_a(k-1), ds_to_dpe_a(k-1), &
                            pe_chg=pe_chg(itt))
         enddo
         ! Compare with a 4th-order finite difference estimate.
         dpea_dkd_est(k) = (4.0*(pe_chg(4)-pe_chg(2))/(0.02*kddt_h(k)) - &
                                (pe_chg(5)-pe_chg(1))/(0.04*kddt_h(k))) / 3.0
         dpea_dkd_trunc(k) = (pe_chg(4)-pe_chg(2))/(0.02*kddt_h(k)) - &
                             (pe_chg(5)-pe_chg(1))/(0.04*kddt_h(k))
         dpea_dkd_err(k) = (dpea_dkd_est(k) - dpea_dkd(k))
         dpea_dkd_err_norm(k) = (dpea_dkd_est(k) - dpea_dkd(k)) / &
                               (abs(dpea_dkd_est(k)) + abs(dpea_dkd(k)) + 1e-100)
       endif
       !   At this point, the final value of Kddt_h(K) is known, so the estimated
       ! properties for layer k-1 can be calculated.
       b1 = 1.0 / (b_denom_1(k-1) + kddt_h(k))
       c1(k) = kddt_h(k) * b1
       if (k==2) then
         te(1) = b1*(h_tr(1)*t0(1))
         se(1) = b1*(h_tr(1)*s0(1))
       else
         te(k-1) = b1 * (h_tr(k-1) * t0(k-1) + kddt_h(k-1) * te(k-2))
         se(k-1) = b1 * (h_tr(k-1) * s0(k-1) + kddt_h(k-1) * se(k-2))
       endif
       dte(k-1) = b1 * ( kddt_h(k)*(t0(k)-t0(k-1)) + dte_t2 )
       dse(k-1) = b1 * ( kddt_h(k)*(s0(k)-s0(k-1)) + dse_t2 )
       b_denom_1(k) = h_tr(k) + (b_denom_1(k-1) * b1) * kddt_h(k)
       dt_to_dpe_a(k) = dt_to_dpe(k) + c1(k)*dt_to_dpe_a(k-1)
       ds_to_dpe_a(k) = ds_to_dpe(k) + c1(k)*ds_to_dpe_a(k-1)
     enddo
     b1 = 1.0 / (b_denom_1(nz))
     te(nz) = b1 * (h_tr(nz) * t0(nz) + kddt_h(nz) * te(nz-1))
     se(nz) = b1 * (h_tr(nz) * s0(nz) + kddt_h(nz) * se(nz-1))
     dte(nz) = b1 * kddt_h(nz) * ((t0(nz-1)-t0(nz)) + dte(nz-1))
     dse(nz) = b1 * kddt_h(nz) * ((s0(nz-1)-s0(nz)) + dse(nz-1))
     do k=nz-1,1,-1
       te(k) = te(k) + c1(k+1)*te(k+1)
       se(k) = se(k) + c1(k+1)*se(k+1)
     enddo
     if (debug) then
       do k=1,nz ; ta(k) = te(k) ; sa(k) = se(k) ; enddo
       pe_chg_tot1a = 0.0 ; pe_chg_tot2a = 0.0 ; t_chg_tota = 0.0
       do k=1,nz
         pe_chg_tot1a = pe_chg_tot1a + (dt_to_dpe(k) * (te(k) - t0(k)) + &
                                       ds_to_dpe(k) * (se(k) - s0(k)))
         t_chg_tota = t_chg_tota + h_tr(k) * (te(k) - t0(k))
       enddo
       do k=2,nz
         pe_chg_tot2a = pe_chg_tot2a + pe_chg_k(k)
       enddo
     endif
   endif
   if (bottom_bl) then  ! This version is appropriate for a bottom boundary layer.
     b_denom_1(nz) = h_tr(nz)
     dt_to_dpe_b(nz) = dt_to_dpe(nz)
     ds_to_dpe_b(nz) = ds_to_dpe(nz)
     do k=nz,2,-1  ! Loop over interior interfaces.
       ! At this point, Kddt_h(K) will be unknown because its value may depend
       ! on how much energy is available.
       ! Precalculate some temporary expressions that are independent of Kddt_h_guess.
       if (k==nz) then
         dt_k_t2 = (t0(k-1)-t0(k))
         ds_k_t2 = (s0(k-1)-s0(k))
         dte_t2 = 0.0 ; dse_t2 = 0.0
       else
         dte_t2 = kddt_h(k+1) * ((t0(k+1) - t0(k)) + dte(k+1))
         dse_t2 = kddt_h(k+1) * ((s0(k+1) - s0(k)) + dse(k+1))
         dt_k_t2 = (t0(k-1)-t0(k)) - &
                 (kddt_h(k+1)/ b_denom_1(k)) * ((t0(k+1) - t0(k)) + dte(k+1))
         ds_k_t2 = (s0(k-1)-s0(k)) - &
                 (kddt_h(k+1)/ b_denom_1(k)) * ((s0(k+1) - s0(k)) + dse(k+1))
       endif
       dte_term = dte_t2 + b_denom_1(k) * (t0(k)-t0(k-1))
       dse_term = dse_t2 + b_denom_1(k) * (s0(k)-s0(k-1))
       ! Find the energy change due to a guess at the strength of diffusion at interface K.
       kddt_h_guess = kddt_h(k)
       call find_pe_chg(kddt_h_guess, h_tr(k-1), b_denom_1(k), &
                        dte_term, dse_term, dt_k_t2, ds_k_t2, &
                        dt_to_dpe(k-1), ds_to_dpe(k-1), dt_to_dpe_b(k), ds_to_dpe_b(k), &
                        pe_chg_k(k), dpeb_dkd(k))
       if (debug) then
         ! Compare with a 4th-order finite difference estimate.
         do itt=1,5
           kddt_h_guess = (1.0+0.01*(itt-3))*kddt_h(k)
           call find_pe_chg(kddt_h_guess, h_tr(k-1), b_denom_1(k), &
                            dte_term, dse_term, dt_k_t2, ds_k_t2, &
                            dt_to_dpe(k-1), ds_to_dpe(k-1), dt_to_dpe_b(k), ds_to_dpe_b(k), &
                            pe_chg=pe_chg(itt))
         enddo
         dpeb_dkd_est(k) = (4.0*(pe_chg(4)-pe_chg(2))/(0.02*kddt_h(k)) - &
                                (pe_chg(5)-pe_chg(1))/(0.04*kddt_h(k))) / 3.0
         dpeb_dkd_trunc(k) = (pe_chg(4)-pe_chg(2))/(0.02*kddt_h(k)) - &
                             (pe_chg(5)-pe_chg(1))/(0.04*kddt_h(k))
         dpeb_dkd_err(k) = (dpeb_dkd_est(k) - dpeb_dkd(k))
         dpeb_dkd_err_norm(k) = (dpeb_dkd_est(k) - dpeb_dkd(k)) / &
                               (abs(dpeb_dkd_est(k)) + abs(dpeb_dkd(k)) + 1e-100)
       endif
       !   At this point, the final value of Kddt_h(K) is known, so the estimated
       ! properties for layer k can be calculated.
       b1 = 1.0 / (b_denom_1(k) + kddt_h(k))
       c1(k) = kddt_h(k) * b1
       if (k==nz) then
         te(nz) = b1* (h_tr(nz)*t0(nz))
         se(nz) = b1* (h_tr(nz)*s0(nz))
       else
         te(k) = b1 * (h_tr(k) * t0(k) + kddt_h(k+1) * te(k+1))
         se(k) = b1 * (h_tr(k) * s0(k) + kddt_h(k+1) * se(k+1))
       endif
       dte(k) = b1 * ( kddt_h(k)*(t0(k-1)-t0(k)) + dte_t2 )
       dse(k) = b1 * ( kddt_h(k)*(s0(k-1)-s0(k)) + dse_t2 )
       b_denom_1(k-1) = h_tr(k-1) + (b_denom_1(k) * b1) * kddt_h(k)
       dt_to_dpe_b(k-1) = dt_to_dpe(k-1) + c1(k)*dt_to_dpe_b(k)
       ds_to_dpe_b(k-1) = ds_to_dpe(k-1) + c1(k)*ds_to_dpe_b(k)
     enddo
     b1 = 1.0 / (b_denom_1(1))
     te(1) = b1 * (h_tr(1) * t0(1) + kddt_h(2) * te(2))
     se(1) = b1 * (h_tr(1) * s0(1) + kddt_h(2) * se(2))
     dte(1) = b1 * kddt_h(2) * ((t0(2)-t0(1)) + dte(2))
     dse(1) = b1 * kddt_h(2) * ((s0(2)-s0(1)) + dse(2))
     do k=2,nz
       te(k) = te(k) + c1(k)*te(k-1)
       se(k) = se(k) + c1(k)*se(k-1)
     enddo
     if (debug) then
       pe_chg_tot1b = 0.0 ; pe_chg_tot2b = 0.0 ; t_chg_totb = 0.0
       do k=1,nz
         pe_chg_tot1b = pe_chg_tot1b + (dt_to_dpe(k) * (te(k) - t0(k)) + &
                                        ds_to_dpe(k) * (se(k) - s0(k)))
         t_chg_totb = t_chg_totb + h_tr(k) * (te(k) - t0(k))
       enddo
       do k=2,nz
         pe_chg_tot2b = pe_chg_tot2b + pe_chg_k(k)
       enddo
     endif
   endif
   energy_kd = 0.0 ; do k=2,nz ; energy_kd = energy_kd + pe_chg_k(k) ; enddo
   energy_kd = energy_kd / dt
   k=nz
subroutine, public mom_diapyc_energy_req::diapyc_energy_req_end (type(diapyc_energy_req_cs), pointer CS)
Definition at line 554 of file MOM_diapyc_energy_req.F90.
   type(diapyc_energy_req_cs), pointer :: cs
   if (associated(cs)) deallocate(cs)
subroutine, public mom_diapyc_energy_req::diapyc_energy_req_init (type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(diapyc_energy_req_cs), pointer CS)
Definition at line 531 of file MOM_diapyc_energy_req.F90.
References mom_file_parser::log_version().
   type(ocean_grid_type),        intent(in) :: g
   type(param_file_type),        intent(in) :: param_file
   type(diapyc_energy_req_cs),   pointer    :: cs
 ! Arguments: param_file - A structure indicating the open file to parse for
 !                         model parameter values.
 !  (in/out)  Reg - A pointer that is set to point to the tracer registry.
   integer, save :: init_calls = 0
 ! This include declares and sets the variable "version".
 #include "version_variable.h"
   character(len=40)  :: mod = "MOM_diapyc_energy_req" ! This module's name.
   character(len=256) :: mesg    ! Message for error messages.
   if (.not.associated(cs)) then ; allocate(cs)
   else ; return ; endif
   cs%initialized = .true.
   ! Read all relevant parameters and write them to the model log.
   call log_version(param_file, mod, version, "")
subroutine, public mom_diapyc_energy_req::diapyc_energy_req_test (real, dimension(szi_(g),szj_(g),szk_(g)), intent(in) h_3d, real, intent(in) dt, type(thermo_var_ptrs), intent(inout) tv, type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV)
Definition at line 53 of file MOM_diapyc_energy_req.F90.
References diapyc_energy_req_calc().
   type(ocean_grid_type),                 intent(in)    :: g
   type(verticalgrid_type),               intent(in)    :: gv
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)), intent(in) :: h_3d
   type(thermo_var_ptrs),                 intent(inout) :: tv
   real,                                  intent(in)    :: dt
 ! Arguments: h_3d -  Layer thickness before entrainment, in m or kg m-2.
 !  (in/out)  tv - A structure containing pointers to any available
 !                 thermodynamic fields. Absent fields have NULL ptrs.
 !  (in)      dt - The amount of time covered by this call, in s.
 !  (in)      G - The ocean's grid structure.
 !  (in)      GV - The ocean's vertical grid structure.
   real, dimension(SZK_(G)) :: &
     t0, s0, &   ! T0 & S0 are columns of initial temperatures and salinities, in degC and g/kg.
     h_col       ! h_col is a column of thicknesses h at tracer points, in H (m or kg m-2).
   real, dimension(SZK_(G)+1) :: &
     kd, &       ! A column of diapycnal diffusivities at interfaces, in m2 s-1.
     h_top, h_bot ! Distances from the top or bottom, in H.
   real :: ustar, absf, htot
   real :: energy_kd ! The energy used by diapycnal mixing in W m-2.
   real :: tmp1  ! A temporary array.
   integer :: i, j, k, is, ie, js, je, nz, itt
   logical :: surface_bl, bottom_bl
   is = g%isc ; ie = g%iec ; js = g%jsc ; je = g%jec ; nz = g%ke
 !$OMP do
   do j=js,je ; do i=is,ie ; if (g%mask2dT(i,j) > 0.5) then
     htot = 0.0 ; h_top(1) = 0.0
     do k=1,nz
       t0(k) = tv%T(i,j,k) ; s0(k) = tv%S(i,j,k)
       h_col(k) = h_3d(i,j,k)
       h_top(k+1) = h_top(k) + h_col(k)
     enddo
     htot = h_top(nz+1)
     h_bot(nz+1) = 0.0
     do k=nz,1,-1
       h_bot(k) = h_bot(k+1) + h_col(k)
     enddo
     ustar = 0.01 ! Change this to being an input parameter?
     absf = 0.25*((abs(g%CoriolisBu(i-1,j-1)) + abs(g%CoriolisBu(i,j))) + &
                  (abs(g%CoriolisBu(i-1,j-1)) + abs(g%CoriolisBu(i,j))))
     kd(1) = 0.0 ; kd(nz+1) = 0.0
     do k=2,nz
       tmp1 = h_top(k) * h_bot(k) * gv%H_to_m
       kd(k) = ustar * 0.41 * (tmp1*ustar) / (absf*tmp1 + htot*ustar)
     enddo
     call diapyc_energy_req_calc(h_col, t0, s0, kd, energy_kd, dt, tv, g, gv)
   endif ; enddo ; enddo
subroutine mom_diapyc_energy_req::find_pe_chg (real, intent(in) Kddt_h, real, intent(in) h_k, real, intent(in) b_den_1, real, intent(in) dTe_term, real, intent(in) dSe_term, real, intent(in) dT_km1_t2, real, intent(in) dS_km1_t2, real, intent(in) dT_to_dPE_k, real, intent(in) dS_to_dPE_k, real, intent(in) dT_to_dPEa, real, intent(in) dS_to_dPEa, real, intent(out), optional PE_chg, real, intent(out), optional dPE_chg_dKd) private
Definition at line 433 of file MOM_diapyc_energy_req.F90.
Referenced by diapyc_energy_req_calc().
   real, intent(in)  :: kddt_h, h_k, b_den_1, dte_term, dse_term
   real, intent(in)  :: dt_km1_t2, ds_km1_t2, dt_to_dpe_k, ds_to_dpe_k
   real, intent(in)  :: dt_to_dpea, ds_to_dpea
   real, optional, intent(out) :: pe_chg
   real, optional, intent(out) :: dpe_chg_dkd
 !   This subroutine determines the total potential energy change due to mixing
 ! at an interface, including all of the implicit effects of the prescribed
 ! mixing at interfaces above.  Everything here is derived by careful manipulation
 ! of the robust tridiagonal solvers used for tracers by MOM6.
 !   The comments describing these arguments are for a downward mixing pass, but
 ! this routine can also be used for an upward pass with the sense of direction
 ! reversed.
 !
 ! Arguments: Kddt_h - The diffusivity at an interface times the time step and
 !                     divided by the average of the thicknesses around the
 !                     interface, in units of H (m or kg-2).
 !  (in)      h_k - The thickness of the layer below the interface, in H.
 !  (in)      b_den_1 - The first first term in the denominator of the pivot
 !                  for the tridiagonal solver, given by h_k plus a term that
 !                  is a fraction (determined from the tridiagonal solver) of
 !                  Kddt_h for the interface above, in H.
 !  (in)      dTe_term - A diffusivity-independent term related to the
 !                  temperature change in the layer below the interface, in K H.
 !  (in)      dSe_term - A diffusivity-independent term related to the
 !                  salinity change in the layer below the interface, in ppt H.
 !  (in)      dT_km1_t2 - A diffusivity-independent term related to the
 !                  temperature change in the layer above the interface, in K.
 !  (in)      dS_km1_t2 - A diffusivity-independent term related to the
 !                  salinity change in the layer above the interface, in ppt.
 !  (in)      dT_to_dPE_k - A factor (1/2*pres*mass_lay*dSpec_vol/dT) relating
 !                  a layer's temperature change to the change in column
 !                  potential energy, in J m-2 K-1.
 !  (in)      dS_to_dPE_k - A factor (1/2*pres*mass_lay*dSpec_vol/dS) relating
 !                  a layer's salinity change to the change in column
 !                  potential energy, in J m-2 ppt-1.
 !  (in)      dT_to_dPEa - A factor (1/2*pres*mass_lay*dSpec_vol/dT) relating
 !                  a layer's temperature change to the change in column
 !                  potential energy, including all implicit diffusive changes
 !                  in the temperatures of all the layers above, in J m-2 K-1.
 !  (in)      dS_to_dPEa - A factor (1/2*pres*mass_lay*dSpec_vol/dS) relating
 !                  a layer's salinity change to the change in column
 !                  potential energy, including all implicit diffusive changes
 !                  in the salinities of all the layers above, in J m-2 ppt-1.
 !  (out,opt) PE_chg - The change in column potential energy from applying
 !                  Kddt_h at the present interface, in J m-2.
 !  (out,opt) dPE_chg_dKd - The partial derivative of PE_chg with Kddt_h,
 !                  in units of J m-2 H-1.
   ! b_den_1 - The first term in the denominator of b1, in m or kg m-2.
   real :: b1            ! b1 is used by the tridiagonal solver, in H-1.
   real :: b1kd          ! Temporary array (nondim.)
   real :: dt_k, dt_km1  ! Temporary arrays in K.
   real :: ds_k, ds_km1  ! Temporary arrays in ppt.
   real :: i_kr_denom, dkr_dkd   ! Temporary arrays in H-2 and nondim.
   real :: ddt_k_dkd, ddt_km1_dkd ! Temporary arrays in K H-1.
   real :: dds_k_dkd, dds_km1_dkd ! Temporary arrays in ppt H-1.
   b1 = 1.0 / (b_den_1 + kddt_h)
   b1kd = kddt_h*b1
   ! Start with the temperature change in layer k-1 due to the diffusivity at
   ! interface K without considering the effects of changes in layer k.
   ! Calculate the change in PE due to the diffusion at interface K
   ! if Kddt_h(K+1) = 0.
   i_kr_denom = 1.0 / (h_k*b_den_1 + (b_den_1 + h_k)*kddt_h)
   dt_k = (kddt_h*i_kr_denom) * dte_term
   ds_k = (kddt_h*i_kr_denom) * dse_term
   if (present(pe_chg)) then
     ! Find the change in energy due to diffusion with strength Kddt_h at this interface.
     ! Increment the temperature changes in layer k-1 due the changes in layer k.
     dt_km1 = b1kd * ( dt_k + dt_km1_t2 )
     ds_km1 = b1kd * ( ds_k + ds_km1_t2 )
     pe_chg = (dt_to_dpe_k * dt_k + dt_to_dpea * dt_km1) + &
              (ds_to_dpe_k * ds_k + ds_to_dpea * ds_km1)
   endif
   if (present(dpe_chg_dkd)) then
     ! Find the derivatives of the temperature and salinity changes with Kddt_h.
     dkr_dkd = (h_k*b_den_1) * i_kr_denom**2
     ddt_k_dkd = dkr_dkd * dte_term
     dds_k_dkd = dkr_dkd * dse_term
     ddt_km1_dkd = (b1**2 * b_den_1) * ( dt_k + dt_km1_t2 ) + b1kd * ddt_k_dkd
     dds_km1_dkd = (b1**2 * b_den_1) * ( ds_k + ds_km1_t2 ) + b1kd * dds_k_dkd
     ! Calculate the partial derivative of Pe_chg with Kddt_h.
     dpe_chg_dkd = (dt_to_dpe_k * ddt_k_dkd + dt_to_dpea * ddt_km1_dkd) + &
                   (ds_to_dpe_k * dds_k_dkd + ds_to_dpea * dds_km1_dkd)
   endif